<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.def-power-nat">
      <expr>
        D(x) ((5*x-2)*(5*x-2))
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.product">
      <expr>
        D(x) (5*x-2)*(5*x-2)+(5*x-2)*D(x) (5*x-2)
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        5*(5*x-2)+(5*x-2)*D(x) (5*x-2)
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        5*(5*x-2)+(5*x-2)*5
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
  </list>
</reply>

