<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.product">
      <expr>
        D(x) (4*x^3-x)*(3*x^2+7*x)+(4*x^3-x)*D(x) (3*x^2+7*x)
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (12*x^2-1)*(3*x^2+7*x)+(4*x^3-x)*D(x) (3*x^2+7*x)
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (12*x^2-1)*(3*x^2+7*x)+(4*x^3-x)*(6*x+7)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
  </list>
</reply>

