<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.product">
      <expr>
        D(x) (5*x-7)*(2*x^3-3*x+1)+(5*x-7)*D(x) (2*x^3-3*x+1)
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        5*(2*x^3-3*x+1)+(5*x-7)*D(x) (2*x^3-3*x+1)
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        5*(2*x^3-3*x+1)+(5*x-7)*(6*x^2-3)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
  </list>
</reply>

