<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.def-power-nat">
      <expr>
        D(x) ((5*x^3+7*x)*(5*x^3+7*x))
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.product">
      <expr>
        D(x) (5*x^3+7*x)*(5*x^3+7*x)+(5*x^3+7*x)*D(x) (5*x^3+7*x)
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (15*x^2+7)*(5*x^3+7*x)+(5*x^3+7*x)*D(x) (5*x^3+7*x)
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (15*x^2+7)*(5*x^3+7*x)+(5*x^3+7*x)*(15*x^2+7)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
  </list>
</reply>

