<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.product">
      <expr>
        D(x) (3*x^2+2)*(5*x^3+4*x^2-7*x)+(3*x^2+2)*D(x) (5*x^3+4*x^2-7*x)
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        6*x*(5*x^3+4*x^2-7*x)+(3*x^2+2)*D(x) (5*x^3+4*x^2-7*x)
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        6*x*(5*x^3+4*x^2-7*x)+(3*x^2+2)*(15*x^2+8*x-7)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
  </list>
</reply>

