<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.product">
      <expr>
        D(x) (x^2+2*x)*(3*x+5)+(x^2+2*x)*D(x) (3*x+5)
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (2*x+2)*(3*x+5)+(x^2+2*x)*D(x) (3*x+5)
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (2*x+2)*(3*x+5)+(x^2+2*x)*3
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
  </list>
</reply>

