<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.def-power-nat">
      <expr>
        D(x) ((4*x-3)*(4*x-3))
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.product">
      <expr>
        D(x) (4*x-3)*(4*x-3)+(4*x-3)*D(x) (4*x-3)
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        4*(4*x-3)+(4*x-3)*D(x) (4*x-3)
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        4*(4*x-3)+(4*x-3)*4
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
  </list>
</reply>

