module Service.Omdoc where

-- spul integreren met ideas
-- document buggy rules for AM

import Data.Map(Map,empty,insert,(!))
-- import Data.String.UTF8

import Common.Library
import Service.OpenMathSupport
import qualified Main.Revision as MR
import Text.OpenMath.Object
import Text.XML.Interface

import Data.Maybe
import Domain.LinearAlgebra
import Domain.Math.Polynomial.Exercises
import Domain.Math.Derivative.Exercises
import Domain.Math.Numeric.Exercises
import Domain.Math.Polynomial.RationalExercises
import Domain.Math.Polynomial.IneqExercises
import Domain.Math.Equation.CoverUpExercise
import Domain.Math.Power.Exercises
import Domain.Math.Power.Equation.Exercises

import Text.XML

--------------------------------------------------------------------------------
{- Global info; should probably be generated by the makefile.
-}
--------------------------------------------------------------------------------

today  :: String
today  =  "Today's date"

--------------------------------------------------------------------------------
{- Different languages can be supported.
-}
--------------------------------------------------------------------------------

data Lang = EN | ES | DE | FR | NL | FI | ALL 

instance Show Lang where
  show EN = "en"
  show ES = "es"
  show DE = "de"
  show FR = "fr"
  show NL = "nl"
  show FI = "fi"

--------------------------------------------------------------------------------
{- Generate all files
-}
--------------------------------------------------------------------------------


generateallfiles :: IO ()
generateallfiles = 
      do let version = MR.version
         let revision = MR.revision
         omdocexercisefile version revision linearExercise
         omdocexercisefile version revision linearMixedExercise
         omdocexercisefile version revision quadraticExercise
         omdocexercisefile version revision higherDegreeExercise
         omdocexercisefile version revision rationalEquationExercise
         omdocexercisefile version revision ineqLinearExercise
         omdocexercisefile version revision coverUpExercise
         omdocexercisefile version revision fractionExercise
         omdocexercisefile version revision findFactorsExercise
         omdocexercisefile version revision ineqQuadraticExercise
         omdocexercisefile version revision ineqHigherDegreeExercise
         omdocexercisefile version revision simplifyRationalExercise
         omdocexercisefile version revision quadraticNoABCExercise
         omdocexercisefile version revision quadraticWithApproximation
         omdocexercisefile version revision derivativeExercise
         omdocexercisefile version revision derivativePolyExercise
         omdocexercisefile version revision derivativeProductExercise
         omdocexercisefile version revision derivativeQuotientExercise
         omdocexercisefile version revision simplifyPowerExercise
         omdocexercisefile version revision powerOfExercise
         omdocexercisefile version revision nonNegBrokenExpExercise
         omdocexercisefile version revision calcPowerExercise
         omdocexercisefile version revision powerEqExercise
         omdocexercisefile version revision expEqExercise
         omdocexercisefile version revision logEqExercise
         omdocexercisefile version revision gramSchmidtExercise
         omdocexercisefile version revision linearSystemExercise
         omdocexercisefile version revision gaussianElimExercise
         omdocexercisefile version revision systemWithMatrixExercise
         recbookfile version revision
           [sourcefile linearExercise
           ,sourcefile linearMixedExercise
           ,sourcefile quadraticExercise
           ,sourcefile higherDegreeExercise
           ,sourcefile rationalEquationExercise
           ,sourcefile ineqLinearExercise
           ,sourcefile coverUpExercise
           ,sourcefile fractionExercise
           ,sourcefile findFactorsExercise
           ,sourcefile ineqQuadraticExercise
           ,sourcefile ineqHigherDegreeExercise
           ,sourcefile simplifyRationalExercise
           ,sourcefile quadraticNoABCExercise
           ,sourcefile quadraticWithApproximation
           ,sourcefile derivativeExercise
           ,sourcefile derivativePolyExercise
           ,sourcefile derivativeProductExercise
           ,sourcefile derivativeQuotientExercise
           ,sourcefile simplifyPowerExercise
           ,sourcefile powerOfExercise
           ,sourcefile nonNegBrokenExpExercise
           ,sourcefile calcPowerExercise
           ,sourcefile powerEqExercise
           ,sourcefile expEqExercise
           ,sourcefile logEqExercise
           ,sourcefile gramSchmidtExercise
           ,sourcefile linearSystemExercise
           ,sourcefile gaussianElimExercise
           ,sourcefile systemWithMatrixExercise
           ]
           [omdocexerciserefs linearExercise
           ,omdocexerciserefs linearMixedExercise
           ,omdocexerciserefs quadraticExercise
           ,omdocexerciserefs higherDegreeExercise
           ,omdocexerciserefs rationalEquationExercise
           ,omdocexerciserefs ineqLinearExercise
           ,omdocexerciserefs coverUpExercise
           ,omdocexerciserefs fractionExercise
           ,omdocexerciserefs findFactorsExercise
           ,omdocexerciserefs ineqQuadraticExercise
           ,omdocexerciserefs ineqHigherDegreeExercise
           ,omdocexerciserefs simplifyRationalExercise
           ,omdocexerciserefs quadraticNoABCExercise
           ,omdocexerciserefs quadraticWithApproximation
           ,omdocexerciserefs derivativeExercise
           ,omdocexerciserefs derivativePolyExercise
           ,omdocexerciserefs derivativeProductExercise
           ,omdocexerciserefs derivativeQuotientExercise
           ,omdocexerciserefs simplifyPowerExercise
           ,omdocexerciserefs powerOfExercise
           ,omdocexerciserefs nonNegBrokenExpExercise
           ,omdocexerciserefs calcPowerExercise
           ,omdocexerciserefs powerEqExercise
           ,omdocexerciserefs expEqExercise
           ,omdocexerciserefs logEqExercise
           ,omdocexerciserefs gramSchmidtExercise
           ,omdocexerciserefs linearSystemExercise
           ,omdocexerciserefs gaussianElimExercise
           ,omdocexerciserefs systemWithMatrixExercise
           ]
       
--------------------------------------------------------------------------------
{- Generating the recbook for the exercise collections
-}
--------------------------------------------------------------------------------

recbookfile :: String -> Int -> [Element] -> [Element] -> IO ()
recbookfile version revision sourcefiles exercisesrefs = do
  let filestring = 
             xmldecl 
          ++ activemathdtd 
          ++ showXML
               (omdocelt 
                  ""
                  "http://www.activemath.org/namespaces/am_internal"
                  [omgroupelt "" "http://www.mathweb.org/omdoc"
                    [omgroupelt "IdeasExercises" ""
                      [metadataelt "IdeasExercises-metadata"
                        [titleelt "Ideas Exercises collection"
                        -- ,versionelt version (show revision) -- apparently not allowed
                        ]
                      ,omgroupelt "recbook_for_IdeasExercises" ""
                        (metadataelt ""
                          [titleelt "Complete Ideas Exercises Recbook"
                          ,dateelt "created" "2011-01-22"
                          ,dateelt "changed" today
                          ,creatorelt "aut" "Johan Jeuring"
                          ,sourceelt ""
                          ,formatelt "application/omdoc+xml"
                          -- ,extradataelt sourcefiles -- apparently not allowed
                          ]
                        :exercisesrefs
                        )
                      ]
                    ]
                  ]
               )
  writeFile (omdocpath ++ "RecBook_Exercises.omdoc") filestring
  writeFile (oqmathpath ++ "RecBook_Exercises.oqmath") filestring
  
sourcefile :: Exercise a -> Element
sourcefile ex = 
  sourcefileelt 
    "http://www.activemath.org/namespaces/am_internal" 
    ("omdoc/" ++ show (exerciseId ex))
    "1293473065000" -- last modified; don't know why or if this has to be provided

omdocrefpath  :: String
omdocrefpath  =  ""

omdocexerciserefs :: Exercise a -> Element
omdocexerciserefs ex = 
  let info             = mBExerciseInfo ! (exerciseId ex)
      len              = length (examples ex)
      refs             = map (\i -> omdocrefpath  -- relative dir (the same right now)
                                ++  context info  -- filename
                                ++  "/" 
                                ++  context info  -- exercise id
                                ++  show i)       -- and nr
                             [0..len-1]
      exercises        = map (`xrefelt` "exercise") refs
  in omgroupelt "" "" (metadataelt "" [titleelt (title info)]:exercises)

--------------------------------------------------------------------------------
{- Generating an omdoc file for an exercise
-}
--------------------------------------------------------------------------------

omdocpath :: String
omdocpath = "/Users/johanj/Documents/Research/ExerciseAssistants/Feedback/math-bridge/activemath/all/activemath-ideas/content/IdeasExercises/omdoc/"

oqmathpath :: String
oqmathpath = "/Users/johanj/Documents/Research/ExerciseAssistants/Feedback/math-bridge/activemath/all/activemath-ideas/content/IdeasExercises/oqmath/"

{-
omdocexercisefile :: (IsTerm a) => String -> Int -> Exercise a -> IO ()
omdocexercisefile version revision ex = 
  let info = mBExerciseInfo ! (exerciseId ex)
      filestring = 
             xmldecl 
          ++ activemathdtd 
          ++ showXML
               (omdocelt 
                  (context info ++ ".omdoc")
                  []
                  [metadataelt 
                    ""
                    [dateelt "created" "2011-01-22"
                    ,dateelt "changed" today
                    ,titleelt (title info)
                    ,creatorelt "aut" "Johan Jeuring"
                    ,versionelt version (show revision)
                    ]
                  ,theoryelt (context info) 
                             (omdocexercises ex)
                  ]
               )
  in writeFile (omdocpath ++ context info ++ ".omdoc") filestring
-}

omdocexercisefile :: (IsTerm a) => String -> Int -> Exercise a -> IO ()
omdocexercisefile version revision ex = do
  let info = mBExerciseInfo ! (exerciseId ex)
  let filestring = 
             xmldecl 
          ++ activemathdtd 
          ++ showXML
               (omdocelt 
                  (context info ++ ".omdoc")
                  []
                  [metadataelt 
                    ""
                    [dateelt "created" "2011-01-22"
                    ,dateelt "changed" today
                    ,titleelt (title info)
                    ,creatorelt "aut" "Johan Jeuring"
                    ,versionelt version (show revision)
                    ]
                  ,theoryelt (context info) 
                             (omdocexercises ex)
                  ]
               )
  writeFile (omdocpath ++ context info ++ ".omdoc") filestring
  writeFile (oqmathpath ++ context info ++ ".oqmath") filestring

omdocexercises :: (IsTerm a) => Exercise a -> [Element]
omdocexercises ex = catMaybes $ zipWith make [(0::Int)..] (examples ex)
 where
   info = mBExerciseInfo ! (exerciseId ex)
   langs = langSupported info
   make nr (dif, example) = 
      fmap (makeElement . omobj2xml) (toOpenMath ex example)
    where
      makeElement omobj =
         omdocexercise  
            (context info ++ show nr)
            (if null (for info) then Nothing else Just (for info))
            (show dif)
            langs
            (map (\l -> cmp info l ++ (show omobj)) langs)
            "IDEASGenerator"
            "strategy"
            (problemStatement info)
            (context info)
            omobj

omdocexercise :: String
              -> Maybe String
              -> String
              -> [Lang]
              -> [String]
              -> String
              -> String
              -> String
              -> String
              -> Element
              -> Element
omdocexercise 
    exerciseid 
    maybefor
    difficulty 
    langs 
    cmps
    interaction_generatorname 
    interaction_generatortype 
    problemstatement
    ctxt
    task
  = exerciseelt 
      exerciseid
      Nothing
      ([metadataelt
         ""
         [formatelt "AMEL1.0"
         ,extradataelt 
           (difficultyelt difficulty
           :case maybefor of
              Just for -> [relationelt for]
              Nothing  -> []
           )
         ]
       ]
       ++
       cmpelts langs cmps
       ++
       [interaction_generatorelt 
         interaction_generatorname 
         interaction_generatortype
         [parameterelt "problemstatement" [Left problemstatement]
         ,parameterelt "context"          [Left ctxt]
         ,parameterelt "difficulty"       [Left difficulty]
         ,parameterelt "task"             [Right task]
         ]
       ]
      )

--------------------------------------------------------------------------------
{- Info about exercises for ActiveMath
-}
--------------------------------------------------------------------------------

data MBExerciseInfo = MBExerciseInfo
  { title             :: String
  , for               :: String
  , langSupported     :: [Lang]
  , cmp               :: Lang -> String
  , problemStatement  :: String
  , context           :: String
  , difficulty        :: String
  }

mBExerciseInfo :: Map Id MBExerciseInfo
mBExerciseInfo =  
    insert (exerciseId coverUpExercise)            coverUpExerciseInfo
  $ insert (exerciseId derivativeExercise)         derivativeExerciseInfo
  $ insert (exerciseId gramSchmidtExercise)        gramSchmidtExerciseInfo
  $ insert (exerciseId linearSystemExercise)       linearSystemExerciseInfo
  $ insert (exerciseId gaussianElimExercise)       gaussianElimExerciseInfo
  $ insert (exerciseId systemWithMatrixExercise)   systemWithMatrixExerciseInfo
  $ insert (exerciseId powerOfExercise)            powerOfExerciseInfo
  $ insert (exerciseId nonNegBrokenExpExercise)    nonNegBrokenExpExerciseInfo
  $ insert (exerciseId calcPowerExercise)          calcPowerExerciseInfo
  $ insert (exerciseId powerEqExercise)            powerEqExerciseInfo
  $ insert (exerciseId expEqExercise)              expEqExerciseInfo
  $ insert (exerciseId logEqExercise)              logEqExerciseInfo
  $ insert (exerciseId derivativePolyExercise)     derivativePolyExerciseInfo
  $ insert (exerciseId derivativeProductExercise)  derivativeProductExerciseInfo
  $ insert (exerciseId derivativeQuotientExercise) derivativeQuotientExerciseInfo
  $ insert (exerciseId findFactorsExercise)        findFactorsExerciseInfo
  $ insert (exerciseId fractionExercise)           fractionExerciseInfo
  $ insert (exerciseId higherDegreeExercise)       higherDegreeExerciseInfo
  $ insert (exerciseId ineqHigherDegreeExercise)   ineqHigherDegreeExerciseInfo
  $ insert (exerciseId ineqLinearExercise)         ineqLinearExerciseInfo
  $ insert (exerciseId ineqQuadraticExercise)      ineqQuadraticExerciseInfo
  $ insert (exerciseId linearExercise)             linearExerciseInfo 
  $ insert (exerciseId linearMixedExercise)        linearMixedExerciseInfo
  $ insert (exerciseId quadraticExercise)          quadraticExerciseInfo
  $ insert (exerciseId quadraticNoABCExercise)     quadraticNoABCExerciseInfo
  $ insert (exerciseId quadraticWithApproximation) quadraticWithApproximationExerciseInfo
  $ insert (exerciseId rationalEquationExercise)   rationalEquationExerciseInfo
  $ insert (exerciseId simplifyPowerExercise)      simplifyPowerExerciseInfo
  $ insert (exerciseId simplifyRationalExercise)   simplifyRationalExerciseInfo
    empty

calcPowerExerciseInfo :: MBExerciseInfo
calcPowerExerciseInfo = MBExerciseInfo
  { title             = "Calculating powers"
  , for               = "mbase://mb_concepts/mb_numbers_and_computation/_01_02_05_03_Powers"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Calculate the power "
                          ES -> "Calcular la potencia "
                          DE -> "Berechnen Sie die Potenz "
                          FR -> "Calculer la puissance "
                          NL -> "Bereken de macht "
                          FI -> "Laske arvo potenssilausekkeelle "
  , problemStatement  = "Calculate the following power: "
  , context           = showId $ exerciseId calcPowerExercise
  , difficulty        = "medium"
  }

coverUpExerciseInfo :: MBExerciseInfo
coverUpExerciseInfo = MBExerciseInfo
  { title             = "Covering up in equations"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_04_Equations"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve the equation "
                          ES -> "Resolver la ecuación "
                          DE -> "Lösen Sie die Gleichung "
                          FR -> "Résoudre l'équation "
                          NL -> "Los de volgende vergelijking op "
                          FI -> "Ratkaise yhtälö "
  , problemStatement  = "Solve the following equation: "
  , context           = showId $ exerciseId coverUpExercise
  , difficulty        = "medium"
  }

derivativeExerciseInfo :: MBExerciseInfo
derivativeExerciseInfo = MBExerciseInfo
  { title             = "Derivatives"
  , for               = "mbase://mb_concepts/mb_calculus/_06_01_Single_Variable"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Calculate the derivative of the function "
                          ES -> "Calcular la derivada de la función "
                          DE -> "Bestimmen Sie die Ableitung der Funktion "
                          FR -> "Calculer la dérivée de la fonction "
                          NL -> "Bereken de afgeleide van de functie "
                          FI -> "Laske derivaatta funktiolle "
  , problemStatement  = "Calculate the derivative of the following function: "
  , context           = showId $ exerciseId derivativeExercise
  , difficulty        = "medium"
  }

derivativePolyExerciseInfo :: MBExerciseInfo
derivativePolyExerciseInfo = MBExerciseInfo
  { title             = "Differentiate polynomials"
  , for               = "mbase://mb_concepts/mb_calculus/_06_01_Single_Variable"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Calculate the derivative of the polynomial "
                          ES -> "Calcular la derivada del polinomio "
                          DE -> "Bestimmen Sie die Ableitung des Polynoms "
                          FR -> "Calculer la dérivée du polynôme "
                          NL -> "Bereken de afgeleide van de polynoom "
                          FI -> "Laske derivaatta polynomille "
  , problemStatement  = "Calculate the derivative of the following polynomial: "
  , context           = showId $ exerciseId derivativePolyExercise
  , difficulty        = "medium"
  }

derivativeProductExerciseInfo :: MBExerciseInfo
derivativeProductExerciseInfo = MBExerciseInfo
  { title             = "Differentiate product"
  , for               = "mbase://mb_concepts/mb_calculus/_06_01_Single_Variable"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Calculate the derivative of the product "
                          ES -> "Calcular la derivada del producto "
                          DE -> "Bestimmen Sie die Ableitung des Produkts "
                          FR -> "Calculer la dérivée du produit "
                          NL -> "Bereken de afgeleide van het product "
                          FI -> "Laske derivaatta tulolle "
  , problemStatement  = "Calculate the derivative of the following product: "
  , context           = showId $ exerciseId derivativeProductExercise
  , difficulty        = "medium"
  }

derivativeQuotientExerciseInfo :: MBExerciseInfo
derivativeQuotientExerciseInfo = MBExerciseInfo
  { title             = "Differentiate quotients"
  , for               = "mbase://mb_concepts/mb_calculus/_06_01_Single_Variable"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Calculate the derivative of the quotient "
                          ES -> "Calcular la derivada del cociente "
                          DE -> "Bestimmen Sie die Ableitung des Quotienten "
                          FR -> "Calculer la dérivée du quotient "
                          NL -> "Bereken de afgeleide van het quotiënt "
                          FI -> "Laske derivaatta osamäärälle "
  , problemStatement  = "Calculate the derivative of the following quotient: "
  , context           = showId $ exerciseId derivativeQuotientExercise
  , difficulty        = "medium"
  }

expEqExerciseInfo :: MBExerciseInfo
expEqExerciseInfo = MBExerciseInfo
  { title             = "Solving exponential equations"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_04_05_Exponential_Equations"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve the exponential equation "
                          ES -> "Resolver la ecuación exponencial "
                          DE -> "Lösen Sie die Exponentialgleichung "
                          FR -> "Résoudre l'équation exponentielle "
                          NL -> "Los de volgende exponentiële vergelijking op "
                          FI -> "Ratkaise eksponenttiyhtälö "
  , problemStatement  = "Solve the following exponential equation: "
  , context           = showId $ exerciseId expEqExercise
  , difficulty        = "medium"
  }

findFactorsExerciseInfo :: MBExerciseInfo
findFactorsExerciseInfo = MBExerciseInfo
  { title             = "Finding factors"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_02_Algebraic_Manipulation"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Find the factors "
                          ES -> "Encontrar los factores "
                          DE -> "Finden Sie die Faktoren "
                          FR -> "Trouver les facteurs "
                          NL -> "Ontbind in factoren "
                          FI -> "Ratkaise kertoimet "
  , problemStatement  = "Find the factors: "
  , context           = showId $ exerciseId findFactorsExercise
  , difficulty        = "easy"
  }

fractionExerciseInfo :: MBExerciseInfo
fractionExerciseInfo = MBExerciseInfo
  { title             = "Simplifying fractions"
  , for               = "mbase://mb_concepts/mb_numbers_and_computation/_01_02_02_Fractions"
  , langSupported     = [EN]
  , cmp               = \l -> case l of 
                          EN -> "Simplify the fraction "
  , problemStatement  = "Simplify the following fraction: "
  , context           = showId $ exerciseId fractionExercise
  , difficulty        = ""
  }

gaussianElimExerciseInfo :: MBExerciseInfo
gaussianElimExerciseInfo = MBExerciseInfo
  { title             = "Gaussian elimination"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_02_02_Matrix_Algebra"
  , langSupported     = [EN]
  , cmp               = \l -> case l of 
                          EN -> "Perform Gaussian elimination "
  , problemStatement  = "Perform Gaussian elimination: "
  , context           = showId $ exerciseId gaussianElimExercise
  , difficulty        = ""
  }

gramSchmidtExerciseInfo :: MBExerciseInfo
gramSchmidtExerciseInfo = MBExerciseInfo
  { title             = "Gram Schmidt"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_02_04_Vector_Spaces"
  , langSupported     = [EN]
  , cmp               = \l -> case l of 
                          EN -> "Solve using Gram Schmidt "
  , problemStatement  = "Solve using Gram Schmidt: "
  , context           = showId $ exerciseId gramSchmidtExercise
  , difficulty        = ""
  }

higherDegreeExerciseInfo :: MBExerciseInfo
higherDegreeExerciseInfo = MBExerciseInfo
  { title             = "Solving higher degree polynomial equations"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_04_03_Polynomial_Equations"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve the higher degree polynomial equation "
                          ES -> "Resolver la ecuación de orden superior "
                          DE -> "Lösen Sie die Gleichung "
                          FR -> "Résoudre l'équation polynomiale de degré élevé "
                          NL -> "Los de volgende hogere orde polynomiale vergelijking op "
                          FI -> "Ratkaise korkeamman asteen polynomiyhätlö "
  , problemStatement  = "Solve the following higher degree polynomial equation: "
  , context           = showId $ exerciseId higherDegreeExercise
  , difficulty        = "easy"
  }

ineqHigherDegreeExerciseInfo :: MBExerciseInfo
ineqHigherDegreeExerciseInfo = MBExerciseInfo
  { title             = "Solving inequations of higher degree"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_05_Inequalities"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve the inequation "
                          ES -> "Resolver la inecuación "
                          DE -> "Lösen Sie die Ungleichung "
                          FR -> "Résoudre l'inéquation "
                          NL -> "Los de volgende ongelijkheid op "
                          FI -> "Ratkaise epäyhtälö "
  , problemStatement  = "Solve the following inequation: "
  , context           = showId $ exerciseId ineqHigherDegreeExercise
  , difficulty        = "medium"
  }

ineqLinearExerciseInfo :: MBExerciseInfo
ineqLinearExerciseInfo = MBExerciseInfo
  { title             = "Solving linear inequations"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_05_Inequalities"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve the linear inequation "
                          ES -> "Resolver la inecuación linea "
                          DE -> "Lösen Sie die lineare Ungleichung "
                          FR -> "Résoudre l'inéquation linéaire "
                          NL -> "Los de volgende lineaire ongelijkheid op "
                          FI -> "Ratkaise lineaarinen epäyhtälö "
  , problemStatement  = "Solve the following linear inequation: "
  , context           = showId $ exerciseId ineqLinearExercise
  , difficulty        = "medium"
  }

ineqQuadraticExerciseInfo :: MBExerciseInfo
ineqQuadraticExerciseInfo = MBExerciseInfo
  { title             = "Solving quadratic inequations"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_05_Inequalities"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve the inequation "
                          ES -> "Resolver la inecuación "
                          DE -> "Lösen Sie die Ungleichung "
                          FR -> "Résoudre l'inéquation "
                          NL -> "Los de volgende ongelijkheid op "
                          FI -> "Ratkaise epäyhtälö "
  , problemStatement  = "Solve the following inequation: "
  , context           = showId $ exerciseId ineqQuadraticExercise
  , difficulty        = "medium"
  }

linearExerciseInfo :: MBExerciseInfo
linearExerciseInfo = MBExerciseInfo
  { title             = "Solving linear equations"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_04_01_Linear_Equations"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve the linear equation "
                          ES -> "Resolver la ecuación lineal "
                          DE -> "Lösen Sie die lineare Gleichung "
                          FR -> "Résoudre l'équation linéaire "
                          NL -> "Los de volgende lineaire vergelijking op "
                          FI -> "Ratkaise lineaarinen yhtälö "
  , problemStatement  = "Solve the following equation: "
  , context           = showId $ exerciseId linearExercise
  , difficulty        = "easy"
  }

linearMixedExerciseInfo :: MBExerciseInfo
linearMixedExerciseInfo = MBExerciseInfo
  { title             = "Solving linear mixed equations"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_04_01_Linear_Equations"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve the linear mixed equation "
                          ES -> "Resolver la ecuación lineal compuesta "
                          DE -> "Lösen Sie die lineare Gleichung "
                          FR -> "Résoudre l'équation linéaire mixte "
                          NL -> "Los de volgende gemengde lineaire vergelijking op "
                          FI -> "Ratkaise lineaarinen yhtälö "
  , problemStatement  = "Solve the linear mixed equation: "
  , context           = showId $ exerciseId linearMixedExercise
  , difficulty        = "easy"
  }

linearSystemExerciseInfo :: MBExerciseInfo
linearSystemExerciseInfo = MBExerciseInfo
  { title             = "Solving systems of linear equations"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_04_07_Systems_of_Equations"
  , langSupported     = [EN]
  , cmp               = \l -> case l of 
                          EN -> "Solve the system of linear equations "
  , problemStatement  = "Solve the following system of linear equations: "
  , context           = showId $ exerciseId linearSystemExercise
  , difficulty        = ""
  }

logEqExerciseInfo :: MBExerciseInfo
logEqExerciseInfo = MBExerciseInfo
  { title             = "Solving logarithmic equations"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_04_06_Logarithmic_Equations"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve the logarithmic equation "
                          ES -> "Resolver la ecuación logarítmica "
                          DE -> "Lösen Sie die Gleichung mit Logarithmen "
                          FR -> "Résoudre l'équation logarithmique "
                          NL -> "Los de volgende logaritmische vergelijking op "
                          FI -> "Ratkaise logaritmiyhtälö "
  , problemStatement  = "Solve the following logarithmic equation: "
  , context           = showId $ exerciseId logEqExercise
  , difficulty        = "medium"
  }

nonNegBrokenExpExerciseInfo :: MBExerciseInfo
nonNegBrokenExpExerciseInfo = MBExerciseInfo
  { title             = "Writing with non-negative exponents"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_02_Algebraic_Manipulation"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Write with a non-negative exponent "
                          ES -> "Expresar con exponente no negativo "
                          DE -> "Schreiben Sie mit nicht-negativen Exponenten "
                          FR -> "Écrire avec une puissance non-négative <"
                          NL -> "Schrijf met niet-negatieve exponenten "
                          FI -> "Ilmaise käyttäen ei-negatiivista eksponenttia "
  , problemStatement  = "Write the following with a non-negative exponent: "
  , context           = showId $ exerciseId nonNegBrokenExpExercise
  , difficulty        = "medium"
  }

powerEqExerciseInfo :: MBExerciseInfo
powerEqExerciseInfo = MBExerciseInfo
  { title             = "Solving power equations"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_04_03_Polynomial_Equations"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve the power equation "
                          ES -> "Resolver la ecuación con potencias "
                          DE -> "Lösen Sie die Gleichung mit x im Exponenten "
                          FR -> "Résoudre l'équation avec puissances "
                          NL -> "Los de volgende machtsvergelijking op "
                          FI -> "Ratkaise potenssiyhtälö "
  , problemStatement  = "Solve the following power equation: "
  , context           = showId $ exerciseId powerEqExercise
  , difficulty        = "medium"
  }

powerOfExerciseInfo :: MBExerciseInfo
powerOfExerciseInfo = MBExerciseInfo
  { title             = "Writing as a power"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_02_Algebraic_Manipulation"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Write as a power "
                          ES -> "Expresar como potencia "
                          DE -> "Schreiben Sie als Potenz "
                          FR -> "Écrire sous la forme d'une puissance "
                          NL -> "Schrijf als een macht "
                          FI -> "Ilmaise potenssimuodossa "
  , problemStatement  = "Write the following as a power: "
  , context           = showId $ exerciseId powerOfExercise
  , difficulty        = "medium"
  }

quadraticExerciseInfo :: MBExerciseInfo
quadraticExerciseInfo = MBExerciseInfo
  { title             = "Solving quadratic equations"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_04_02_Quadratic_Equations"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve the quadratic equation "
                          ES -> "Resolver la ecuación cuadrática "
                          DE -> "Lösen Sie die quadratische Gleichung "
                          FR -> "Résoudre l'équation quadratique "
                          NL -> "Los de volgende kwadratische vergelijking op "
                          FI -> "Ratkaise toisen asteen yhtälö "
  , problemStatement  = "Solve the following quadratic equation: "
  , context           = showId $ exerciseId quadraticExercise
  , difficulty        = "easy"
  }
  
quadraticNoABCExerciseInfo :: MBExerciseInfo
quadraticNoABCExerciseInfo = MBExerciseInfo
  { title             = "Solving quadratic equations (no abc)"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_04_02_Quadratic_Equations"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve, without using the quadratic formula, the quadratic equation "
                          ES -> "Resolver la ecuación cuadrática sin utilizar la fórmula cuadrática "
                          DE -> "Lösen Sie die quadratische Gleichung ohne Benutzung der p-q-Formel "
                          FR -> "Résoudre l'équation quadratique, sans utiliser la formule de résolution "
                          NL -> "Los de volgende kwadratische vergelijking op, zonder gebruik te maken van de abc-formule "
                          FI -> "Ratkaise toisen asteen yhtälö käyttämättä ratkaisukaavaa "
  , problemStatement  = "Solve, without using the quadratic formula, the following quadratic equation: "
  , context           = showId $ exerciseId quadraticNoABCExercise
  , difficulty        = "easy"
  }
  
quadraticWithApproximationExerciseInfo :: MBExerciseInfo
quadraticWithApproximationExerciseInfo = MBExerciseInfo
  { title             = "Solving quadratic equations (with approximation)"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_04_02_Quadratic_Equations"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve, with approximation allowed, the quadratic equation "
                          ES -> "Resolver la ecuación cuadrática, con aproximación permitida "
                          DE -> "Lösen Sie die quadratische Gleichung"
                          FR -> "Résoudre l'équation quadratique, approximation permise "
                          NL -> "Los de volgende kwadratische vergelijking op, een benadering is toegestaan "
                          FI -> "Ratkaise likimääräisesti toisen asteen yhtälö "
  , problemStatement  = "Solve, with approximation allowed, the following quadratic equation: "
  , context           = showId $ exerciseId quadraticWithApproximation
  , difficulty        = "easy"
  }

rationalEquationExerciseInfo :: MBExerciseInfo
rationalEquationExerciseInfo = MBExerciseInfo
  { title             = "Solving rational equations"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_04_04_Rational_Equations"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Solve the rational equation "
                          ES -> "Resolver la ecuación racional "
                          DE -> "Lösen Sie die Bruchgleichung "
                          FR -> "Résoudre l'équation rationnelle "
                          NL -> "Los de volgende gebroken vergelijking op "
                          FI -> "Ratkaise rationaaliyhtälö "
  , problemStatement  = "Solve the following rational equation: "
  , context           = showId $ exerciseId rationalEquationExercise
  , difficulty        = "medium"
  }

simplifyPowerExerciseInfo :: MBExerciseInfo
simplifyPowerExerciseInfo = MBExerciseInfo
  { title             = "Simplifying powers"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_02_Algebraic_Manipulation"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Simplify the power "
                          ES -> "Simplificar las potencias "
                          DE -> "Vereinfachen Sie die Potenz "
                          FR -> "Simplifier la puissance "
                          NL -> "Vereenvoudig de macht "
                          FI -> "Sievennä potenssilauseke "
  , problemStatement  = "Simplify the following power: "
  , context           = showId $ exerciseId simplifyPowerExercise
  , difficulty        = "medium"
  }

simplifyRationalExerciseInfo :: MBExerciseInfo
simplifyRationalExerciseInfo = MBExerciseInfo
  { title             = "Simplifying rationals"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_01_02_Algebraic_Manipulation"
  , langSupported     = [EN,ES,DE,FR,NL,FI]
  , cmp               = \l -> case l of 
                          EN -> "Simplify the rational "
                          ES -> "Simplificar el racional "
                          DE -> "Vereinfachen Sie den Bruch "
                          FR -> "Simplifiez le rationnel "
                          NL -> "Vereenvoudig de breuk "
                          FI -> "Sievennä murtolauseke "
  , problemStatement  = "Simplify the following rational: "
  , context           = showId $ exerciseId simplifyRationalExercise
  , difficulty        = "medium"
  }

systemWithMatrixExerciseInfo :: MBExerciseInfo
systemWithMatrixExerciseInfo = MBExerciseInfo
  { title             = "Solving systems of linear equations using matrices"
  , for               = "mbase://mb_concepts/mb_algebra_and_number_theory/_03_02_02_Matrix_Algebra"
  , langSupported     = [EN]
  , cmp               = \l -> case l of 
                          EN -> "Solve the following system of linear equations using a matrix: "
  , problemStatement  = "Solve the following system of linear equations using a matrix:  "
  , context           = showId $ exerciseId systemWithMatrixExercise
  , difficulty        = ""
  }

--------------------------------------------------------------------------------
{- XML elements for Omdoc.

Use inefficient string concatenation. 
Probably use Text.XML.
-}
--------------------------------------------------------------------------------

activemathdtd  :: String
activemathdtd  =  "<!DOCTYPE omdoc SYSTEM \"../dtd/activemath.dtd\" []>\n"

cmpelts :: [Lang] -> [String] -> [Element]
cmpelts = zipWith (\l s -> cmpelt (show l) s)         

cmpelt :: String  -> String -> Element
cmpelt lang cmp =          
  Element { name        =  "CMP"
          , attributes  =  ["xml:lang" := lang]
          , content     =  [Left cmp]
          }

creatorelt :: String -> String -> Element
creatorelt role nm =
  Element { name         =  "Creator"
          , attributes   =  ["role" := role ]
          , content      =  [Left nm] 
          }           

dateelt :: String -> String -> Element
dateelt action date =
  Element { name         =  "Date"
          , attributes   =  ["action" := action ]
          , content      =  [Left date] 
          }           

difficultyelt :: String  -> Element
difficultyelt difficulty = 
  Element { name        =  "difficulty"
          , attributes  =  ["value" := difficulty]
          , content     =  []
          }

extradataelt :: [Element] -> Element
extradataelt ls = 
  Element { name        =  "extradata"
          , attributes  =  []
          , content     =  map Right ls
          }

exerciseelt :: String -> Maybe String -> [Element] -> Element
exerciseelt idattr maybefor ls = 
  case maybefor of 
    Nothing  -> Element { name        =  "exercise"
                        , attributes  =  ["id" := idattr]
                        , content     =  map Right ls
                        }
    Just for -> Element { name        =  "exercise"
                        , attributes  =  ["id" := idattr, "for" := for]
                        , content     =  map Right ls
                        }                        

formatelt :: String -> Element
formatelt format = 
  Element { name        =  "Format"
          , attributes  =  []
          , content     =  [Left format]
          }

interaction_generatorelt :: String -> String -> [Element] -> Element
interaction_generatorelt interaction_generatorname interaction_generatortype ls =          
  Element { name        =  "interaction_generator"
          , attributes  =  ["name" := interaction_generatorname
                           ,"type" := interaction_generatortype]
          , content     =  map Right ls
          }

metadataelt :: String -> [Element] -> Element
metadataelt identifier ls = 
  Element { name        =  "metadata"
          , attributes  =  if null identifier
                           then []
                           else ["id" := identifier]
          , content     =  map Right ls
          }

omdocelt :: String -> String -> [Element] -> Element
omdocelt identifier namespace ls =
  Element { name         =  "omdoc"
          , attributes   =  if null namespace 
                            then ["id" := identifier]
                            else if null identifier 
                                 then ["xmlns:ami" := namespace]
                                 else ["id" := identifier
                                      ,"xmlns:ami" := namespace]
          , content      =  map Right ls
          }           

omgroupelt :: String -> String -> [Element] -> Element
omgroupelt identifier namespace ls =
  Element { name         =  "omgroup"
          , attributes   = if null namespace && null identifier
                           then []
                           else if null namespace
                                then ["id" := identifier]
                                else if null identifier 
                                     then ["xmlns" := namespace]
                                     else ["id" := identifier
                                          ,"xmlns" := namespace]
          , content      =  map Right ls
          }           

omtextelt  :: String -> [Element] -> Element
omtextelt identifier ls =
  Element { name         =  "omtext"
          , attributes   =  ["id" := identifier]
          , content      =  map Right ls
          }           

parameterelt :: String -> Content -> Element
parameterelt parametername ls =          
  Element { name        =  "parameter"
          , attributes  =  ["name" := parametername]
          , content     =  ls
          }

refelt :: String -> Element
refelt ref =
  Element { name         =  "ref"
          , attributes   =  ["ref" := ref]
          , content      =  []
          }           

relationelt :: String -> Element
relationelt for =
  Element { name         =  "relation"
          , attributes   =  ["type" := "for"]
          , content      =  [Right (refelt for)]
          }           
          
sourceelt :: String -> Element
sourceelt source =
  Element { name         =  "Source"
          , attributes   =  []
          , content      =  if null source
                            then []
                            else [Left source]
          }           

sourcefileelt :: String -> String -> String -> Element
sourcefileelt namespace filename lastmodified =
  Element { name         =  "sourcefile"
          , attributes   =  ["xmlns" := namespace
                            ,"path" := filename
                            ,"lastModified" := lastmodified]
          , content      =  []
          }           

theoryelt  :: String -> [Element] -> Element
theoryelt identifier ls =
  Element { name         =  "theory"
          , attributes   =  ["id" := identifier]
          , content      =  map Right ls
          }           

titleelt :: String -> Element
titleelt titletext = 
  Element { name        =  "Title"
          , attributes  =  []
          , content     =  [Left titletext]
          }

versionelt :: String -> String -> Element
versionelt version revision = 
  Element { name        =  "Version"
          , attributes  =  ["number" := revision]
          , content     =  [Left version]
          }

xmldecl  :: String
xmldecl  =  "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" 

xrefelt :: String -> String -> Element
xrefelt xref ami =
  Element { name         =  "ref"
          , attributes   =  ["xref" := xref
                            --,"ami:item-element-name" := ami -- apparently not allowed
                            ]
          , content      =  []
          }           

