<reply result="ok" version="0.7.6 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.remove-div">
      <argument description="factor">
        6
      </argument>
      <expr>
        5*x-13 == -24*x+3*(3*x-6)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        5*x-13 == -24*x+9*x-18
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.collect">
      <expr>
        5*x-13 == -15*x-18
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-left-plus">
      <argument description="term">
        15*x
      </argument>
      <expr>
        20*x-13 == -18
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-right-plus">
      <argument description="term">
        13
      </argument>
      <expr>
        20*x == -5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        20
      </argument>
      <expr>
        x == -1/4
      </expr>
    </elem>
  </list>
</reply>

