<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.remove-div">
      <argument description="factor">
        4
      </argument>
      <expr>
        4*(1/4*x-3/4) == 4*(2*x+1/2)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        x-3 == 8*x+2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-right-minus">
      <argument description="term">
        x
      </argument>
      <expr>
        -3 == 7*x+2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-minus">
      <argument description="term">
        2
      </argument>
      <expr>
        -5 == 7*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        7
      </argument>
      <expr>
        -5/7 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == -5/7
      </expr>
    </elem>
  </list>
</reply>

