<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.con-right-minus">
      <argument description="term">
        15
      </argument>
      <expr>
        -9*x == -9
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        -9
      </argument>
      <expr>
        x == 1
      </expr>
    </elem>
  </list>
</reply>

