<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.collect">
      <expr>
        1/2*x-4 == 2*x+5/2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.remove-div">
      <argument description="factor">
        2
      </argument>
      <expr>
        2*(1/2*x-4) == 2*(2*x+5/2)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        x-8 == 4*x+5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-right-minus">
      <argument description="term">
        x
      </argument>
      <expr>
        -8 == 3*x+5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-minus">
      <argument description="term">
        5
      </argument>
      <expr>
        -13 == 3*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        3
      </argument>
      <expr>
        -13/3 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == -13/3
      </expr>
    </elem>
  </list>
</reply>

