<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.var-left-plus">
      <argument description="term">
        5*x
      </argument>
      <expr>
        9*x-7 == -24
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-right-plus">
      <argument description="term">
        7
      </argument>
      <expr>
        9*x == -17
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        9
      </argument>
      <expr>
        x == -17/9
      </expr>
    </elem>
  </list>
</reply>

