<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        12*x == 7*x-14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-left-minus">
      <argument description="term">
        7*x
      </argument>
      <expr>
        5*x == -14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        5
      </argument>
      <expr>
        x == -14/5
      </expr>
    </elem>
  </list>
</reply>

