<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        4*x-16 == 10*x+5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-right-minus">
      <argument description="term">
        4*x
      </argument>
      <expr>
        -16 == 6*x+5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-minus">
      <argument description="term">
        5
      </argument>
      <expr>
        -21 == 6*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        6
      </argument>
      <expr>
        -7/2 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == -7/2
      </expr>
    </elem>
  </list>
</reply>

