<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.con-right-minus">
      <argument description="term">
        18
      </argument>
      <expr>
        4*x == -18
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        4
      </argument>
      <expr>
        x == -9/2
      </expr>
    </elem>
  </list>
</reply>

