<reply result="ok" version="0.7.6 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        3/5*x+2 == 7*x-14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.remove-div">
      <argument description="factor">
        5
      </argument>
      <expr>
        3*x+10 == 35*x-70
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-right-minus">
      <argument description="term">
        3*x
      </argument>
      <expr>
        10 == 32*x-70
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-plus">
      <argument description="term">
        70
      </argument>
      <expr>
        80 == 32*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        32
      </argument>
      <expr>
        5/2 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == 5/2
      </expr>
    </elem>
  </list>
</reply>

