<reply result="ok" version="0.7.6 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.remove-div">
      <argument description="factor">
        4
      </argument>
      <expr>
        3*x-4*(x-1) == 12+10*(x-1)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        3*x-4*x+4 == 12+10*x-10
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.collect">
      <expr>
        -x+4 == 2+10*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-right-plus">
      <argument description="term">
        x
      </argument>
      <expr>
        4 == 2+11*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-minus">
      <argument description="term">
        2
      </argument>
      <expr>
        2 == 11*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        11
      </argument>
      <expr>
        2/11 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == 2/11
      </expr>
    </elem>
  </list>
</reply>

