<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.remove-div">
      <argument description="factor">
        15
      </argument>
      <expr>
        15*(2/3*x-2) == 15*(1/5*x-3/5)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        10*x-30 == 3*x-9
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-left-minus">
      <argument description="term">
        3*x
      </argument>
      <expr>
        7*x-30 == -9
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-right-plus">
      <argument description="term">
        30
      </argument>
      <expr>
        7*x == 21
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        7
      </argument>
      <expr>
        x == 3
      </expr>
    </elem>
  </list>
</reply>

