<reply result="ok" version="0.7.6 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.remove-div">
      <argument description="factor">
        4
      </argument>
      <expr>
        x-3 == 2*x-16
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-right-minus">
      <argument description="term">
        x
      </argument>
      <expr>
        -3 == x-16
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-plus">
      <argument description="term">
        16
      </argument>
      <expr>
        13 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == 13
      </expr>
    </elem>
  </list>
</reply>

