<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.con-right-plus">
      <argument description="term">
        12
      </argument>
      <expr>
        6*x == 14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        6
      </argument>
      <expr>
        x == 7/3
      </expr>
    </elem>
  </list>
</reply>

