<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.var-left-minus">
      <argument description="term">
        2*x
      </argument>
      <expr>
        4*x-2 == 14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-right-plus">
      <argument description="term">
        2
      </argument>
      <expr>
        4*x == 16
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        4
      </argument>
      <expr>
        x == 4
      </expr>
    </elem>
  </list>
</reply>

