<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.var-left-minus">
      <argument description="term">
        2*x
      </argument>
      <expr>
        3*x+7 == -10
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-right-minus">
      <argument description="term">
        7
      </argument>
      <expr>
        3*x == -17
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        3
      </argument>
      <expr>
        x == -17/3
      </expr>
    </elem>
  </list>
</reply>

