<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        16*x-6 == -3*x+6*x-15
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.collect">
      <expr>
        16*x-6 == 3*x-15
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-left-minus">
      <argument description="term">
        3*x
      </argument>
      <expr>
        13*x-6 == -15
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-right-plus">
      <argument description="term">
        6
      </argument>
      <expr>
        13*x == -9
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        13
      </argument>
      <expr>
        x == -9/13
      </expr>
    </elem>
  </list>
</reply>

