<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.var-right-minus">
      <argument description="term">
        4*x
      </argument>
      <expr>
        -18 == 14+7*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-minus">
      <argument description="term">
        14
      </argument>
      <expr>
        -32 == 7*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        7
      </argument>
      <expr>
        -32/7 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == -32/7
      </expr>
    </elem>
  </list>
</reply>

