<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.remove-div">
      <argument description="factor">
        12
      </argument>
      <expr>
        12*(-1/3*x+3/4) == 12*(1/4*x+1/6)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        -4*x+9 == 3*x+2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-right-plus">
      <argument description="term">
        4*x
      </argument>
      <expr>
        9 == 7*x+2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-minus">
      <argument description="term">
        2
      </argument>
      <expr>
        7 == 7*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        7
      </argument>
      <expr>
        1 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == 1
      </expr>
    </elem>
  </list>
</reply>

