<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.collect">
      <expr>
        3*x+2 == 12+5*(x-1)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        3*x+2 == 12+5*x-5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.collect">
      <expr>
        3*x+2 == 7+5*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-right-minus">
      <argument description="term">
        3*x
      </argument>
      <expr>
        2 == 7+2*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-minus">
      <argument description="term">
        7
      </argument>
      <expr>
        -5 == 2*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        2
      </argument>
      <expr>
        -5/2 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == -5/2
      </expr>
    </elem>
  </list>
</reply>

