<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.var-right-plus">
      <argument description="term">
        5*x
      </argument>
      <expr>
        6 == 2+2*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-minus">
      <argument description="term">
        2
      </argument>
      <expr>
        4 == 2*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        2
      </argument>
      <expr>
        2 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == 2
      </expr>
    </elem>
  </list>
</reply>

