<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.con-right-minus">
      <argument description="term">
        19
      </argument>
      <expr>
        -3*x == -24
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        -3
      </argument>
      <expr>
        x == 8
      </expr>
    </elem>
  </list>
</reply>

