<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.con-right-plus">
      <argument description="term">
        13
      </argument>
      <expr>
        -4*x == 2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        -4
      </argument>
      <expr>
        x == -1/2
      </expr>
    </elem>
  </list>
</reply>

