<reply result="ok" version="0.7.6 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.remove-div">
      <argument description="factor">
        12
      </argument>
      <expr>
        12+4*(-4*x-2) == 36*x+3*(-5*x+1)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        12-16*x-8 == 36*x-15*x+3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.collect">
      <expr>
        4-16*x == 21*x+3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-right-plus">
      <argument description="term">
        16*x
      </argument>
      <expr>
        4 == 37*x+3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-minus">
      <argument description="term">
        3
      </argument>
      <expr>
        1 == 37*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        37
      </argument>
      <expr>
        1/37 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == 1/37
      </expr>
    </elem>
  </list>
</reply>

