<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.collect">
      <expr>
        -x-5 == 10+5*(x-1)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        -x-5 == 10+5*x-5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.collect">
      <expr>
        -x-5 == 5+5*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-right-plus">
      <argument description="term">
        x
      </argument>
      <expr>
        -5 == 5+6*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-minus">
      <argument description="term">
        5
      </argument>
      <expr>
        -10 == 6*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        6
      </argument>
      <expr>
        -5/3 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == -5/3
      </expr>
    </elem>
  </list>
</reply>

