<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.con-right-plus">
      <argument description="term">
        3
      </argument>
      <expr>
        -2*x == -1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        -2
      </argument>
      <expr>
        x == 1/2
      </expr>
    </elem>
  </list>
</reply>

