<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.var-right-plus">
      <argument description="term">
        5*x
      </argument>
      <expr>
        -1 == 8*x-20
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-plus">
      <argument description="term">
        20
      </argument>
      <expr>
        19 == 8*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        8
      </argument>
      <expr>
        19/8 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == 19/8
      </expr>
    </elem>
  </list>
</reply>

