<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        18-8*x-4 == 7*x-16*x+8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.collect">
      <expr>
        14-8*x == -9*x+8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-left-plus">
      <argument description="term">
        9*x
      </argument>
      <expr>
        14+x == 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-right-minus">
      <argument description="term">
        14
      </argument>
      <expr>
        x == -6
      </expr>
    </elem>
  </list>
</reply>

