<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.con-right-plus">
      <argument description="term">
        12
      </argument>
      <expr>
        5*x == 45
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        5
      </argument>
      <expr>
        x == 9
      </expr>
    </elem>
  </list>
</reply>

