<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.remove-div">
      <argument description="factor">
        18
      </argument>
      <expr>
        9*(7-2/3*x) == 18*(2+1/9*x)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute">
      <expr>
        63-6*x == 36+2*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-right-plus">
      <argument description="term">
        6*x
      </argument>
      <expr>
        63 == 36+8*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-left-minus">
      <argument description="term">
        36
      </argument>
      <expr>
        27 == 8*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        8
      </argument>
      <expr>
        27/8 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == 27/8
      </expr>
    </elem>
  </list>
</reply>

