<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.var-left-plus">
      <argument description="term">
        x
      </argument>
      <expr>
        3*x-8 == 18
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-right-plus">
      <argument description="term">
        8
      </argument>
      <expr>
        3*x == 26
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        3
      </argument>
      <expr>
        x == 26/3
      </expr>
    </elem>
  </list>
</reply>

