<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.con-right-minus">
      <argument description="term">
        3
      </argument>
      <expr>
        5*x == 15
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        5
      </argument>
      <expr>
        x == 3
      </expr>
    </elem>
  </list>
</reply>

