<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.def-power-nat">
      <expr>
        (x-1)*(x-1)*(x-1)*x
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (x^2-x-x+1)*(x-1)*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (x^3-x^2-x^2+x-x^2+x+x-1)*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^4-3*x^3+3*x^2-x
      </expr>
    </elem>
  </list>
</reply>

