<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.no-div-con">
      <expr>
        1/2*(x+1)+(x+2)/3
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        1/2*x+1/2+(x+2)/3
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.no-div-con">
      <expr>
        1/2*x+1/2+1/3*(x+2)
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        1/2*x+1/2+1/3*x+2/3
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        5/6*x+7/6
      </expr>
    </elem>
  </list>
</reply>

