<reply result="ok" version="0.7.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.fraction-product">
      <expr>
        (x+1)*(x+2)/6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (x^2+3*x+2)/6
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.no-div-con">
      <expr>
        1/6*(x^2+3*x+2)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        1/6*x^2+1/2*x+1/3
      </expr>
    </elem>
  </list>
</reply>

