<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.distr-square">
      <expr>
        (x^2-2*x+1)*(x+1)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^3-x^2-x+1
      </expr>
    </elem>
  </list>
</reply>

