<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.factor-varpower">
      <expr>
        x*(14*x-10)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.polynomial.simpler-linfactor">
      <expr>
        x*2*(7*x-5)
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

