<reply result="ok" version="0.7.1 (0)">
  <list>
    <elem ruleid="logic.propositional.buggy.demorgan1">
      []
      <state>
        <expr>
          ~p || ~q
        </expr>
      </state>
    </elem>
    <elem ruleid="logic.propositional.buggy.demorgan1">
      []
      <state>
        <expr>
          p || ~~q
        </expr>
      </state>
    </elem>
    <elem ruleid="logic.propositional.buggy.demorgan1">
      []
      <state>
        <expr>
          p || ~q
        </expr>
      </state>
    </elem>
    <elem ruleid="logic.propositional.buggy.demorgan2">
      []
      <state>
        <expr>
          ~(~p || ~~q)
        </expr>
      </state>
    </elem>
    <elem ruleid="logic.propositional.buggy.demorgan3">
      []
      <state>
        <expr>
          ~p /\ ~~q
        </expr>
      </state>
    </elem>
    <elem ruleid="logic.propositional.buggy.parenth1">
      []
      <state>
        <expr>
          ~p /\ ~q
        </expr>
      </state>
    </elem>
    <elem ruleid="logic.propositional.command">
      [0]
      <state>
        <expr>
          ~(~q /\ p)
        </expr>
        <context>
          <item name="location" value="[0]"/>
        </context>
      </state>
    </elem>
    <elem ruleid="logic.propositional.demorganand">
      []
      <state>
        <prefix>
          [5,1,1,0,1,1,0,0,1,1,0]
        </prefix>
        <expr>
          ~p || ~~q
        </expr>
      </state>
    </elem>
  </list>
</reply>

