<reply result="ok" version="0.7.4 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div" location="[]">
      <argument description="factor">
        2
      </argument>
      <state>
        <prefix>
          [4,1,0]
        </prefix>
        <expr>
          10*(x-1) == x
        </expr>
      </state>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times" location="[]">
      <state>
        <prefix>
          [4,1,1,0]
        </prefix>
        <expr>
          5*x-5 == x/2
        </expr>
      </state>
    </elem>
  </list>
</reply>

