<reply result="ok" version="0.7.6 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.smart-div" location="[]">
      <argument description="factor">
        2
      </argument>
      <state>
        <prefix>
          [3,1,0,1,0,1]
        </prefix>
        <expr>
          x-5 == 2
        </expr>
      </state>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute" location="[]">
      <state>
        <prefix>
          [4,0,1,1,0]
        </prefix>
        <expr>
          2*x-10 == 4
        </expr>
      </state>
    </elem>
  </list>
</reply>

