<reply result="ok" version="1.0.5 (0)">
  <state>
    <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
      <OMA>
        <OMS cd="relation1" name="eq"/>
        <OMA>
          <OMS cd="arith1" name="minus"/>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMV name="x"/>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMI>
            1
          </OMI>
        </OMA>
        <OMI>
          3
        </OMI>
      </OMA>
    </OMOBJ>
  </state>
</reply>

