<reply result="ok" version="0.7.6 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.remove-div">
      <argument description="factor">
        2
      </argument>
      <expr>
        10*x-10 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.var-left-minus">
      <argument description="term">
        x
      </argument>
      <expr>
        9*x-10 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.con-right-plus">
      <argument description="term">
        10
      </argument>
      <expr>
        9*x == 10
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.scale-to-one">
      <argument description="factor">
        9
      </argument>
      <expr>
        x == 10/9
      </expr>
    </elem>
  </list>
</reply>

