<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.remove-div" location="[]">
      <argument description="factor">
        2
      </argument>
      <state>
        <prefix>
          [4,0,1,1,1,0]
        </prefix>
        <expr>
          10*(x-1) == x
        </expr>
      </state>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute" location="[]">
      <state>
        <prefix>
          [4,0,1,1,0]
        </prefix>
        <expr>
          5*x-5 == x/2
        </expr>
      </state>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.div-to-fraction" location="[1]">
      <state>
        <prefix>
          [6,0,1,1,1,1,0,1,0,1,0,0,0]
        </prefix>
        <expr>
          5*(x-1) == 1/2*x
        </expr>
        <context>
          <item name="location" value="[1]"/>
        </context>
      </state>
    </elem>
  </list>
</reply>

