<reply result="ok" version="0.7.6 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.remove-div" location="[]">
      <argument description="factor">
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMI>
            2
          </OMI>
        </OMOBJ>
      </argument>
      <state>
        <prefix>
          [4,0,1,1,1]
        </prefix>
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  10
                </OMI>
                <OMV name="x"/>
              </OMA>
              <OMI>
                10
              </OMI>
            </OMA>
            <OMV name="x"/>
          </OMA>
        </OMOBJ>
      </state>
    </elem>
    <elem ruleid="algebra.equations.linear.balance.distribute" location="[]">
      <state>
        <prefix>
          [4,0,1,1,0]
        </prefix>
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  5
                </OMI>
                <OMV name="x"/>
              </OMA>
              <OMI>
                5
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMV name="x"/>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
        </OMOBJ>
      </state>
    </elem>
  </list>
</reply>

