<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="remove division">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMI>
              12
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                4
              </OMI>
              <OMA>
                <OMS cd="arith1" name="plus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    4
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  2
                </OMI>
              </OMA>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                36
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                3
              </OMI>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    5
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  1
                </OMI>
              </OMA>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="distribution">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMI>
                12
              </OMI>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  16
                </OMI>
                <OMV name="x"/>
              </OMA>
            </OMA>
            <OMI>
              8
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                36
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                3
              </OMI>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    5
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  1
                </OMI>
              </OMA>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="distribution">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMI>
                12
              </OMI>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  16
                </OMI>
                <OMV name="x"/>
              </OMA>
            </OMA>
            <OMI>
              8
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  36
                </OMI>
                <OMV name="x"/>
              </OMA>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  15
                </OMI>
                <OMV name="x"/>
              </OMA>
            </OMA>
            <OMI>
              3
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="merge similar terms">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMI>
              4
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                16
              </OMI>
              <OMV name="x"/>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                21
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              3
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="variable to left">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMI>
              4
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                37
              </OMI>
              <OMV name="x"/>
            </OMA>
          </OMA>
          <OMI>
            3
          </OMI>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="cover-up minus right [one var]">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMI>
              37
            </OMI>
            <OMV name="x"/>
          </OMA>
          <OMI>
            1
          </OMI>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMV name="x"/>
          <OMA>
            <OMS cd="arith1" name="divide"/>
            <OMI>
              1
            </OMI>
            <OMI>
              37
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
  </list>
</reply>

