<reply result="ok" version="0.1">
  <list>
    <elem ruleid="Tidy-up rule">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="calculus1" name="diff"/>
          <OMBIND>
            <OMS cd="fns1" name="lambda"/>
            <OMBVAR>
              <OMV name="x"/>
            </OMBVAR>
            <OMA>
              <OMS cd="transc1" name="ln"/>
              <OMA>
                <OMS cd="arith1" name="plus"/>
                <OMI>
                  -1
                </OMI>
                <OMV name="x"/>
              </OMA>
            </OMA>
          </OMBIND>
        </OMA>
      </OMOBJ>
    </elem>
  </list>
</reply>

