<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <argument description="factor">
        2
      </argument>
      <expr>
        10*(x-1) == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        10*x-10 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        1*x
      </argument>
      <expr>
        9*x-10 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        9*x == 10
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 10/9
      </expr>
    </elem>
  </list>
</reply>

