<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        x^2-2*x-15 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-2*x-15>=0)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+3)*(x-5) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-2*x-15>=0)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -3 or x == 5
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-2*x-15>=0)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        x &lt;= -3 or x &gt;= 5
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

