<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="logarithmic">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="fns1" name="lambda"/>
          <OMBVAR>
            <OMV name="x"/>
          </OMBVAR>
          <OMA>
            <OMS cd="arith1" name="divide"/>
            <OMI>
              1
            </OMI>
            <OMV name="x"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </elem>
  </list>
</reply>

