<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        x^2-x-6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x-6<=0)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+2)*(x-3) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x-6<=0)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -2 or x == 3
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x-6<=0)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        -2 &lt;= x &lt;= 3
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

