<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem>
      remove division
      <expr>
        x+3 == 10*(1/2*x+3/2)
      </expr>
    </elem>
    <elem>
      distribution multiplication
      <expr>
        x+3 == 5*x+15
      </expr>
    </elem>
    <elem>
      variable to left
      <expr>
        -4*x+3 == 15
      </expr>
    </elem>
    <elem>
      rule plus
      <expr>
        -4*x == 12
      </expr>
    </elem>
    <elem>
      rule times
      <expr>
        x == -3
      </expr>
    </elem>
  </list>
</reply>

