<reply result="ok" version="0.1">
  <list>
    <elem ruleid="Sine Rule">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="transc1" name="cos"/>
          <OMA>
            <OMS cd="arith1" name="power"/>
            <OMV name="x"/>
            <OMI>
              2
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
  </list>
</reply>

