<reply result="ok" version="0.1">
  <list>
    <elem ruleid="Tidy-up rule">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="arith1" name="plus"/>
          <OMI>
            3
          </OMI>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMI>
              3
            </OMI>
            <OMI>
              4
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="Tidy-up rule">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="arith1" name="plus"/>
          <OMI>
            3
          </OMI>
          <OMI>
            7
          </OMI>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="Tidy-up rule">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMI>
          10
        </OMI>
      </OMOBJ>
    </elem>
  </list>
</reply>

