<reply result="ok" version="0.5.12">
  <expected ready="false" ruleid="cover-up plus [one var]">
    <state>
      <prefix>
        [0,0,0,3,0,0,3,0]
      </prefix>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMI>
              2
            </OMI>
            <OMV name="x"/>
          </OMA>
          <OMI>
            2
          </OMI>
        </OMA>
      </OMOBJ>
    </state>
  </expected>
</reply>

