<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="variable to left">
      <expr>
        3*x+3 == 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        3*x == 2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 2/3
      </expr>
    </elem>
  </list>
</reply>

