<reply result="ok" version="0.6.1 (3081)">
  <list>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                5
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              3
            </OMI>
          </OMA>
          <OMI>
            18
          </OMI>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                11
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              12
            </OMI>
          </OMA>
          <OMI>
            21
          </OMI>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMI>
              19
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                3
              </OMI>
              <OMV name="x"/>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="unary_minus"/>
            <OMI>
              5
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                12
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                5
              </OMI>
              <OMV name="x"/>
            </OMA>
          </OMA>
          <OMI>
            33
          </OMI>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMI>
              15
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                9
              </OMI>
              <OMV name="x"/>
            </OMA>
          </OMA>
          <OMI>
            6
          </OMI>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                4
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              18
            </OMI>
          </OMA>
          <OMI>
            0
          </OMI>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                11
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              12
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="unary_minus"/>
            <OMI>
              34
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  2
                </OMI>
                <OMV name="x"/>
              </OMA>
            </OMA>
            <OMI>
              3
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="unary_minus"/>
            <OMI>
              4
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                6
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              12
            </OMI>
          </OMA>
          <OMI>
            2
          </OMI>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  4
                </OMI>
                <OMV name="x"/>
              </OMA>
            </OMA>
            <OMI>
              13
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="unary_minus"/>
            <OMI>
              11
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                6
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              2
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                2
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              14
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMI>
              3
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                6
              </OMI>
              <OMV name="x"/>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                3
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              24
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                5
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              7
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                2
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              10
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                2
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              8
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMI>
              18
            </OMI>
            <OMV name="x"/>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                4
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              6
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                7
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              14
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                1
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                5
              </OMI>
              <OMV name="x"/>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                3
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              20
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                4
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              7
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  5
                </OMI>
                <OMV name="x"/>
              </OMA>
            </OMA>
            <OMI>
              24
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                4
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              18
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMI>
              14
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                11
              </OMI>
              <OMV name="x"/>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMI>
            17
          </OMI>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMI>
              4
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                10
              </OMI>
              <OMV name="x"/>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  5
                </OMI>
                <OMV name="x"/>
              </OMA>
            </OMA>
            <OMI>
              6
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMI>
              2
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                3
              </OMI>
              <OMV name="x"/>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMI>
              4
            </OMI>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMV name="x"/>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                11
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              12
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMI>
              4
            </OMI>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMV name="x"/>
              <OMI>
                4
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMI>
              5
            </OMI>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  2
                </OMI>
                <OMV name="x"/>
              </OMA>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMI>
              2
            </OMI>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMI>
                5
              </OMI>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  3
                </OMI>
                <OMV name="x"/>
              </OMA>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMI>
              6
            </OMI>
            <OMV name="x"/>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                4
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMV name="x"/>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMI>
              12
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                5
              </OMI>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMV name="x"/>
                <OMI>
                  1
                </OMI>
              </OMA>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="unary_minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                3
              </OMI>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMV name="x"/>
                <OMI>
                  2
                </OMI>
              </OMA>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                3
              </OMI>
              <OMA>
                <OMS cd="arith1" name="plus"/>
                <OMV name="x"/>
                <OMI>
                  4
                </OMI>
              </OMA>
            </OMA>
            <OMI>
              7
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                3
              </OMI>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    4
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  1
                </OMI>
              </OMA>
            </OMA>
            <OMI>
              3
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                7
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              14
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                4
              </OMI>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    4
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  1
                </OMI>
              </OMA>
            </OMA>
            <OMI>
              2
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  3
                </OMI>
                <OMV name="x"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                3
              </OMI>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    2
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  5
                </OMI>
              </OMA>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                2
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  3
                </OMI>
                <OMV name="x"/>
              </OMA>
              <OMI>
                5
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMI>
              10
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                5
              </OMI>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMV name="x"/>
                <OMI>
                  1
                </OMI>
              </OMA>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="unary_minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                5
              </OMI>
              <OMA>
                <OMS cd="arith1" name="plus"/>
                <OMV name="x"/>
                <OMI>
                  1
                </OMI>
              </OMA>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                9
              </OMI>
              <OMA>
                <OMS cd="arith1" name="plus"/>
                <OMV name="x"/>
                <OMI>
                  4
                </OMI>
              </OMA>
            </OMA>
            <OMI>
              5
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMI>
              18
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                2
              </OMI>
              <OMA>
                <OMS cd="arith1" name="plus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    4
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  2
                </OMI>
              </OMA>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                7
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                4
              </OMI>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    4
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  2
                </OMI>
              </OMA>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  1
                </OMI>
                <OMI>
                  2
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMI>
              4
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  2
                </OMI>
                <OMV name="x"/>
              </OMA>
              <OMI>
                2
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  1
                </OMI>
                <OMI>
                  4
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  5
                </OMI>
                <OMI>
                  2
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMI>
              2
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  1
                </OMI>
                <OMI>
                  4
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                3
              </OMI>
              <OMI>
                4
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                2
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMA>
                  <OMS cd="arith1" name="divide"/>
                  <OMI>
                    1
                  </OMI>
                  <OMI>
                    2
                  </OMI>
                </OMA>
                <OMV name="x"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                3
              </OMI>
              <OMI>
                4
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  5
                </OMI>
                <OMI>
                  2
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMI>
              3
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="unary_minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMA>
                    <OMS cd="arith1" name="divide"/>
                    <OMI>
                      1
                    </OMI>
                    <OMI>
                      2
                    </OMI>
                  </OMA>
                  <OMV name="x"/>
                </OMA>
              </OMA>
              <OMI>
                1
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                2
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              5
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMA>
                  <OMS cd="arith1" name="divide"/>
                  <OMI>
                    1
                  </OMI>
                  <OMI>
                    3
                  </OMI>
                </OMA>
                <OMV name="x"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                3
              </OMI>
              <OMI>
                4
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  1
                </OMI>
                <OMI>
                  4
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                6
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  3
                </OMI>
                <OMI>
                  4
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                3
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  2
                </OMI>
                <OMI>
                  3
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                3
              </OMI>
              <OMI>
                4
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  2
                </OMI>
                <OMI>
                  5
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                4
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  1
                </OMI>
                <OMI>
                  2
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                3
              </OMI>
              <OMI>
                4
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  2
                </OMI>
                <OMI>
                  3
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMI>
              2
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  1
                </OMI>
                <OMI>
                  5
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                3
              </OMI>
              <OMI>
                5
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMA>
                  <OMS cd="arith1" name="plus"/>
                  <OMA>
                    <OMS cd="arith1" name="unary_minus"/>
                    <OMI>
                      1
                    </OMI>
                  </OMA>
                  <OMA>
                    <OMS cd="arith1" name="divide"/>
                    <OMI>
                      2
                    </OMI>
                    <OMI>
                      5
                    </OMI>
                  </OMA>
                </OMA>
                <OMV name="x"/>
              </OMA>
              <OMI>
                3
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  3
                </OMI>
                <OMI>
                  5
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                9
              </OMI>
              <OMI>
                10
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                4
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMV name="x"/>
              <OMI>
                3
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  1
                </OMI>
                <OMI>
                  2
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMI>
              4
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="divide"/>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMV name="x"/>
              <OMI>
                3
              </OMI>
            </OMA>
            <OMI>
              2
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMI>
              5
            </OMI>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="plus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMA>
                    <OMS cd="arith1" name="divide"/>
                    <OMI>
                      1
                    </OMI>
                    <OMI>
                      2
                    </OMI>
                  </OMA>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  1
                </OMI>
              </OMA>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  1
                </OMI>
                <OMI>
                  2
                </OMI>
              </OMA>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMI>
                7
              </OMI>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMA>
                  <OMS cd="arith1" name="divide"/>
                  <OMI>
                    2
                  </OMI>
                  <OMI>
                    3
                  </OMI>
                </OMA>
                <OMV name="x"/>
              </OMA>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMI>
              2
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  1
                </OMI>
                <OMI>
                  9
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  3
                </OMI>
                <OMI>
                  4
                </OMI>
              </OMA>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMV name="x"/>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMI>
              3
            </OMI>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="plus"/>
                <OMI>
                  2
                </OMI>
                <OMA>
                  <OMS cd="arith1" name="divide"/>
                  <OMI>
                    1
                  </OMI>
                  <OMI>
                    2
                  </OMI>
                </OMA>
              </OMA>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMV name="x"/>
                <OMI>
                  1
                </OMI>
              </OMA>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="unary_minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  5
                </OMI>
                <OMI>
                  4
                </OMI>
              </OMA>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMV name="x"/>
                <OMI>
                  7
                </OMI>
              </OMA>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  3
                </OMI>
                <OMI>
                  4
                </OMI>
              </OMA>
              <OMA>
                <OMS cd="arith1" name="plus"/>
                <OMV name="x"/>
                <OMI>
                  2
                </OMI>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMI>
                4
              </OMI>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  1
                </OMI>
                <OMI>
                  2
                </OMI>
              </OMA>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                3
              </OMI>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMA>
                    <OMS cd="arith1" name="divide"/>
                    <OMI>
                      1
                    </OMI>
                    <OMI>
                      5
                    </OMI>
                  </OMA>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  1
                </OMI>
              </OMA>
            </OMA>
            <OMI>
              5
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                7
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              14
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    5
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  1
                </OMI>
              </OMA>
              <OMI>
                6
              </OMI>
            </OMA>
            <OMI>
              2
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  4
                </OMI>
                <OMV name="x"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    3
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  6
                </OMI>
              </OMA>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                2
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMA>
                <OMS cd="arith1" name="plus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    2
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  2
                </OMI>
              </OMA>
              <OMI>
                5
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMI>
              12
            </OMI>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMV name="x"/>
                <OMI>
                  1
                </OMI>
              </OMA>
              <OMI>
                6
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="divide"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  3
                </OMI>
                <OMA>
                  <OMS cd="arith1" name="plus"/>
                  <OMV name="x"/>
                  <OMI>
                    2
                  </OMI>
                </OMA>
              </OMA>
            </OMA>
            <OMI>
              6
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                9
              </OMI>
              <OMA>
                <OMS cd="arith1" name="plus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMA>
                    <OMS cd="arith1" name="divide"/>
                    <OMI>
                      2
                    </OMI>
                    <OMI>
                      3
                    </OMI>
                  </OMA>
                  <OMV name="x"/>
                </OMA>
                <OMA>
                  <OMS cd="arith1" name="divide"/>
                  <OMI>
                    1
                  </OMI>
                  <OMI>
                    3
                  </OMI>
                </OMA>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                5
              </OMI>
              <OMI>
                3
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMA>
                <OMS cd="arith1" name="plus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    4
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  2
                </OMI>
              </OMA>
              <OMI>
                3
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="times"/>
              <OMI>
                3
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMA>
                <OMS cd="arith1" name="minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    5
                  </OMI>
                  <OMV name="x"/>
                </OMA>
                <OMI>
                  1
                </OMI>
              </OMA>
              <OMI>
                4
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMI>
            5
          </OMI>
          <OMV name="x"/>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMI>
            5
          </OMI>
          <OMA>
            <OMS cd="arith1" name="plus"/>
            <OMV name="x"/>
            <OMI>
              1
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMV name="x"/>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                5
              </OMI>
            </OMA>
          </OMA>
          <OMI>
            2
          </OMI>
        </OMA>
      </OMOBJ>
    </elem>
  </list>
</reply>

