<reply result="ok" version="0.6.3 (0)">
  <list>
    <elem domain="algebra.equations" identifier="coverup" description="solve an equation by covering up" status="Provisional"/>
    <elem domain="algebra.equations" identifier="linear" description="solve a linear equation" status="Provisional"/>
    <elem domain="algebra.equations" identifier="polynomial" description="solve an equation (higher degree)" status="Provisional"/>
    <elem domain="algebra.equations" identifier="quadratic" description="solve a quadratic equation" status="Provisional"/>
    <elem domain="algebra.equations" identifier="rational" description="solve a rational equation (with a variable in a divisor)" status="Provisional"/>
    <elem domain="algebra.equations.linear" identifier="mixed" description="solve a linear equation with mixed fractions" status="Provisional"/>
    <elem domain="algebra.equations.quadratic" identifier="approximate" description="solve a quadratic equation with approximation" status="Alpha"/>
    <elem domain="algebra.equations.quadratic" identifier="no-abc" description="solve a quadratic equation without abc-formula" status="Alpha"/>
    <elem domain="algebra.inequalities" identifier="linear" description="solve a linear inequation" status="Provisional"/>
    <elem domain="algebra.inequalities" identifier="polynomial" description="solve an inequation of higher degree" status="Provisional"/>
    <elem domain="algebra.inequalities" identifier="quadratic" description="solve a quadratic inequation" status="Provisional"/>
    <elem domain="algebra.manipulation.exponents" identifier="nonnegative" description="write with a non-negative exponent" status="Provisional"/>
    <elem domain="algebra.manipulation.exponents" identifier="powerof" description="write as a power of a" status="Provisional"/>
    <elem domain="algebra.manipulation.exponents" identifier="simplify" description="simplify expression (powers)" status="Provisional"/>
    <elem domain="algebra.manipulation.polynomial" identifier="factor" description="factorize the expression" status="Provisional"/>
    <elem domain="algebra.manipulation.rational" identifier="simplify" description="simplify a rational expression (with a variable in a divisor)" status="Alpha"/>
    <elem domain="arithmetic" identifier="exponents" description="simplify expression (powers)" status="Provisional"/>
    <elem domain="arithmetic" identifier="fractions" description="simplify expression (fractions)" status="Alpha"/>
    <elem domain="calculus" identifier="differentiation" description="Derivative" status="Experimental"/>
    <elem domain="linearalgebra" identifier="gaussianelim" description="Gaussian Elimination" status="Stable"/>
    <elem domain="linearalgebra" identifier="gramschmidt" description="Gram-Schmidt" status="Alpha"/>
    <elem domain="linearalgebra" identifier="linsystem" description="Solve Linear System" status="Stable"/>
    <elem domain="linearalgebra" identifier="systemwithmatrix" description="Solve Linear System with Matrix" status="Provisional"/>
    <elem domain="logic.propositional" identifier="dnf" description="Proposition to DNF" status="Stable"/>
    <elem domain="logic.propositional.dnf" identifier="unicode" description="Proposition to DNF (unicode support)" status="Stable"/>
    <elem domain="relationalgebra" identifier="cnf" description="To conjunctive normal form" status="Alpha"/>
  </list>
</reply>

