<reply result="ok" version="0.5.11">
  <list>
    <elem domain="linalg" identifier="gaussianelim" description="Gaussian Elimination" status="Stable"/>
    <elem domain="linalg" identifier="gramschmidt" description="Gram-Schmidt" status="Provisional"/>
    <elem domain="linalg" identifier="linsystem" description="Solve Linear System" status="Stable"/>
    <elem domain="linalg" identifier="systemwithmatrix" description="Solve Linear System with Matrix" status="Provisional"/>
    <elem domain="logic" identifier="dnf" description="Proposition to DNF" status="Stable"/>
    <elem domain="logic" identifier="dnf-unicode" description="Proposition to DNF (unicode support)" status="Stable"/>
    <elem domain="math" identifier="coverup" description="solve an equation by covering up" status="Provisional"/>
    <elem domain="math" identifier="derivative" description="Derivative" status="Experimental"/>
    <elem domain="math" identifier="factor" description="factorize the expression" status="Provisional"/>
    <elem domain="math" identifier="fraction" description="simplify expression (fractions)" status="Provisional"/>
    <elem domain="math" identifier="higherdegree" description="solve an equation (higher degree)" status="Provisional"/>
    <elem domain="math" identifier="ineqhigherdegree" description="solve an inequation of higher degree" status="Experimental"/>
    <elem domain="math" identifier="integer" description="simplify expression (integers)" status="Provisional"/>
    <elem domain="math" identifier="lineq" description="solve a linear equation" status="Provisional"/>
    <elem domain="math" identifier="linineq" description="solve a linear inequation" status="Experimental"/>
    <elem domain="math" identifier="natural" description="simplify expression (natural numbers)" status="Provisional"/>
    <elem domain="math" identifier="quadreq" description="solve a quadratic equation" status="Provisional"/>
    <elem domain="math" identifier="quadreq-no-abc" description="solve a quadratic equation without abc-formula" status="Provisional"/>
    <elem domain="math" identifier="quadreq-with-approx" description="solve a quadratic equation with approximation" status="Provisional"/>
    <elem domain="math" identifier="quadrineq" description="solve a quadratic inequation" status="Experimental"/>
    <elem domain="math" identifier="rational" description="simplify expression (rational numbers)" status="Provisional"/>
    <elem domain="regexp" identifier="normalform" description="Rewrite a regular expression" status="Provisional"/>
    <elem domain="relationalg" identifier="cnf" description="To conjunctive normal form" status="Provisional"/>
  </list>
</reply>

