<reply result="ok" version="1.0 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.flip" location="[]">
      <state>
        <prefix>
          [7,0,1,0,0]
        </prefix>
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMV name="x"/>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMI>
                2
              </OMI>
              <OMA>
                <OMS cd="arith1" name="divide"/>
                <OMI>
                  1
                </OMI>
                <OMI>
                  3
                </OMI>
              </OMA>
            </OMA>
          </OMA>
        </OMOBJ>
      </state>
    </elem>
  </list>
</reply>

