<reply result="ok" version="0.5.8">
  <state>
    <prefix>
      []
    </prefix>
    <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
      <OMA>
        <OMS cd="calculus1" name="diff"/>
        <OMBIND>
          <OMS cd="fns1" name="lambda"/>
          <OMBVAR>
            <OMV name="x"/>
          </OMBVAR>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMI>
              2
            </OMI>
            <OMV name="x"/>
          </OMA>
        </OMBIND>
      </OMA>
    </OMOBJ>
  </state>
</reply>

