<reply result="ok" version="1.0.3 (0)">
  <state>
    <prefix>
      []
    </prefix>
    <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
      <OMA>
        <OMS cd="relation1" name="eq"/>
        <OMA>
          <OMS cd="arith1" name="unary_minus"/>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMI>
              5
            </OMI>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMV name="x"/>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
        </OMA>
        <OMA>
          <OMS cd="arith1" name="minus"/>
          <OMA>
            <OMS cd="arith1" name="times"/>
            <OMI>
              9
            </OMI>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMV name="x"/>
              <OMI>
                4
              </OMI>
            </OMA>
          </OMA>
          <OMI>
            5
          </OMI>
        </OMA>
      </OMA>
    </OMOBJ>
  </state>
</reply>

