<reply result="ok" version="0.5.8">
  <list>
    <elem ruleid="Scale equation to one">
      <expr>
        x+3*y+1 == 2
2*x == 5
      </expr>
    </elem>
    <elem ruleid="Eliminate variable">
      <expr>
        x+3*y+1 == 2
(-6)*y-2 == 1
      </expr>
    </elem>
    <elem ruleid="Scale equation to one">
      <expr>
        x+3*y+1 == 2
y+1/3 == -1/6
      </expr>
      <context>
        <item name="covered" value="1"/>
      </context>
    </elem>
    <elem ruleid="Scale equation to one">
      <expr>
        x+3*y == 1
y == -1/2
      </expr>
      <context>
        <item name="covered" value="1"/>
      </context>
    </elem>
    <elem ruleid="Back substitution">
      <expr>
        x == 5/2
y == -1/2
      </expr>
      <context>
        <item name="covered" value="1"/>
      </context>
    </elem>
    <elem ruleid="Scale equation to one">
      <expr>
        x == 5/2
y == -1/2
      </expr>
      <context>
        <item name="covered" value="0"/>
      </context>
    </elem>
  </list>
</reply>

