<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.merge" location="[]">
      <state>
        <prefix>
          [4,1,1,1]
        </prefix>
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMI>
                3
              </OMI>
              <OMV name="x"/>
            </OMA>
            <OMI>
              5
            </OMI>
          </OMA>
        </OMOBJ>
      </state>
    </elem>
  </list>
</reply>

