<reply result="ok" version="0.6.5 (0)">
  <rule name="absorpand" buggy="false" rewriterule="true">
    <description>
      absorpand
    </description>
    <CMP>
      a /\ (a || b) ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ (b || a) ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ a ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (b || a) /\ a ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$1"/>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="absorpor" buggy="false" rewriterule="true">
    <description>
      absorpor
    </description>
    <CMP>
      a || a /\ b ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a || b /\ a ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || a ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      b /\ a || a ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$1"/>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="andcomplbuggy" buggy="true" rewriterule="true">
    <description>
      andcomplbuggy
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a /\ ~a /~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a /\ a /~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ ~a /~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a /\ a /~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="andoveror" buggy="false" rewriterule="true">
    <description>
      andoveror
    </description>
    <CMP>
      a /\ (b || c) ~&gt; a /\ b || a /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ c ~&gt; a /\ c || b /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="andsame" buggy="true" rewriterule="true">
    <description>
      andsame
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a /\ a /~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="assimp" buggy="true" rewriterule="true">
    <description>
      assimp
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a -&gt; b -&gt; c /~&gt; (a -&gt; b) -&gt; c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a -&gt; b) -&gt; c /~&gt; a -&gt; b -&gt; c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="assocand" buggy="false" rewriterule="true">
    <description>
      assocand
    </description>
    <group>
      Associativity
    </group>
    <CMP>
      (a /\ b) /\ c ~&gt; a /\ b /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="assocor" buggy="false" rewriterule="true">
    <description>
      assocor
    </description>
    <group>
      Associativity
    </group>
    <CMP>
      (a || b) || c ~&gt; a || b || c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggyabsor" buggy="true" rewriterule="true">
    <description>
      buggyabsor
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      (a || b) || (a /\ b) /\ c /~&gt; a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="and"/>
                  <OMV name="$0"/>
                  <OMV name="$1"/>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || (a || b) /\ c /~&gt; a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="or"/>
                  <OMV name="$0"/>
                  <OMV name="$1"/>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ (a /\ b || c) /~&gt; a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="and"/>
                  <OMV name="$0"/>
                  <OMV name="$1"/>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a /\ b) /\ ((a || b) || c) /~&gt; a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="or"/>
                  <OMV name="$0"/>
                  <OMV name="$1"/>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggyassoc" buggy="true" rewriterule="true">
    <description>
      buggyassoc
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a || b /\ c /~&gt; (a || b) /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ c /~&gt; a || b /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || c /~&gt; a /\ (b || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ (b || c) /~&gt; a /\ b || c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggydemorgan1" buggy="true" rewriterule="true">
    <description>
      buggydemorgan1
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a /\ b) /~&gt; ~a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a /\ b) /~&gt; a || ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a /\ b) /~&gt; a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a || b) /~&gt; ~a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a || b) /~&gt; a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a || b) /~&gt; a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggydemorgan2" buggy="true" rewriterule="true">
    <description>
      buggydemorgan2
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a /\ b) /~&gt; ~(~a || ~b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a || b) /~&gt; ~(~a /\ ~b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggydemorgan3" buggy="true" rewriterule="true">
    <description>
      buggydemorgan3
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a /\ b) /~&gt; ~a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggydemorgan4" buggy="true" rewriterule="true">
    <description>
      buggydemorgan4
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a || b) /~&gt; ~a || ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggydemorgan5" buggy="true" rewriterule="true">
    <description>
      buggydemorgan5
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(~(a /\ b) || c) /~&gt; ~(~a || ~b) || c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMA>
                    <OMS cd="logic1" name="and"/>
                    <OMV name="$0"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="or"/>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$0"/>
                  </OMA>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(~(a /\ b) /\ c) /~&gt; ~(~a || ~b) /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMA>
                    <OMS cd="logic1" name="and"/>
                    <OMV name="$0"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="or"/>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$0"/>
                  </OMA>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(~(a || b) || c) /~&gt; ~(~a /\ ~b) || c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMA>
                    <OMS cd="logic1" name="or"/>
                    <OMV name="$0"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="and"/>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$0"/>
                  </OMA>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(~(a || b) /\ c) /~&gt; ~(~a /\ ~b) /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMA>
                    <OMS cd="logic1" name="or"/>
                    <OMV name="$0"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="and"/>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$0"/>
                  </OMA>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggydistr" buggy="true" rewriterule="true">
    <description>
      buggydistr
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a /\ (b || c) /~&gt; (a /\ b) /\ a /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ c /~&gt; (a /\ c) /\ b /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ (b || c) /~&gt; (a || b) /\ (a || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ c /~&gt; (a || c) /\ (b || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a || b /\ c /~&gt; (a || b) || a || c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || c /~&gt; (a || c) || b || c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a || b /\ c /~&gt; a /\ b || a /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || c /~&gt; a /\ c || b /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggydistrnot" buggy="true" rewriterule="true">
    <description>
      buggydistrnot
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~a /\ (b || c) /~&gt; ~a /\ b || a /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a /\ (b || c) /~&gt; a /\ b || ~a /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ ~c /~&gt; a /\ ~c || b /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$2"/>
                </OMA>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ ~c /~&gt; a /\ c || b /\ ~c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$2"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a || b /\ c /~&gt; (~a || b) /\ (a || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a || b /\ c /~&gt; (a || b) /\ (~a || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || ~c /~&gt; (a || ~c) /\ (b || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$2"/>
                </OMA>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || ~c /~&gt; (a || c) /\ (b || ~c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$2"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggyequivelim1" buggy="true" rewriterule="true">
    <description>
      buggyequivelim1
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a &lt;-&gt; b /~&gt; a /\ b || ~(a /\ b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="and"/>
                  <OMV name="$0"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; b /~&gt; a /\ b || ~a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; b /~&gt; a /\ b || a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; b /~&gt; a /\ b || a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; b /~&gt; a /\ b || ~(a || ~b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="or"/>
                  <OMV name="$0"/>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggyequivelim2" buggy="true" rewriterule="true">
    <description>
      buggyequivelim2
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a &lt;-&gt; b /~&gt; (a || b) /\ (~a || ~b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; b /~&gt; (a /\ b) /\ ~a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; b /~&gt; a /\ b || ~a || ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggyimplelim" buggy="true" rewriterule="true">
    <description>
      buggyimplelim
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a -&gt; b /~&gt; ~(a || b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a -&gt; b /~&gt; a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a -&gt; b /~&gt; ~(a /\ b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggyimplelim1" buggy="true" rewriterule="true">
    <description>
      buggyimplelim1
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a -&gt; b /~&gt; ~a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggyimplelim2" buggy="true" rewriterule="true">
    <description>
      buggyimplelim2
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a -&gt; b /~&gt; a /\ b || ~a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggynotoverimpl" buggy="true" rewriterule="true">
    <description>
      buggynotoverimpl
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a -&gt; b) /~&gt; ~a -&gt; ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggyparenth1" buggy="true" rewriterule="true">
    <description>
      buggyparenth1
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a /\ b) /~&gt; ~a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a || b) /~&gt; ~a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggyparenth2" buggy="true" rewriterule="true">
    <description>
      buggyparenth2
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a &lt;-&gt; b) /~&gt; ~(a /\ b) || ~a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="equivalent"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="and"/>
                  <OMV name="$0"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="buggyparenth3" buggy="true" rewriterule="true">
    <description>
      buggyparenth3
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(~a /\ b) /~&gt; a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(~a || b) /~&gt; a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(~a -&gt; b) /~&gt; a -&gt; b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(~a &lt;-&gt; b) /~&gt; a &lt;-&gt; b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="equivalent"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="command" buggy="false" rewriterule="true">
    <description>
      command
    </description>
    <group>
      Commutativity
    </group>
    <CMP>
      a /\ b ~&gt; b /\ a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$1"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="commequiv" buggy="false" rewriterule="true">
    <description>
      commequiv
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      a &lt;-&gt; b ~&gt; b &lt;-&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$1"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="commimp" buggy="true" rewriterule="true">
    <description>
      commimp
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a -&gt; b /~&gt; b -&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$1"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="commor" buggy="false" rewriterule="true">
    <description>
      commor
    </description>
    <group>
      Commutativity
    </group>
    <CMP>
      a || b ~&gt; b || a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$1"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="compland" buggy="false" rewriterule="true">
    <description>
      compland
    </description>
    <CMP>
      a /\ ~a ~&gt; F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a /\ a ~&gt; F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="complor" buggy="false" rewriterule="true">
    <description>
      complor
    </description>
    <CMP>
      a || ~a ~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a || a ~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="defequiv" buggy="false" rewriterule="true">
    <description>
      defequiv
    </description>
    <CMP>
      a &lt;-&gt; b ~&gt; a /\ b || ~a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="defequivimpls" buggy="false" rewriterule="true">
    <description>
      defequivimpls
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      a &lt;-&gt; b ~&gt; a -&gt; b /\ b -&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$1"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="defimpl" buggy="false" rewriterule="true">
    <description>
      defimpl
    </description>
    <CMP>
      a -&gt; b ~&gt; ~a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="demorganand" buggy="false" rewriterule="true">
    <description>
      demorganand
    </description>
    <CMP>
      ~(a /\ b) ~&gt; ~a || ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="demorganor" buggy="false" rewriterule="true">
    <description>
      demorganor
    </description>
    <CMP>
      ~(a || b) ~&gt; ~a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="equivelim3" buggy="true" rewriterule="true">
    <description>
      equivelim3
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a &lt;-&gt; b /~&gt; ~a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="equivsame" buggy="false" rewriterule="true">
    <description>
      equivsame
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      a &lt;-&gt; a ~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="falseinequiv" buggy="false" rewriterule="true">
    <description>
      falseinequiv
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      F &lt;-&gt; a ~&gt; ~a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMS cd="logic1" name="false"/>
              <OMV name="$0"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; F ~&gt; ~a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="false"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="falseinimpl" buggy="false" rewriterule="true">
    <description>
      falseinimpl
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      F -&gt; a ~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMS cd="logic1" name="false"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a -&gt; F ~&gt; ~a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="false"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="falseprop" buggy="true" rewriterule="true">
    <description>
      falseprop
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a || F /~&gt; F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="false"/>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      F || a /~&gt; F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMS cd="logic1" name="false"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ F /~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="false"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      F /\ a /~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMS cd="logic1" name="false"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="falsezeroand" buggy="false" rewriterule="true">
    <description>
      falsezeroand
    </description>
    <CMP>
      F /\ a ~&gt; F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMS cd="logic1" name="false"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ F ~&gt; F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="false"/>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="falsezeroor" buggy="false" rewriterule="true">
    <description>
      falsezeroor
    </description>
    <CMP>
      F || a ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMS cd="logic1" name="false"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a || F ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="false"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="genandoveror" buggy="false" rewriterule="false">
    <description>
      genandoveror
    </description>
  </rule>
  <rule name="gendemorganand" buggy="false" rewriterule="false">
    <description>
      gendemorganand
    </description>
  </rule>
  <rule name="gendemorganor" buggy="false" rewriterule="false">
    <description>
      gendemorganor
    </description>
  </rule>
  <rule name="genoroverand" buggy="false" rewriterule="false">
    <description>
      genoroverand
    </description>
    <group>
      DistributionOrOverAnd
    </group>
  </rule>
  <rule name="idemequi" buggy="true" rewriterule="true">
    <description>
      idemequi
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a &lt;-&gt; a /~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="idemimp" buggy="true" rewriterule="true">
    <description>
      idemimp
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a -&gt; a /~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="idempand" buggy="false" rewriterule="true">
    <description>
      idempand
    </description>
    <CMP>
      a /\ a ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="idempor" buggy="false" rewriterule="true">
    <description>
      idempor
    </description>
    <CMP>
      a || a ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="implsame" buggy="false" rewriterule="true">
    <description>
      implsame
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      a -&gt; a ~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="invandoveror" buggy="false" rewriterule="false">
    <description>
      invandoveror
    </description>
    <group>
      InverseDistr
    </group>
  </rule>
  <rule name="invdemorganand" buggy="false" rewriterule="false">
    <description>
      invdemorganand
    </description>
    <group>
      InverseDeMorgan
    </group>
  </rule>
  <rule name="invdemorganor" buggy="false" rewriterule="false">
    <description>
      invdemorganor
    </description>
    <group>
      InverseDeMorgan
    </group>
  </rule>
  <rule name="invoroverand" buggy="false" rewriterule="false">
    <description>
      invoroverand
    </description>
    <group>
      InverseDistr
    </group>
  </rule>
  <rule name="notfalse" buggy="false" rewriterule="true">
    <description>
      notfalse
    </description>
    <CMP>
      ~F ~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="logic1" name="not"/>
            <OMS cd="logic1" name="false"/>
          </OMA>
          <OMS cd="logic1" name="true"/>
        </OMA>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="notnot" buggy="false" rewriterule="true">
    <description>
      notnot
    </description>
    <CMP>
      ~~a ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="nottrue" buggy="false" rewriterule="true">
    <description>
      nottrue
    </description>
    <CMP>
      ~T ~&gt; F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="logic1" name="not"/>
            <OMS cd="logic1" name="true"/>
          </OMA>
          <OMS cd="logic1" name="false"/>
        </OMA>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="orcomplbuggy" buggy="true" rewriterule="true">
    <description>
      orcomplbuggy
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a || ~a /~&gt; F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a || a /~&gt; F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a || ~a /~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a || a /~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="oroverand" buggy="false" rewriterule="true">
    <description>
      oroverand
    </description>
    <group>
      DistributionOrOverAnd
    </group>
    <CMP>
      a || b /\ c ~&gt; (a || b) /\ (a || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || c ~&gt; (a || c) /\ (b || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="orsame" buggy="true" rewriterule="true">
    <description>
      orsame
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a || a /~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="trueinequiv" buggy="false" rewriterule="true">
    <description>
      trueinequiv
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      T &lt;-&gt; a ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMS cd="logic1" name="true"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; T ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="true"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="trueinimpl" buggy="false" rewriterule="true">
    <description>
      trueinimpl
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      T -&gt; a ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMS cd="logic1" name="true"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a -&gt; T ~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="true"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="trueprop" buggy="true" rewriterule="true">
    <description>
      trueprop
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a || T /~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="true"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      T || a /~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMS cd="logic1" name="true"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ T /~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="true"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      T /\ a /~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMS cd="logic1" name="true"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="truezeroand" buggy="false" rewriterule="true">
    <description>
      truezeroand
    </description>
    <CMP>
      T /\ a ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMS cd="logic1" name="true"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ T ~&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="true"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="truezeroor" buggy="false" rewriterule="true">
    <description>
      truezeroor
    </description>
    <CMP>
      T || a ~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMS cd="logic1" name="true"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a || T ~&gt; T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="true"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
</reply>

