<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem name="abc formula" buggy="false" rewriterule="false"/>
    <elem name="algebra.equations.buggy.abc.minus-4ac" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.abc.minus-b" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.abc.one-solution" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.abc.two-a" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.cancel-minus" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.coverup.even-power" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.coverup.even-power-forget" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.coverup.even-power-too-early" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.coverup.square-minus" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.coverup.times-mul" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.coverup.times-with-plus" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.distr-square" buggy="true" rewriterule="true"/>
    <elem name="algebra.equations.buggy.distr-square-forget" buggy="true" rewriterule="true"/>
    <elem name="algebra.equations.buggy.distr-times-denom" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.distr-times-plus" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.distr-times-plus-forget" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.distr-times-plus-sign" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.distr-times-too-many" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.divide-negate" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.divide-numdenom" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.division-by-var-both" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.division-by-var-zero" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.flip-negate-one-side" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.minus-minus" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.multiply-forget-one" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.multiply-one-side" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.negate-all" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.negate-one-side" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.plus" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.priority-times" buggy="true" rewriterule="false"/>
    <elem name="algebra.equations.buggy.square-multiplication" buggy="true" rewriterule="true"/>
    <elem name="algebra.equations.coverup.negate" buggy="false" rewriterule="false"/>
    <elem name="algebra.equations.coverup.numerator" buggy="false" rewriterule="false"/>
    <elem name="algebra.equations.coverup.onevar.minus-left" buggy="false" rewriterule="false"/>
    <elem name="algebra.equations.coverup.onevar.minus-right" buggy="false" rewriterule="false"/>
    <elem name="algebra.equations.coverup.onevar.plus" buggy="false" rewriterule="false"/>
    <elem name="algebra.equations.coverup.power" buggy="false" rewriterule="false"/>
    <elem name="algebra.equations.coverup.times" buggy="false" rewriterule="false"/>
    <elem name="approximate" buggy="false" rewriterule="false"/>
    <elem name="bring a to one" buggy="false" rewriterule="false"/>
    <elem name="cancel terms" buggy="false" rewriterule="false"/>
    <elem name="common factor var" buggy="false" rewriterule="false"/>
    <elem name="distribution division" buggy="false" rewriterule="false"/>
    <elem name="distribution multiplication" buggy="false" rewriterule="false"/>
    <elem name="distribution square" buggy="false" rewriterule="true"/>
    <elem name="factor left as square" buggy="false" rewriterule="false"/>
    <elem name="flip equation" buggy="false" rewriterule="true"/>
    <elem name="merge similar terms" buggy="false" rewriterule="false"/>
    <elem name="move to left" buggy="false" rewriterule="false"/>
    <elem name="multiplication is zero" buggy="false" rewriterule="false"/>
    <elem name="nice factors" buggy="false" rewriterule="false"/>
    <elem name="no linear term b" buggy="false" rewriterule="false"/>
    <elem name="prepare split square" buggy="false" rewriterule="false"/>
    <elem name="same constant factor" buggy="false" rewriterule="false"/>
    <elem name="same factor" buggy="false" rewriterule="false"/>
    <elem name="simpler polynomial" buggy="false" rewriterule="false"/>
    <elem name="simpler square root" buggy="false" rewriterule="false"/>
    <elem name="square both sides" buggy="false" rewriterule="true"/>
  </list>
</reply>

