<reply result="ok" version="0.5.12">
  <rule name="AbsorpAnd" buggy="false" rewriterule="true">
    <description>
      AbsorpAnd
    </description>
    <CMP>
      a /\ (a || b)  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ (b || a)  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ a  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (b || a) /\ a  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$1"/>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="AbsorpOr" buggy="false" rewriterule="true">
    <description>
      AbsorpOr
    </description>
    <CMP>
      a || a /\ b  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a || b /\ a  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || a  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      b /\ a || a  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$1"/>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="AndComplBuggy" buggy="true" rewriterule="true">
    <description>
      AndComplBuggy
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a /\ ~a  /~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a /\ a  /~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ ~a  /~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a /\ a  /~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="AndOverOr" buggy="false" rewriterule="true">
    <description>
      AndOverOr
    </description>
    <CMP>
      a /\ (b || c)  ~&gt;  a /\ b || a /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ c  ~&gt;  a /\ c || b /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="AndSame" buggy="true" rewriterule="true">
    <description>
      AndSame
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a /\ a  /~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="AssImp" buggy="true" rewriterule="true">
    <description>
      AssImp
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a -&gt; b -&gt; c  /~&gt;  (a -&gt; b) -&gt; c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a -&gt; b) -&gt; c  /~&gt;  a -&gt; b -&gt; c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="AssocAnd" buggy="false" rewriterule="true">
    <description>
      AssocAnd
    </description>
    <group>
      Associativity
    </group>
    <CMP>
      (a /\ b) /\ c  ~&gt;  a /\ b /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="AssocOr" buggy="false" rewriterule="true">
    <description>
      AssocOr
    </description>
    <group>
      Associativity
    </group>
    <CMP>
      (a || b) || c  ~&gt;  a || b || c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyAbsor" buggy="true" rewriterule="true">
    <description>
      BuggyAbsor
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      (a || b) || (a /\ b) /\ c  /~&gt;  a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="and"/>
                  <OMV name="$0"/>
                  <OMV name="$1"/>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || (a || b) /\ c  /~&gt;  a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="or"/>
                  <OMV name="$0"/>
                  <OMV name="$1"/>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ (a /\ b || c)  /~&gt;  a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="and"/>
                  <OMV name="$0"/>
                  <OMV name="$1"/>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a /\ b) /\ ((a || b) || c)  /~&gt;  a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="or"/>
                  <OMV name="$0"/>
                  <OMV name="$1"/>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyAssoc" buggy="true" rewriterule="true">
    <description>
      BuggyAssoc
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a || b /\ c  /~&gt;  (a || b) /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ c  /~&gt;  a || b /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || c  /~&gt;  a /\ (b || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ (b || c)  /~&gt;  a /\ b || c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyDeMorgan1" buggy="true" rewriterule="true">
    <description>
      BuggyDeMorgan1
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a /\ b)  /~&gt;  ~a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a /\ b)  /~&gt;  a || ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a /\ b)  /~&gt;  a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a || b)  /~&gt;  ~a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a || b)  /~&gt;  a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a || b)  /~&gt;  a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyDeMorgan2" buggy="true" rewriterule="true">
    <description>
      BuggyDeMorgan2
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a /\ b)  /~&gt;  ~(~a || ~b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a || b)  /~&gt;  ~(~a /\ ~b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyDeMorgan3" buggy="true" rewriterule="true">
    <description>
      BuggyDeMorgan3
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a /\ b)  /~&gt;  ~a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyDeMorgan4" buggy="true" rewriterule="true">
    <description>
      BuggyDeMorgan4
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a || b)  /~&gt;  ~a || ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyDeMorgan5" buggy="true" rewriterule="true">
    <description>
      BuggyDeMorgan5
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(~(a /\ b) || c)  /~&gt;  ~(~a || ~b) || c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMA>
                    <OMS cd="logic1" name="and"/>
                    <OMV name="$0"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="or"/>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$0"/>
                  </OMA>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(~(a /\ b) /\ c)  /~&gt;  ~(~a || ~b) /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMA>
                    <OMS cd="logic1" name="and"/>
                    <OMV name="$0"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="or"/>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$0"/>
                  </OMA>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(~(a || b) || c)  /~&gt;  ~(~a /\ ~b) || c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMA>
                    <OMS cd="logic1" name="or"/>
                    <OMV name="$0"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="and"/>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$0"/>
                  </OMA>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(~(a || b) /\ c)  /~&gt;  ~(~a /\ ~b) /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMA>
                    <OMS cd="logic1" name="or"/>
                    <OMV name="$0"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="and"/>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$0"/>
                  </OMA>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
              </OMA>
              <OMV name="$2"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyDistr" buggy="true" rewriterule="true">
    <description>
      BuggyDistr
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a /\ (b || c)  /~&gt;  (a /\ b) /\ a /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ c  /~&gt;  (a /\ c) /\ b /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ (b || c)  /~&gt;  (a || b) /\ (a || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ c  /~&gt;  (a || c) /\ (b || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a || b /\ c  /~&gt;  (a || b) || a || c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || c  /~&gt;  (a || c) || b || c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a || b /\ c  /~&gt;  a /\ b || a /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || c  /~&gt;  a /\ c || b /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyDistrNot" buggy="true" rewriterule="true">
    <description>
      BuggyDistrNot
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~a /\ (b || c)  /~&gt;  ~a /\ b || a /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a /\ (b || c)  /~&gt;  a /\ b || ~a /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ ~c  /~&gt;  a /\ ~c || b /\ c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$2"/>
                </OMA>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      (a || b) /\ ~c  /~&gt;  a /\ c || b /\ ~c
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$2"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a || b /\ c  /~&gt;  (~a || b) /\ (a || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a || b /\ c  /~&gt;  (a || b) /\ (~a || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || ~c  /~&gt;  (a || ~c) /\ (b || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$2"/>
                </OMA>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || ~c  /~&gt;  (a || c) /\ (b || ~c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$2"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyEquivElim1" buggy="true" rewriterule="true">
    <description>
      BuggyEquivElim1
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a &lt;-&gt; b  /~&gt;  a /\ b || ~(a /\ b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="and"/>
                  <OMV name="$0"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; b  /~&gt;  a /\ b || ~a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; b  /~&gt;  a /\ b || a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; b  /~&gt;  a /\ b || a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; b  /~&gt;  a /\ b || ~(a || ~b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="or"/>
                  <OMV name="$0"/>
                  <OMA>
                    <OMS cd="logic1" name="not"/>
                    <OMV name="$1"/>
                  </OMA>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyEquivElim2" buggy="true" rewriterule="true">
    <description>
      BuggyEquivElim2
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a &lt;-&gt; b  /~&gt;  (a || b) /\ (~a || ~b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; b  /~&gt;  (a /\ b) /\ ~a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; b  /~&gt;  a /\ b || ~a || ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyImplElim" buggy="true" rewriterule="true">
    <description>
      BuggyImplElim
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a -&gt; b  /~&gt;  ~(a || b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a -&gt; b  /~&gt;  a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a -&gt; b  /~&gt;  ~(a /\ b)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyImplElim1" buggy="true" rewriterule="true">
    <description>
      BuggyImplElim1
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a -&gt; b  /~&gt;  ~a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyImplElim2" buggy="true" rewriterule="true">
    <description>
      BuggyImplElim2
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a -&gt; b  /~&gt;  a /\ b || ~a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyNotOverImpl" buggy="true" rewriterule="true">
    <description>
      BuggyNotOverImpl
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a -&gt; b)  /~&gt;  ~a -&gt; ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyParenth1" buggy="true" rewriterule="true">
    <description>
      BuggyParenth1
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a /\ b)  /~&gt;  ~a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(a || b)  /~&gt;  ~a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyParenth2" buggy="true" rewriterule="true">
    <description>
      BuggyParenth2
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(a &lt;-&gt; b)  /~&gt;  ~(a /\ b) || ~a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="equivalent"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMA>
                  <OMS cd="logic1" name="and"/>
                  <OMV name="$0"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="BuggyParenth3" buggy="true" rewriterule="true">
    <description>
      BuggyParenth3
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      ~(~a /\ b)  /~&gt;  a /\ b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(~a || b)  /~&gt;  a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(~a -&gt; b)  /~&gt;  a -&gt; b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~(~a &lt;-&gt; b)  /~&gt;  a &lt;-&gt; b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="equivalent"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="CommAnd" buggy="false" rewriterule="true">
    <description>
      CommAnd
    </description>
    <group>
      Commutativity
    </group>
    <CMP>
      a /\ b  ~&gt;  b /\ a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$1"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="CommEquiv" buggy="false" rewriterule="true">
    <description>
      CommEquiv
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      a &lt;-&gt; b  ~&gt;  b &lt;-&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$1"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="CommImp" buggy="true" rewriterule="true">
    <description>
      CommImp
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a -&gt; b  /~&gt;  b -&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$1"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="CommOr" buggy="false" rewriterule="true">
    <description>
      CommOr
    </description>
    <group>
      Commutativity
    </group>
    <CMP>
      a || b  ~&gt;  b || a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$1"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="ComplAnd" buggy="false" rewriterule="true">
    <description>
      ComplAnd
    </description>
    <CMP>
      a /\ ~a  ~&gt;  F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a /\ a  ~&gt;  F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="ComplOr" buggy="false" rewriterule="true">
    <description>
      ComplOr
    </description>
    <CMP>
      a || ~a  ~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a || a  ~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="DeMorganAnd" buggy="false" rewriterule="true">
    <description>
      DeMorganAnd
    </description>
    <CMP>
      ~(a /\ b)  ~&gt;  ~a || ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="DeMorganOr" buggy="false" rewriterule="true">
    <description>
      DeMorganOr
    </description>
    <CMP>
      ~(a || b)  ~&gt;  ~a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$1"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="DefEquiv" buggy="false" rewriterule="true">
    <description>
      DefEquiv
    </description>
    <CMP>
      a &lt;-&gt; b  ~&gt;  a /\ b || ~a /\ ~b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$0"/>
                </OMA>
                <OMA>
                  <OMS cd="logic1" name="not"/>
                  <OMV name="$1"/>
                </OMA>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="DefEquivImpls" buggy="false" rewriterule="true">
    <description>
      DefEquivImpls
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      a &lt;-&gt; b  ~&gt;  a -&gt; b /\ b -&gt; a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="implies"/>
                <OMV name="$1"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="DefImpl" buggy="false" rewriterule="true">
    <description>
      DefImpl
    </description>
    <CMP>
      a -&gt; b  ~&gt;  ~a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="EquivElim3" buggy="true" rewriterule="true">
    <description>
      EquivElim3
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a &lt;-&gt; b  /~&gt;  ~a || b
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$1"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$1"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="EquivSame" buggy="false" rewriterule="true">
    <description>
      EquivSame
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      a &lt;-&gt; a  ~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="FalseInEquiv" buggy="false" rewriterule="true">
    <description>
      FalseInEquiv
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      F &lt;-&gt; a  ~&gt;  ~a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMS cd="logic1" name="false"/>
              <OMV name="$0"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; F  ~&gt;  ~a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="false"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="FalseInImpl" buggy="false" rewriterule="true">
    <description>
      FalseInImpl
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      F -&gt; a  ~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMS cd="logic1" name="false"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a -&gt; F  ~&gt;  ~a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="false"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMV name="$0"/>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="FalseProp" buggy="true" rewriterule="true">
    <description>
      FalseProp
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a || F  /~&gt;  F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="false"/>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      F || a  /~&gt;  F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMS cd="logic1" name="false"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ F  /~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="false"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      F /\ a  /~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMS cd="logic1" name="false"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="FalseZeroAnd" buggy="false" rewriterule="true">
    <description>
      FalseZeroAnd
    </description>
    <CMP>
      F /\ a  ~&gt;  F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMS cd="logic1" name="false"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ F  ~&gt;  F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="false"/>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="FalseZeroOr" buggy="false" rewriterule="true">
    <description>
      FalseZeroOr
    </description>
    <CMP>
      F || a  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMS cd="logic1" name="false"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a || F  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="false"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="GenAndOverOr" buggy="false" rewriterule="false">
    <description>
      GenAndOverOr
    </description>
  </rule>
  <rule name="GenDeMorganAnd" buggy="false" rewriterule="false">
    <description>
      GenDeMorganAnd
    </description>
  </rule>
  <rule name="GenDeMorganOr" buggy="false" rewriterule="false">
    <description>
      GenDeMorganOr
    </description>
  </rule>
  <rule name="GenOrOverAnd" buggy="false" rewriterule="false">
    <description>
      GenOrOverAnd
    </description>
    <group>
      DistributionOrOverAnd
    </group>
  </rule>
  <rule name="IdemEqui" buggy="true" rewriterule="true">
    <description>
      IdemEqui
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a &lt;-&gt; a  /~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="IdemImp" buggy="true" rewriterule="true">
    <description>
      IdemImp
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a -&gt; a  /~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="IdempAnd" buggy="false" rewriterule="true">
    <description>
      IdempAnd
    </description>
    <CMP>
      a /\ a  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="IdempOr" buggy="false" rewriterule="true">
    <description>
      IdempOr
    </description>
    <CMP>
      a || a  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="ImplSame" buggy="false" rewriterule="true">
    <description>
      ImplSame
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      a -&gt; a  ~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="InvAndOverOr" buggy="false" rewriterule="false">
    <description>
      InvAndOverOr
    </description>
    <group>
      InverseDistr
    </group>
  </rule>
  <rule name="InvDeMorganAnd" buggy="false" rewriterule="false">
    <description>
      InvDeMorganAnd
    </description>
    <group>
      InverseDeMorgan
    </group>
  </rule>
  <rule name="InvDeMorganOr" buggy="false" rewriterule="false">
    <description>
      InvDeMorganOr
    </description>
    <group>
      InverseDeMorgan
    </group>
  </rule>
  <rule name="InvOrOverAnd" buggy="false" rewriterule="false">
    <description>
      InvOrOverAnd
    </description>
    <group>
      InverseDistr
    </group>
  </rule>
  <rule name="NotFalse" buggy="false" rewriterule="true">
    <description>
      NotFalse
    </description>
    <CMP>
      ~F  ~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="logic1" name="not"/>
            <OMS cd="logic1" name="false"/>
          </OMA>
          <OMS cd="logic1" name="true"/>
        </OMA>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="NotNot" buggy="false" rewriterule="true">
    <description>
      NotNot
    </description>
    <CMP>
      ~~a  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="not"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="NotTrue" buggy="false" rewriterule="true">
    <description>
      NotTrue
    </description>
    <CMP>
      ~T  ~&gt;  F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMA>
            <OMS cd="logic1" name="not"/>
            <OMS cd="logic1" name="true"/>
          </OMA>
          <OMS cd="logic1" name="false"/>
        </OMA>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="OrComplBuggy" buggy="true" rewriterule="true">
    <description>
      OrComplBuggy
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a || ~a  /~&gt;  F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a || a  /~&gt;  F
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="false"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a || ~a  /~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      ~a || a  /~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="not"/>
                <OMV name="$0"/>
              </OMA>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="OrOverAnd" buggy="false" rewriterule="true">
    <description>
      OrOverAnd
    </description>
    <group>
      DistributionOrOverAnd
    </group>
    <CMP>
      a || b /\ c  ~&gt;  (a || b) /\ (a || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ b || c  ~&gt;  (a || c) /\ (b || c)
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
            <OMV name="$1"/>
            <OMV name="$2"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMA>
                <OMS cd="logic1" name="and"/>
                <OMV name="$0"/>
                <OMV name="$1"/>
              </OMA>
              <OMV name="$2"/>
            </OMA>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$0"/>
                <OMV name="$2"/>
              </OMA>
              <OMA>
                <OMS cd="logic1" name="or"/>
                <OMV name="$1"/>
                <OMV name="$2"/>
              </OMA>
            </OMA>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="OrSame" buggy="true" rewriterule="true">
    <description>
      OrSame
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a || a  /~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="TrueInEquiv" buggy="false" rewriterule="true">
    <description>
      TrueInEquiv
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      T &lt;-&gt; a  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMS cd="logic1" name="true"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a &lt;-&gt; T  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="equivalent"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="true"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="TrueInImpl" buggy="false" rewriterule="true">
    <description>
      TrueInImpl
    </description>
    <group>
      Additional rules
    </group>
    <CMP>
      T -&gt; a  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMS cd="logic1" name="true"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a -&gt; T  ~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="implies"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="true"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="TrueProp" buggy="true" rewriterule="true">
    <description>
      TrueProp
    </description>
    <group>
      Common misconceptions
    </group>
    <CMP>
      a || T  /~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="true"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      T || a  /~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMS cd="logic1" name="true"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ T  /~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="true"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      T /\ a  /~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="exists"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="neq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMS cd="logic1" name="true"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="TrueZeroAnd" buggy="false" rewriterule="true">
    <description>
      TrueZeroAnd
    </description>
    <CMP>
      T /\ a  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMS cd="logic1" name="true"/>
              <OMV name="$0"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a /\ T  ~&gt;  a
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="and"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="true"/>
            </OMA>
            <OMV name="$0"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
  <rule name="TrueZeroOr" buggy="false" rewriterule="true">
    <description>
      TrueZeroOr
    </description>
    <CMP>
      T || a  ~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMS cd="logic1" name="true"/>
              <OMV name="$0"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
    <CMP>
      a || T  ~&gt;  T
    </CMP>
    <FMP>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMBIND>
          <OMS cd="quant1" name="forall"/>
          <OMBVAR>
            <OMV name="$0"/>
          </OMBVAR>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMA>
              <OMS cd="logic1" name="or"/>
              <OMV name="$0"/>
              <OMS cd="logic1" name="true"/>
            </OMA>
            <OMS cd="logic1" name="true"/>
          </OMA>
        </OMBIND>
      </OMOBJ>
    </FMP>
  </rule>
</reply>

