<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem name="abc formula" buggy="false" rewriterule="false"/>
    <elem name="abc misconception minus 4ac" buggy="true" rewriterule="false"/>
    <elem name="abc misconception minus b" buggy="true" rewriterule="false"/>
    <elem name="abc misconception one solution" buggy="true" rewriterule="false"/>
    <elem name="abc misconception two a" buggy="true" rewriterule="false"/>
    <elem name="approximate" buggy="false" rewriterule="false"/>
    <elem name="bring a to one" buggy="false" rewriterule="false"/>
    <elem name="buggy cancel minus" buggy="true" rewriterule="false"/>
    <elem name="buggy cover-up even power" buggy="true" rewriterule="false"/>
    <elem name="buggy cover-up even power forget" buggy="true" rewriterule="false"/>
    <elem name="buggy cover-up even power too early" buggy="true" rewriterule="false"/>
    <elem name="buggy cover-up square minus" buggy="true" rewriterule="false"/>
    <elem name="buggy cover-up times mul" buggy="true" rewriterule="false"/>
    <elem name="buggy cover-up times with plus" buggy="true" rewriterule="false"/>
    <elem name="buggy distr times denom" buggy="true" rewriterule="false"/>
    <elem name="buggy distr times plus" buggy="true" rewriterule="false"/>
    <elem name="buggy distr times plus forget" buggy="true" rewriterule="false"/>
    <elem name="buggy distr times plus sign" buggy="true" rewriterule="false"/>
    <elem name="buggy distr times too many" buggy="true" rewriterule="false"/>
    <elem name="buggy distribution square" buggy="true" rewriterule="true"/>
    <elem name="buggy distribution square forget" buggy="true" rewriterule="true"/>
    <elem name="buggy divide negate" buggy="true" rewriterule="false"/>
    <elem name="buggy divide numdenom" buggy="true" rewriterule="false"/>
    <elem name="buggy division by var both" buggy="true" rewriterule="false"/>
    <elem name="buggy division by var zero" buggy="true" rewriterule="false"/>
    <elem name="buggy flip negate one side" buggy="true" rewriterule="false"/>
    <elem name="buggy minus minus" buggy="true" rewriterule="false"/>
    <elem name="buggy multiply forget one" buggy="true" rewriterule="false"/>
    <elem name="buggy multiply one side" buggy="true" rewriterule="false"/>
    <elem name="buggy negate all" buggy="true" rewriterule="false"/>
    <elem name="buggy negate one side" buggy="true" rewriterule="false"/>
    <elem name="buggy plus" buggy="true" rewriterule="false"/>
    <elem name="buggy priority times" buggy="true" rewriterule="false"/>
    <elem name="buggy square multiplication" buggy="true" rewriterule="true"/>
    <elem name="cancel terms" buggy="false" rewriterule="false"/>
    <elem name="common factor var" buggy="false" rewriterule="false"/>
    <elem name="cover-up minus left [one var]" buggy="false" rewriterule="false"/>
    <elem name="cover-up minus right [one var]" buggy="false" rewriterule="false"/>
    <elem name="cover-up negate [vars]" buggy="false" rewriterule="false"/>
    <elem name="cover-up numerator [vars]" buggy="false" rewriterule="false"/>
    <elem name="cover-up plus [one var]" buggy="false" rewriterule="false"/>
    <elem name="cover-up power [vars]" buggy="false" rewriterule="false"/>
    <elem name="cover-up times [vars]" buggy="false" rewriterule="false"/>
    <elem name="distribution division" buggy="false" rewriterule="false"/>
    <elem name="distribution multiplication" buggy="false" rewriterule="false"/>
    <elem name="distribution square" buggy="false" rewriterule="true"/>
    <elem name="factor left as square" buggy="false" rewriterule="false"/>
    <elem name="flip equation" buggy="false" rewriterule="true"/>
    <elem name="merge similar terms" buggy="false" rewriterule="false"/>
    <elem name="move to left" buggy="false" rewriterule="false"/>
    <elem name="multiplication is zero" buggy="false" rewriterule="false"/>
    <elem name="nice factors" buggy="false" rewriterule="false"/>
    <elem name="no linear term b" buggy="false" rewriterule="false"/>
    <elem name="prepare split square" buggy="false" rewriterule="false"/>
    <elem name="same constant factor" buggy="false" rewriterule="false"/>
    <elem name="same factor" buggy="false" rewriterule="false"/>
    <elem name="simpler polynomial" buggy="false" rewriterule="false"/>
    <elem name="simpler square root" buggy="false" rewriterule="false"/>
    <elem name="square both sides" buggy="false" rewriterule="true"/>
  </list>
</reply>

