<reply result="ok" version="0.6.2 (0)">
  <label name="Linear Equation">
    <sequence>
      <rule name="Identity"/>
      <label name="Phase 1">
        <repeat>
          <choice>
            <rule name="remove division"/>
            <label name="distribution multiplication" collapsed="true">
              <sequence>
                <rec var="0">
                  <choice>
                    <sequence>
                      <rule name="parent not negate check"/>
                      <rule name="distribution multiplication"/>
                    </sequence>
                    <sequence>
                      <rule name="MoveDown"/>
                      <var var="0"/>
                      <rule name="MoveUp"/>
                    </sequence>
                  </choice>
                </rec>
                <repeat>
                  <rec var="0">
                    <choice>
                      <sequence>
                        <rule name="parent not negate check"/>
                        <rule name="distribution multiplication"/>
                      </sequence>
                      <sequence>
                        <rule name="MoveDown"/>
                        <var var="0"/>
                        <rule name="MoveUp"/>
                      </sequence>
                    </choice>
                  </rec>
                </repeat>
              </sequence>
            </label>
            <label name="merge similar terms" collapsed="true">
              <sequence>
                <rule name="MoveDown"/>
                <rule name="merge similar terms"/>
                <rule name="MoveUp"/>
                <repeat>
                  <sequence>
                    <rule name="MoveDown"/>
                    <rule name="merge similar terms"/>
                    <rule name="MoveUp"/>
                  </sequence>
                </repeat>
              </sequence>
            </label>
          </choice>
        </repeat>
      </label>
      <label name="Phase 2">
        <repeat>
          <choice>
            <orelse>
              <rule name="flip equation"/>
              <rule name="variable to left"/>
            </orelse>
            <rule name="cover-up plus [one var]"/>
            <rule name="cover-up minus left [one var]"/>
            <rule name="cover-up minus right [one var]"/>
            <rule name="cover-up times [vars]"/>
            <rule name="cover-up negate [vars]"/>
          </choice>
        </repeat>
      </label>
      <repeat>
        <sequence>
          <rule name="MoveDown"/>
          <choice>
            <rule name="normalize rational number"/>
            <rule name="normalize mixed fraction" removed="true"/>
          </choice>
          <rule name="MoveUp"/>
        </sequence>
      </repeat>
    </sequence>
  </label>
</reply>

