<reply result="ok" version="1.0.5 (0)">
  <label name="linearequation">
    <sequence>
      <label name="phase1">
        <repeat>
          <choice>
            <rule name="algebra.equations.linear.remove-div"/>
            <label name="algebra.equations.linear.distr-times" collapsed="true">
              <sequence>
                <rec var="1">
                  <orelse>
                    <rule name="algebra.equations.linear.distr-times"/>
                    <sequence>
                      <rule name="navigator.down"/>
                      <rec var="2">
                        <choice>
                          <var var="1"/>
                          <sequence>
                            <rule name="navigator.right"/>
                            <var var="2"/>
                          </sequence>
                        </choice>
                      </rec>
                      <orelse>
                        <rule name="navigator.up"/>
                        <succeed/>
                      </orelse>
                    </sequence>
                  </orelse>
                </rec>
                <repeat>
                  <rec var="1">
                    <orelse>
                      <rule name="algebra.equations.linear.distr-times"/>
                      <sequence>
                        <rule name="navigator.down"/>
                        <rec var="2">
                          <choice>
                            <var var="1"/>
                            <sequence>
                              <rule name="navigator.right"/>
                              <var var="2"/>
                            </sequence>
                          </choice>
                        </rec>
                        <orelse>
                          <rule name="navigator.up"/>
                          <succeed/>
                        </orelse>
                      </sequence>
                    </orelse>
                  </rec>
                </repeat>
              </sequence>
            </label>
            <label name="algebra.equations.linear.merge" collapsed="true">
              <sequence>
                <rule name="navigator.down"/>
                <rec var="0">
                  <choice>
                    <rule name="algebra.equations.linear.merge"/>
                    <sequence>
                      <rule name="navigator.right"/>
                      <var var="0"/>
                    </sequence>
                  </choice>
                </rec>
                <orelse>
                  <rule name="navigator.up"/>
                  <succeed/>
                </orelse>
                <repeat>
                  <sequence>
                    <rule name="navigator.down"/>
                    <rec var="0">
                      <choice>
                        <rule name="algebra.equations.linear.merge"/>
                        <sequence>
                          <rule name="navigator.right"/>
                          <var var="0"/>
                        </sequence>
                      </choice>
                    </rec>
                    <orelse>
                      <rule name="navigator.up"/>
                      <succeed/>
                    </orelse>
                  </sequence>
                </repeat>
              </sequence>
            </label>
          </choice>
        </repeat>
      </label>
      <label name="phase2">
        <repeat>
          <choice>
            <orelse>
              <sequence>
                <rule name="check"/>
                <rule name="algebra.equations.linear.flip"/>
              </sequence>
              <rule name="algebra.equations.linear.var-left"/>
            </orelse>
            <rule name="algebra.equations.coverup.onevar.plus"/>
            <rule name="algebra.equations.coverup.onevar.minus-left"/>
            <rule name="algebra.equations.coverup.onevar.minus-right"/>
            <rule name="algebra.equations.coverup.times"/>
            <rule name="algebra.equations.coverup.negate"/>
          </choice>
        </repeat>
      </label>
      <repeat>
        <sequence>
          <rule name="navigator.down"/>
          <rec var="0">
            <choice>
              <rule name="algebra.equations.linear.norm-rational"/>
              <rule name="algebra.equations.linear.norm-mixed" removed="true"/>
              <sequence>
                <rule name="navigator.right"/>
                <var var="0"/>
              </sequence>
            </choice>
          </rec>
          <orelse>
            <rule name="navigator.up"/>
            <succeed/>
          </orelse>
        </sequence>
      </repeat>
    </sequence>
  </label>
</reply>

