<reply result="ok" version="0.6.6 (3605)">
  <list>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        3^(2*x+1) == 27
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.factor-as-power">
      <expr>
        3^(2*x+1) == 3^3
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.same-base">
      <expr>
        2*x+1 == 3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        2*x == 2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 1
      </expr>
    </elem>
  </list>
</reply>

