<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.factor-as-power">
      <expr>
        3^(x-1) == 3^4
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.same-base">
      <expr>
        x-1 == 4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 5
      </expr>
    </elem>
  </list>
</reply>

