<reply result="ok" version="0.6.7 (3710)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        5^(x-4) == (5^(-1))^(2*x+1)
      </expr>
      <context>
        <item name="location" value="[2,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        5^(x-4) == 5^(-2*x-1)
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.same-base">
      <expr>
        x-4 == -2*x-1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        3*x-4 == -1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        3*x == 3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 1
      </expr>
    </elem>
  </list>
</reply>

