<reply result="ok" version="0.6.7 (3710)">
  <list>
    <elem ruleid="algebra.equations.coverup.plus">
      <expr>
        5*2^(1-4*x) == 40
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        2^(1-4*x) == 8
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.factor-as-power">
      <expr>
        2^(1-4*x) == 2^3
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.same-base">
      <expr>
        1-4*x == 3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        4*x == -2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -1/2
      </expr>
    </elem>
  </list>
</reply>

