<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.factor-as-power">
      <expr>
        3^(2*x) == 1/3^2
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        3^(2*x) == (3^2)^(-1)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        3^(2*x) == 3^(-2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.same-base">
      <expr>
        2*x == -2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -1
      </expr>
    </elem>
  </list>
</reply>

