<reply result="ok" version="0.6.5 (3574)">
  <list>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        5^(2-x) == 25
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.factor-as-power">
      <expr>
        5^(2-x) == 5^2
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.same-base">
      <expr>
        2-x == 2
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.var-left-con-right">
      <expr>
        -x == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.negate">
      <expr>
        x == 0
      </expr>
    </elem>
  </list>
</reply>

