<reply result="ok" version="0.6.5 (3574)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.equals-one">
      <expr>
        1-2*x == 0
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.var-left-con-right">
      <expr>
        -2*x == -1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.negate">
      <expr>
        2*x == 1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 1/2
      </expr>
    </elem>
  </list>
</reply>

