<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        2^(x-1) == 4*sqrt 2
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.factor-as-power">
      <expr>
        2^(x-1) == 2^2*sqrt 2
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-power">
      <expr>
        2^(x-1) == 2^2*2^(1/2)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        2^(x-1) == 2^(5/2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.same-base">
      <expr>
        x-1 == 5/2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 7/2
      </expr>
    </elem>
  </list>
</reply>

