<reply result="ok" version="0.6.5 (3574)">
  <list>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        9^(1-2*x) == 3*sqrt 3
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.factor-as-power">
      <expr>
        (3^2)^(1-2*x) == 3*sqrt 3
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        3^(2*(1-2*x)) == 3*sqrt 3
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-power-generic">
      <expr>
        3^(2*(1-2*x)) == 3*3^(1/2)
      </expr>
      <context>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents-generic">
      <expr>
        3^(2*(1-2*x)) == 3^(3/2)
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.same-base">
      <expr>
        2*(1-2*x) == 3/2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        1-2*x == 3/4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.minus-right">
      <expr>
        2*x == 1/4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 1/8
      </expr>
    </elem>
  </list>
</reply>

