<reply result="ok" version="0.6.6 (3605)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-for-base">
      <expr>
        5^(x-4) == 5^(-2*x-1)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.same-base">
      <expr>
        x-4 == -2*x-1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        3*x-4 == -1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        3*x == 3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 1
      </expr>
    </elem>
  </list>
</reply>

