<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        3^(5-2*x) == 9*sqrt 3
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.factor-as-power">
      <expr>
        3^(5-2*x) == 3^2*sqrt 3
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-power">
      <expr>
        3^(5-2*x) == 3^2*3^(1/2)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        3^(5-2*x) == 3^(5/2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.same-base">
      <expr>
        5-2*x == 5/2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        2*x == 5/2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 5/4
      </expr>
    </elem>
  </list>
</reply>

