<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.factor-as-power">
      <expr>
        5^(2-x) == 1/5^2
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        5^(2-x) == (5^2)^(-1)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        5^(2-x) == 5^(-2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.same-base">
      <expr>
        2-x == -2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        x == 4
      </expr>
    </elem>
  </list>
</reply>

