<reply result="ok" version="0.6.5 (3574)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.factor-as-power">
      <expr>
        3^(1-3*x) == 3^4
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.same-base">
      <expr>
        1-3*x == 4
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.var-left-con-right">
      <expr>
        -3*x == 3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.negate">
      <expr>
        3*x == -3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -1
      </expr>
    </elem>
  </list>
</reply>

