<reply result="ok" version="0.6.7 (3710)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.write-as-power">
      <expr>
        3^(3*x-2) == 3*3^(1/2)
      </expr>
      <context>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.simple-add-exponents">
      <expr>
        3^(3*x-2) == 3^(3/2)
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.same-base">
      <expr>
        3*x-2 == 3/2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        3*x == 7/2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 7/6
      </expr>
    </elem>
  </list>
</reply>

