<reply result="ok" version="0.6.5 (3574)">
  <list>
    <elem ruleid="algebra.equations.coverup.plus">
      <expr>
        5*2^(1-4*x) == 40
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        2^(1-4*x) == 8
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.factor-as-power">
      <expr>
        2^(1-2^2*x) == 8
      </expr>
      <context>
        <item name="location" value="[1,2,2,1]"/>
      </context>
    </elem>
  </list>
</reply>

