<reply result="ok" version="0.6.5 (3536)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        3/a^(3/5)*b^(1/3)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-root">
      <expr>
        3/root (a^3) 5*b^(1/3)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-root">
      <expr>
        3/root (a^3) 5*root b 3
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        3*root b 3/root (a^3) 5
      </expr>
    </elem>
  </list>
</reply>

