<reply result="ok" version="0.6.5 (3536)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        2/(3*a)^(1/4)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-root">
      <expr>
        2/root (3*a) 4
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

