<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        1/(6*a)^(2/5)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-root">
      <expr>
        1/root ((6*a)^2) 5
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        1/root (36*a^2) 5
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
  </list>
</reply>

