<reply result="ok" version="0.6.7 (3637)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        1/((2*a)^3*b^2)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        1/(8*a^3*b^2)
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
  </list>
</reply>

