<reply result="ok" version="0.6.2 (3188)">
  <list>
    <elem ruleid="reciprocal fraction">
      <expr>
        (a*b)^2*a*b^(-1)
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="reciprocal">
      <expr>
        (a*b)^2*a/b
      </expr>
    </elem>
    <elem ruleid="distribute power">
      <expr>
        a^2*b^2*a/b
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        a^3*b^2/b
      </expr>
    </elem>
    <elem ruleid="sub exponents">
      <expr>
        a^3*b
      </expr>
    </elem>
  </list>
</reply>

