<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        (4*a)^(-3)*7/b^5
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        1/(4*a)^3*7/b^5
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        1/(64*a^3)*7/b^5
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        7/(64*a^3)/b^5
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.division-numerator">
      <expr>
        7/(64*a^3*b^5)
      </expr>
    </elem>
  </list>
</reply>

