<reply result="ok" version="0.6.7 (3637)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.write-as-root">
      <expr>
        root ((3*a)^2) 5
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        root (9*a^2) 5
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        root 9 5*root (a^2) 5
      </expr>
    </elem>
  </list>
</reply>

