<reply result="ok" version="0.6.2 (3229)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        1/(5/6*a)^2
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        1/(25*(1/36)*a^2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        1/(25/36*a^2)
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        1/(25*a^2/36)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.division-denominator">
      <expr>
        36/(25*a^2)
      </expr>
    </elem>
  </list>
</reply>

