<reply result="ok" version="0.6.5 (3536)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        1/(7*a^(1/4))*b^(2/3)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-root">
      <expr>
        1/(7*root a 4)*b^(2/3)
      </expr>
      <context>
        <item name="location" value="[0,1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-root">
      <expr>
        1/(7*root a 4)*root (b^2) 3
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        root (b^2) 3/(7*root a 4)
      </expr>
    </elem>
  </list>
</reply>

