<reply result="ok" version="0.7.9 (0)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        (4*a*b)^(-1)*b^(-6)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        b^(-6)/(4*a*b)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        1/(b^6*4*a*b)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        1/(4*b^7*a)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

