<reply result="ok" version="0.6.7 (3637)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        1/(a^3*b^(-3))
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        b^3/a^3
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
  </list>
</reply>

