<reply result="ok" version="0.6.5 (3536)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        1/a^(-3)*b^(-4)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-frac">
      <expr>
        a^3*b^(-4)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        a^3/b^4
      </expr>
    </elem>
  </list>
</reply>

