<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        (5*a)^(-2)*10/b
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        1/(5*a)^2*10/b
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        1/(25*a^2)*10/b
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        2/(5*a^2)/b
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.division-numerator">
      <expr>
        2/(5*a^2*b)
      </expr>
    </elem>
  </list>
</reply>

