<reply result="ok" version="0.6.2 (3188)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-frac">
      <expr>
        a^(-1)*b^(2/3)/8
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        1/a*b^(2/3)/8
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-root">
      <expr>
        1/a*root (b^2) 3/8
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        root (b^2) 3/a/8
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.division-numerator">
      <expr>
        root (b^2) 3/(a*8)
      </expr>
    </elem>
  </list>
</reply>

