<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        4*a^(-2)/(3*b)^2
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        4/a^2/(3*b)^2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        4/a^2/(9*b^2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.division-numerator">
      <expr>
        4/(9*a^2*b^2)
      </expr>
    </elem>
  </list>
</reply>

