<reply result="ok" version="0.6.2 (3229)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-frac">
      <expr>
        (2*a)^(-1)*(4*b)^2
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        1/(2*a)*(4*b)^2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        1/(2*a)*16*b^2
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        8/a*b^2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        8*b^2/a
      </expr>
    </elem>
  </list>
</reply>

