<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        3*a^(1/4)/b^(1/2)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-root">
      <expr>
        3*root a 4/b^(1/2)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-root">
      <expr>
        3*root a 4/sqrt b
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

