<reply result="ok" version="0.6.2 (3229)">
  <list>
    <elem ruleid="reciprocal">
      <expr>
        1/(3/4*a)^2
      </expr>
    </elem>
    <elem ruleid="distribute power">
      <expr>
        1/(9*(1/16)*a^2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="fraction times">
      <expr>
        1/(9/16*a^2)
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
    <elem ruleid="fraction times">
      <expr>
        1/(9*a^2/16)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="division denominator">
      <expr>
        16/(9*a^2)
      </expr>
    </elem>
  </list>
</reply>

