<reply result="ok" version="0.6.2 (3229)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        1/(2/5*a)^3
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        1/(8*(1/125)*a^3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        1/(8/125*a^3)
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        1/(8*a^3/125)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.division-denominator">
      <expr>
        125/(8*a^3)
      </expr>
    </elem>
  </list>
</reply>

