<reply result="ok" version="0.6.5 (3536)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        1/(2/3*a)^3
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        1/(8*(1/27)*a^3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        1/(8/27*a^3)
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.fraction-times">
      <expr>
        1/(8*a^3/27)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.division-denominator">
      <expr>
        27/(8*a^3)
      </expr>
    </elem>
  </list>
</reply>

