<reply result="ok" version="0.6.5 (3536)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        9*a^(-7)/(2*b)^4
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        9/a^7/(2*b)^4
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        9/a^7/(16*b^4)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.division-numerator">
      <expr>
        9/(16*a^7*b^4)
      </expr>
    </elem>
  </list>
</reply>

