{
   "result": [
      [
         "absorpornot.distr",
         [
         ],
         "~((p || ~p) /\\ (p || q)) == ~(p || q)"
      ],
      [
         "logic.propositional.complor",
         [
         ],
         "~(T /\\ (p || q)) == ~(p || q)"
      ],
      [
         "logic.propositional.truezeroand",
         [
         ],
         "~(p || q) == ~(p || q)"
      ],
      [
         "top-is-or.com",
         [
         ],
         "~(p || q) == ~(p || q)"
      ]
   ],
   "error": null,
   "id": 42,
   "version": "1.0.11 (0)"
}
