{
   "result": [
      [
         "logic.propositional.defimpl",
         [
         ],
         "~p || q || (q -> p) == T"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "~p || q || ~q || p == T"
      ],
      [
         "logic.propositional.complor",
         [
         ],
         "~p || T || p == T"
      ],
      [
         "logic.propositional.truezeroor",
         [
         ],
         "~p || T == T"
      ],
      [
         "logic.propositional.truezeroor",
         [
         ],
         "T == T"
      ]
   ],
   "error": null,
   "id": 42,
   "version": "1.0.9 (0)"
}
