{
   "result": [
      [
         "logic.propositional.defimpl",
         [
         ],
         "~(p /\\ q) || p == T"
      ],
      [
         "logic.propositional.demorganand",
         [
         ],
         "~p || ~q || p == T"
      ],
      [
         "fakeabsorption",
         [
         ],
         "T || ~q || p == T"
      ],
      [
         "logic.propositional.truezeroor",
         [
         ],
         "T == T"
      ]
   ],
   "error": null,
   "id": 42,
   "version": "1.0.9 (0)"
}
