{
   "result": [
      [
         "idempotency-and.sort",
         [
         ],
         "(q -> (~p -> q)) -> p == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "~(q -> (~p -> q)) || p == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "~(~q || (~p -> q)) || p == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "~(~q || ~~p || q) || p == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "~(~q || p || q) || p == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "logic.propositional.demorganor",
         [
         ],
         "(~~q /\\ ~(p || q)) || p == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "(q /\\ ~(p || q)) || p == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "logic.propositional.demorganor",
         [
         ],
         "(q /\\ ~p /\\ ~q) || p == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "contradiction-and.sort",
         [
         ],
         "(~p /\\ q /\\ ~q) || p == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "absorpornot.distr",
         [
         ],
         "(~p || p) /\\ ((q /\\ ~q) || p) == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "fakeabsorption",
         [
         ],
         "(T || p) /\\ ((q /\\ ~q) || p) == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "logic.propositional.compland",
         [
         ],
         "(T || p) /\\ (F || p) == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "logic.propositional.falsezeroor",
         [
         ],
         "(T || p) /\\ p == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "logic.propositional.absorpand",
         [
         ],
         "p == ~p -> (p /\\ q /\\ q /\\ q)"
      ],
      [
         "logic.propositional.idempand",
         [
         ],
         "p == ~p -> (p /\\ q /\\ q)"
      ],
      [
         "logic.propositional.idempand",
         [
         ],
         "p == ~p -> (p /\\ q)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "p == ~~p || (p /\\ q)"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "p == p || (p /\\ q)"
      ],
      [
         "logic.propositional.absorpor",
         [
         ],
         "p == p"
      ]
   ],
   "error": null,
   "id": 42,
   "version": "1.0.11 (0)"
}
