{
   "result": [
      [
         "top-is-impl",
         [
         ],
         "(p -> q) -> (p -> s) == (~q -> ~p) -> (~s -> ~p)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "(~p || q) -> (p -> s) == (~q -> ~p) -> (~s -> ~p)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "(~p || q) -> (p -> s) == (~~q || ~p) -> (~s -> ~p)"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "(~p || q) -> (p -> s) == (q || ~p) -> (~s -> ~p)"
      ],
      [
         "top-is-or",
         [
         ],
         "(~p || q) -> (p -> s) == (~p || q) -> (~s -> ~p)"
      ],
      [
         "top-is-not",
         [
         ],
         "(~p || q) -> (p -> s) == (~p || q) -> (~s -> ~p)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "(~p || q) -> (~p || s) == (~p || q) -> (~s -> ~p)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "(~p || q) -> (~p || s) == (~p || q) -> (~~s || ~p)"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "(~p || q) -> (~p || s) == (~p || q) -> (s || ~p)"
      ],
      [
         "top-is-or",
         [
         ],
         "(~p || q) -> (~p || s) == (~p || q) -> (~p || s)"
      ],
      [
         "top-is-not",
         [
         ],
         "(~p || q) -> (~p || s) == (~p || q) -> (~p || s)"
      ]
   ],
   "error": null,
   "id": 42,
   "version": "1.0.9 (0)"
}
