{
   "result": [
      [
         "logic.propositional.demorganor",
         [
         ],
         "~(p || (~p /\\ ~~q)) == ~(p || q)"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "~(p || (~p /\\ q)) == ~(p || q)"
      ],
      [
         "fakeabsorption",
         [
         ],
         "~(p || q) == ~(p || q)"
      ]
   ],
   "error": null,
   "id": 42,
   "version": "1.0.10 (0)"
}
