{
   "result": [
      [
         "top-is-not",
         [
         ],
         "~(p || ~(p || ~q)) == ~(p || q)"
      ],
      [
         "logic.propositional.demorganor",
         [
         ],
         "~(p || (~p /\\ ~~q)) == ~(p || q)"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "~(p || (~p /\\ q)) == ~(p || q)"
      ],
      [
         "fakeabsorption",
         [
         ],
         "~(p || q) == ~(p || q)"
      ],
      [
         "top-is-or",
         [
         ],
         "~(p || q) == ~(p || q)"
      ]
   ],
   "error": null,
   "id": 42,
   "version": "1.0.9 (0)"
}
