{
   "result": [
      [
         "logic.propositional.defimpl",
         [
         ],
         "~p || (q -> r) == (p -> q) -> (p -> r)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "~p || ~q || r == (p -> q) -> (p -> r)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "~p || ~q || r == ~(p -> q) || (p -> r)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "~p || ~q || r == ~(~p || q) || (p -> r)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "~p || ~q || r == ~(~p || q) || ~p || r"
      ],
      [
         "logic.propositional.demorganor",
         [
         ],
         "~p || ~q || r == (~~p /\\ ~q) || ~p || r"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "~p || ~q || r == (p /\\ ~q) || ~p || r"
      ],
      [
         "fakeabsorptionnot",
         [
         ],
         "~p || ~q || r == ~q || ~p || r"
      ],
      [
         "normalize",
         [
         ],
         "(~p /\\ ~q /\\ ~r) || (~p /\\ ~q /\\ r) || (~p /\\ q /\\ ~r) || (~p /\\ q /\\ r) || (p /\\ ~q /\\ ~r) || (p /\\ ~q /\\ r) || (p /\\ q /\\ r) == (~p /\\ ~q /\\ ~r) || (~p /\\ ~q /\\ r) || (~p /\\ q /\\ ~r) || (~p /\\ q /\\ r) || (p /\\ ~q /\\ ~r) || (p /\\ ~q /\\ r) || (p /\\ q /\\ r)"
      ]
   ],
   "error": null,
   "id": 42,
   "version": "1.0.10 (0)"
}
