{
   "result": [
      [
         "commonexpratom",
         [
         ],
         "~(a -> (p /\\ q)) == a /\\ (~p || ~q)"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "~(a -> (p /\\ q)) == (a /\\ ~p) || (a /\\ ~q)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "~(~a || (p /\\ q)) == (a /\\ ~p) || (a /\\ ~q)"
      ],
      [
         "logic.propositional.demorganor",
         [
         ],
         "~~a /\\ ~(p /\\ q) == (a /\\ ~p) || (a /\\ ~q)"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "a /\\ ~(p /\\ q) == (a /\\ ~p) || (a /\\ ~q)"
      ],
      [
         "logic.propositional.demorganand",
         [
         ],
         "a /\\ (~p || ~q) == (a /\\ ~p) || (a /\\ ~q)"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(a /\\ ~p) || (a /\\ ~q) == (a /\\ ~p) || (a /\\ ~q)"
      ],
      [
         "top-is-or",
         [
         ],
         "(a /\\ ~p) || (a /\\ ~q) == (a /\\ ~p) || (a /\\ ~q)"
      ],
      [
         "top-is-and",
         [
         ],
         "(a /\\ ~p) || (a /\\ ~q) == (a /\\ ~p) || (a /\\ ~q)"
      ],
      [
         "top-is-and",
         [
         ],
         "(a /\\ ~p) || (a /\\ ~q) == (a /\\ ~p) || (a /\\ ~q)"
      ],
      [
         "top-is-not",
         [
         ],
         "(a /\\ ~p) || (a /\\ ~q) == (a /\\ ~p) || (a /\\ ~q)"
      ],
      [
         "top-is-not",
         [
         ],
         "(a /\\ ~p) || (a /\\ ~q) == (a /\\ ~p) || (a /\\ ~q)"
      ]
   ],
   "error": null,
   "id": 42,
   "version": "1.0.9 (0)"
}
