{
   "result": [
      [
         "logic.propositional.defequiv",
         [
         ],
         "(p /\\ q) || (~p /\\ ~q) == (p -> q) /\\ (q -> p)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "(p /\\ q) || (~p /\\ ~q) == (~p || q) /\\ (q -> p)"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "(p /\\ q) || (~p /\\ ~q) == (~p || q) /\\ (~q || p)"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(p /\\ q) || (~p /\\ ~q) == ((~p || q) /\\ ~q) || ((~p || q) /\\ p)"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(p /\\ q) || (~p /\\ ~q) == (~p /\\ ~q) || (q /\\ ~q) || ((~p || q) /\\ p)"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(p /\\ q) || (~p /\\ ~q) == (~p /\\ ~q) || (q /\\ ~q) || (~p /\\ p) || (q /\\ p)"
      ],
      [
         "logic.propositional.compland",
         [
         ],
         "(p /\\ q) || (~p /\\ ~q) == (~p /\\ ~q) || F || (~p /\\ p) || (q /\\ p)"
      ],
      [
         "logic.propositional.compland",
         [
         ],
         "(p /\\ q) || (~p /\\ ~q) == (~p /\\ ~q) || F || F || (q /\\ p)"
      ],
      [
         "logic.propositional.falsezeroor",
         [
         ],
         "(p /\\ q) || (~p /\\ ~q) == (~p /\\ ~q) || F || (q /\\ p)"
      ],
      [
         "logic.propositional.falsezeroor",
         [
         ],
         "(p /\\ q) || (~p /\\ ~q) == (~p /\\ ~q) || (q /\\ p)"
      ],
      [
         "normalize",
         [
         ],
         "(~a /\\ p /\\ q) || (a /\\ ~p /\\ ~q) || (a /\\ ~p /\\ q) || (a /\\ p /\\ ~q) || (a /\\ p /\\ q) == (~a /\\ p /\\ q) || (a /\\ ~p /\\ ~q) || (a /\\ ~p /\\ q) || (a /\\ p /\\ ~q) || (a /\\ p /\\ q)"
      ]
   ],
   "error": null,
   "id": 42,
   "version": "1.0.10 (0)"
}
