{
   "result": [
      [
         "logic.propositional.defequiv",
         [
         ],
         "~(((p /\\ q) || (~p /\\ ~q)) -> (p || (p <-> q))) == F"
      ],
      [
         "logic.propositional.defequiv",
         [
         ],
         "~(((p /\\ q) || (~p /\\ ~q)) -> (p || (p /\\ q) || (~p /\\ ~q))) == F"
      ],
      [
         "logic.propositional.absorpor",
         [
         ],
         "~(((p /\\ q) || (~p /\\ ~q)) -> (p || (~p /\\ ~q))) == F"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "~(~((p /\\ q) || (~p /\\ ~q)) || p || (~p /\\ ~q)) == F"
      ],
      [
         "logic.propositional.demorganor",
         [
         ],
         "~~((p /\\ q) || (~p /\\ ~q)) /\\ ~(p || (~p /\\ ~q)) == F"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "((p /\\ q) || (~p /\\ ~q)) /\\ ~(p || (~p /\\ ~q)) == F"
      ],
      [
         "logic.propositional.demorganor",
         [
         ],
         "((p /\\ q) || (~p /\\ ~q)) /\\ ~p /\\ ~(~p /\\ ~q) == F"
      ],
      [
         "logic.propositional.demorganand",
         [
         ],
         "((p /\\ q) || (~p /\\ ~q)) /\\ ~p /\\ (~~p || ~~q) == F"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "((p /\\ q) || (~p /\\ ~q)) /\\ ~p /\\ (p || ~~q) == F"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "((p /\\ q) || (~p /\\ ~q)) /\\ ~p /\\ (p || q) == F"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(((p /\\ q) || (~p /\\ ~q)) /\\ ~p /\\ p) || (((p /\\ q) || (~p /\\ ~q)) /\\ ~p /\\ q) == F"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(((p /\\ q) || (~p /\\ ~q)) /\\ ~p /\\ p) || (p /\\ q /\\ ~p /\\ q) || (~p /\\ ~q /\\ ~p /\\ q) == F"
      ],
      [
         "logic.propositional.compland",
         [
         ],
         "(((p /\\ q) || (~p /\\ ~q)) /\\ F) || (p /\\ q /\\ ~p /\\ q) || (~p /\\ ~q /\\ ~p /\\ q) == F"
      ],
      [
         "logic.propositional.falsezeroand",
         [
         ],
         "F || (p /\\ q /\\ ~p /\\ q) || (~p /\\ ~q /\\ ~p /\\ q) == F"
      ],
      [
         "logic.propositional.falsezeroor",
         [
         ],
         "(p /\\ q /\\ ~p /\\ q) || (~p /\\ ~q /\\ ~p /\\ q) == F"
      ],
      [
         "contradiction-and.sort",
         [
         ],
         "(p /\\ ~p /\\ q /\\ q) || (~p /\\ ~q /\\ ~p /\\ q) == F"
      ],
      [
         "contradiction-and.sort",
         [
         ],
         "(p /\\ ~p /\\ q /\\ q) || (~p /\\ ~p /\\ q /\\ ~q) == F"
      ],
      [
         "logic.propositional.compland",
         [
         ],
         "(F /\\ q /\\ q) || (~p /\\ ~p /\\ q /\\ ~q) == F"
      ],
      [
         "commor.sort",
         [
         ],
         "(~p /\\ ~p /\\ q /\\ ~q) || (F /\\ q /\\ q) == F"
      ],
      [
         "logic.propositional.compland",
         [
         ],
         "(~p /\\ ~p /\\ F) || (F /\\ q /\\ q) == F"
      ],
      [
         "command.sort",
         [
         ],
         "(F /\\ ~p /\\ ~p) || (F /\\ q /\\ q) == F"
      ],
      [
         "logic.propositional.falsezeroand",
         [
         ],
         "F || (F /\\ q /\\ q) == F"
      ],
      [
         "logic.propositional.falsezeroand",
         [
         ],
         "F || F == F"
      ],
      [
         "logic.propositional.falsezeroor",
         [
         ],
         "F == F"
      ]
   ],
   "error": null,
   "id": 42,
   "version": "1.0.11 (0)"
}
