{
   "result": [
      [
         "top-is-impl",
         [
         ],
         "p -> q == ~q -> ~p, p -> s == ~s -> ~p"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "~p || q == ~q -> ~p, p -> s == ~s -> ~p"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "~p || q == ~~q || ~p, p -> s == ~s -> ~p"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "~p || q == q || ~p, p -> s == ~s -> ~p"
      ],
      [
         "top-is-or",
         [
         ],
         "~p == ~p, q == q, p -> s == ~s -> ~p"
      ],
      [
         "top-is-not",
         [
         ],
         "p == p, q == q, p -> s == ~s -> ~p"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "p == p, q == q, ~p || s == ~s -> ~p"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "p == p, q == q, ~p || s == ~~s || ~p"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "p == p, q == q, ~p || s == s || ~p"
      ],
      [
         "top-is-or",
         [
         ],
         "p == p, q == q, ~p == ~p, s == s"
      ],
      [
         "top-is-not",
         [
         ],
         "p == p, q == q, p == p, s == s"
      ]
   ],
   "error": null,
   "id": 42,
   "version": "1.0.9 (0)"
}
