<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="calculate power">
      <expr>
        1/(1/3)^4
      </expr>
    </elem>
    <elem ruleid="calculate power">
      <expr>
        1/(1/81)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="division denominator">
      <expr>
        81
      </expr>
    </elem>
  </list>
</reply>

