<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        4*(1/7^2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        4*(1/49)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.times">
      <expr>
        4/49
      </expr>
    </elem>
  </list>
</reply>

