<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        5*(1/3^2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        5*(1/9)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.times">
      <expr>
        5/9
      </expr>
    </elem>
  </list>
</reply>

