<reply result="ok" version="0.6.7 (3639)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        1/(1/7)^2
      </expr>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        1/(1/49)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.division-denominator">
      <expr>
        49
      </expr>
    </elem>
  </list>
</reply>

