<reply result="ok" version="0.6.7 (3639)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        1/(1/3)^4
      </expr>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        1/(1/81)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.division-denominator">
      <expr>
        81
      </expr>
    </elem>
  </list>
</reply>

