<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        6*(1/10^3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        6*(1/1000)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.times">
      <expr>
        3/500
      </expr>
    </elem>
  </list>
</reply>

