<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        1/(2*(1/8^2))
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        1/(2*(1/64))
      </expr>
      <context>
        <item name="location" value="[1,1,1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.times">
      <expr>
        1/(1/32)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.division-denominator">
      <expr>
        32
      </expr>
    </elem>
  </list>
</reply>

