<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="calculate power">
      <expr>
        5*(1/10^2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="calculate power">
      <expr>
        5*(1/100)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="calculate times [rational]">
      <expr>
        1/20
      </expr>
    </elem>
  </list>
</reply>

