<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="calculate power">
      <expr>
        1/(3*(1/6^2))
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="calculate power">
      <expr>
        1/(3*(1/36))
      </expr>
      <context>
        <item name="location" value="[1,1,1]"/>
      </context>
    </elem>
    <elem ruleid="calculate times [rational]">
      <expr>
        1/(1/12)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="division denominator">
      <expr>
        12
      </expr>
    </elem>
  </list>
</reply>

