<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="calculate power">
      <expr>
        4*(1/10^3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="calculate power">
      <expr>
        4*(1/1000)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="calculate times [rational]">
      <expr>
        1/250
      </expr>
    </elem>
  </list>
</reply>

