<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        6*(1/5^2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        6*(1/25)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.times">
      <expr>
        6/25
      </expr>
    </elem>
  </list>
</reply>

