<reply result="ok" version="0.6.7 (3639)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        4/7^2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        4/49
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

