<reply result="ok" version="0.6.7 (3639)">
  <list>
    <elem ruleid="algebra.manipulation.division-numerator">
      <expr>
        1/(8*4^(-2))
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-inverse">
      <expr>
        1/(8*(1/4^2))
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        1/(8*(1/16))
      </expr>
      <context>
        <item name="location" value="[1,1,1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.times">
      <expr>
        1/(1/2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.division-denominator">
      <expr>
        2
      </expr>
    </elem>
  </list>
</reply>

