<reply result="ok" version="1.0.7 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        1-2*x^5 == -485
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1-2*x^5 &lt; -485)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        2*x^5 == 486
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1-2*x^5 &lt; -485)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^5 == 243
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1-2*x^5 &lt; -485)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 3
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1-2*x^5 &lt; -485)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        x &gt; 3
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

