<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        -(1/2*x+2)^3 == -1
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (-(1/2*x+2)^3 < -1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.negate">
      <expr>
        (1/2*x+2)^3 == 1
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (-(1/2*x+2)^3 < -1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        1/2*x+2 == 1
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (-(1/2*x+2)^3 < -1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        1/2*x == -1
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (-(1/2*x+2)^3 < -1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -2
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (-(1/2*x+2)^3 < -1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        x &gt; -2
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

