<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        (2*x-3)^4 == 1
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        2*x-3 == 1 or 2*x-3 == -1
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        2*x == 4 or 2*x-3 == -1
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 2 or 2*x-3 == -1
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 2 or 2*x == 2
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 2 or x == 1
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        x &lt; 1 or x &gt; 2
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

