<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        -1/2*x^4 == -81/2
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-1/2*x^4<-81/2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^4 == 81
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-1/2*x^4<-81/2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 3 or x == -3
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-1/2*x^4<-81/2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        x &lt; -3 or x &gt; 3
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

