<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        2*x^3 == 54
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (2*x^3 > 54)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^3 == 27
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (2*x^3 > 54)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 3
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (2*x^3 > 54)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        x &gt; 3
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

