<reply result="ok" version="1.0.7 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        1/4*(1/2*x-2)^4 == 4
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1/4*(1/2*x-2)^4 &lt; 4)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (1/2*x-2)^4 == 16
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1/4*(1/2*x-2)^4 &lt; 4)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        1/2*x-2 == 2 or 1/2*x-2 == -2
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1/4*(1/2*x-2)^4 &lt; 4)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        1/2*x == 4 or 1/2*x-2 == -2
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1/4*(1/2*x-2)^4 &lt; 4)]"/>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 8 or 1/2*x-2 == -2
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1/4*(1/2*x-2)^4 &lt; 4)]"/>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 8 or 1/2*x == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1/4*(1/2*x-2)^4 &lt; 4)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 8 or x == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1/4*(1/2*x-2)^4 &lt; 4)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        0 &lt; x &lt; 8
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

