<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="crossMultiply">
      <expr>
        (x-2)*2 == (x-3)*x
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        (x-2)*2-(x-3)*x == 0
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        2*x-4-x^2+3*x == 0
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        5*x-4-x^2 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == 1 or x == 4
      </expr>
      <context>
        <item name="clipboard" value="[D==9, a==-1, b==5, c==-4]"/>
      </context>
    </elem>
  </list>
</reply>

