<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="sameDivisor">
      <expr>
        x^2+6 == 7*x
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-7*x+6 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == 6 or x == 1
      </expr>
      <context>
        <item name="clipboard" value="[D==25, a==1, b==-7, c==6]"/>
      </context>
    </elem>
  </list>
</reply>

