<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="crossMultiply">
      <expr>
        -3*(x+1) == (x-5)*(x+3)
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        -3*(x+1)-(x-5)*(x+3) == 0
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        -3*x-3-x^2+2*x+15 == 0
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        -x+12-x^2 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == -4 or x == 3
      </expr>
      <context>
        <item name="clipboard" value="[D==49, a==-1, b==-1, c==12]"/>
      </context>
    </elem>
  </list>
</reply>

