<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="sameDividend">
      <expr>
        x^2+5*x == 0 or 2*x^2 == x^2+4
      </expr>
    </elem>
    <elem ruleid="all power factors">
      <expr>
        x == 0 or x+5 == 0 or 2*x^2 == x^2+4
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == 0 or x == -5 or 2*x^2 == x^2+4
      </expr>
      <context>
        <item name="location" value="[2,1]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x == 0 or x == -5 or x^2-4 == 0
      </expr>
      <context>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 0 or x == -5 or x^2 == 4
      </expr>
      <context>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 0 or x == -5 or x == 2 or x == -2
      </expr>
    </elem>
  </list>
</reply>

