<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="divisionIsZero">
      <expr>
        3*x^2-6 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        3*x^2 == 6
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x^2 == 2
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt 2 or x == -sqrt 2
      </expr>
    </elem>
  </list>
</reply>

