<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="sameDivisor">
      <expr>
        x^2 == 3*x+4
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-3*x-4 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == 4 or x == -1
      </expr>
      <context>
        <item name="clipboard" value="[D==25, a==1, b==-3, c==-4]"/>
      </context>
    </elem>
  </list>
</reply>

