<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="sameDivisor">
      <expr>
        x^2+6*x-6 == 4*x+9
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2+2*x-15 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == 3 or x == -5
      </expr>
      <context>
        <item name="clipboard" value="[D==64, a==1, b==2, c==-15]"/>
      </context>
    </elem>
  </list>
</reply>

