<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="crossMultiply">
      <expr>
        (x+4)*(x+2) == (x+3)*(x+1)
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        (x+4)*(x+2)-(x+3)*(x+1) == 0
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        x^2+6*x+8-x^2-4*x-3 == 0
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        2*x+5 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        2*x == -5
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -5/2
      </expr>
    </elem>
  </list>
</reply>

