<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="divisionIsZero">
      <expr>
        2*x^2-10 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        2*x^2 == 10
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x^2 == 5
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt 5 or x == -sqrt 5
      </expr>
    </elem>
  </list>
</reply>

