<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="sameDivisor">
      <expr>
        x^2+4*x == 3*x+6
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2+x-6 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == 2 or x == -3
      </expr>
      <context>
        <item name="clipboard" value="[D==25, a==1, b==1, c==-6]"/>
      </context>
    </elem>
  </list>
</reply>

