<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="sameDividend">
      <expr>
        x^2-9 == 0 or 4*x-1 == 2*x+7
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x^2 == 9 or 4*x-1 == 2*x+7
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 3 or x == -3 or 4*x-1 == 2*x+7
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x == 3 or x == -3 or 2*x-8 == 0
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 3 or x == -3 or 2*x == 8
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 3 or x == -3 or x == 4
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
  </list>
</reply>

