<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="divisionIsZero">
      <expr>
        4*x^2-24 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        4*x^2 == 24
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x^2 == 6
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt 6 or x == -sqrt 6
      </expr>
    </elem>
  </list>
</reply>

