<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="sameDividend">
      <expr>
        5*x+2 == 0 or 2*x-1 == 3*x+5
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        5*x == -2 or 2*x-1 == 3*x+5
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -2/5 or 2*x-1 == 3*x+5
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x == -2/5 or -x-6 == 0
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == -2/5 or -x == 6
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up negate [vars]">
      <expr>
        x == -2/5 or x == -6
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

