<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="sameDividend">
      <expr>
        x^2-1 == 0 or 2*x+2 == x+8
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x^2 == 1 or 2*x+2 == x+8
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 1 or x == -1 or 2*x+2 == x+8
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x == 1 or x == -1 or x-6 == 0
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 1 or x == -1 or x == 6
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
  </list>
</reply>

