<reply result="ok" version="0.6.7 (3637)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        -24*a*b^3*(-a*b)^2
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        -24*a*b^3*a^2*b^2
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        -24*a^3*b^3*b^2
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        -24*a^3*b^5
      </expr>
    </elem>
  </list>
</reply>

