<reply result="ok" version="0.6.7 (3637)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        4*a^2*(b^3)^2*(-3*a^2*b)^3
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        4*a^2*b^6*(-3*a^2*b)^3
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        -108*a^2*b^6*(a^2)^3*b^3
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        -108*a^2*b^9*(a^2)^3
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        -108*a^2*b^9*a^6
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        -108*a^8*b^9
      </expr>
    </elem>
  </list>
</reply>

