<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        (2*a^3)^4-6*a^3*(-a^9)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        (2*a^3)^4-(-6*a^12)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        16*(a^3)^4-(-6*a^12)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        16*a^12-(-6*a^12)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.calc-power.plus">
      <expr>
        22*a^12
      </expr>
    </elem>
  </list>
</reply>

