<reply result="ok" version="0.6.7 (3623)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        -a^5*(2*b)^5
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        -a^5*(32*b^5)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
  </list>
</reply>

