<reply result="ok" version="0.6.7 (3629)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        6*a^7*(8*(a^4)^3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        6*a^7*(8*a^12)
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        48*a^19
      </expr>
    </elem>
  </list>
</reply>

