<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        32*a^5/(-4*a)^2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        32*a^5/(16*a^2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.sub-exponents">
      <expr>
        2*a^3
      </expr>
    </elem>
  </list>
</reply>

