<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="distribute power">
      <expr>
        -27*(a^2)^3+(4*a^3)^2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="mul exponents">
      <expr>
        -27*a^6+(4*a^3)^2
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="distribute power">
      <expr>
        -27*a^6+16*(a^3)^2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="mul exponents">
      <expr>
        -27*a^6+16*a^6
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="calculate power plus">
      <expr>
        -11*a^6
      </expr>
    </elem>
  </list>
</reply>

