<reply result="ok" version="0.6.7 (3637)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        32*(-a)^3*b^5*a^2
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.push-negation-out">
      <expr>
        -32*a^3*b^5*a^2
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        -32*a^5*b^5
      </expr>
    </elem>
  </list>
</reply>

