<reply result="ok" version="0.6.7 (3629)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        (-a)^3*(32*b^5)*a^2
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.push-negation-out">
      <expr>
        (-a^3)*(32*b^5)*a^2
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        -32*a^5*b^5
      </expr>
    </elem>
  </list>
</reply>

