<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="distribute power">
      <expr>
        6*a^7*8*(a^4)^3
      </expr>
    </elem>
    <elem ruleid="mul exponents">
      <expr>
        6*a^7*8*a^12
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        48*a^19
      </expr>
    </elem>
  </list>
</reply>

