<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        32*a^5+(1/3*a)^2*(-3*a)^3
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        32*a^5+(-(1/3*a)^2*27*a^3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        32*a^5+(-1/9*a^2*27*a^3)
      </expr>
      <context>
        <item name="location" value="[1,0,0,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        32*a^5+(-3*a^5)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.calc-power.minus">
      <expr>
        29*a^5
      </expr>
    </elem>
  </list>
</reply>

