<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        a^(-2)*(1/a^4)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        a^(-2)*a^(-4)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        a^(-6)
      </expr>
    </elem>
  </list>
</reply>

