<reply result="ok" version="0.6.7 (3629)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.push-negation-out">
      <expr>
        5*(-(a^5)^3)*a^6
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        5*(-a^15)*a^6
      </expr>
      <context>
        <item name="location" value="[0,1,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        -5*a^21
      </expr>
    </elem>
  </list>
</reply>

