<reply result="ok" version="0.6.7 (3629)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-var">
      <expr>
        1/9*(-3*a)^4*a^(-2)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.distr-power">
      <expr>
        1/9*(81*a^4)*a^(-2)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        9*a^2
      </expr>
    </elem>
  </list>
</reply>

