{
   "result": [
      [
         "IdempOr",
         "[]",
         [
            "logic.dnf",
            "[0,2,0]",
            "s || p || q || q || t",
            {
            }
         ]
      ],
      [
         "IdempOr",
         "[]",
         [
            "logic.dnf",
            "[0,2,0]",
            "s || p || p || q || t",
            {
            }
         ]
      ]
   ],
   "error": null,
   "id": 421,
   "version": "0.5.8 (2432)"
}
