{
   "result": [
      {
         "domain": "algebra.equations",
         "identifier": "coverup",
         "description": "solve an equation by covering up",
         "status": "Provisional"
      },
      {
         "domain": "algebra.equations",
         "identifier": "linear",
         "description": "solve a linear equation",
         "status": "Provisional"
      },
      {
         "domain": "algebra.equations.linear",
         "identifier": "mixed",
         "description": "solve a linear equation with mixed fractions",
         "status": "Provisional"
      },
      {
         "domain": "algebra.equations",
         "identifier": "polynomial",
         "description": "solve an equation (higher degree)",
         "status": "Provisional"
      },
      {
         "domain": "algebra.equations",
         "identifier": "quadratic",
         "description": "solve a quadratic equation",
         "status": "Provisional"
      },
      {
         "domain": "algebra.equations.quadratic",
         "identifier": "approximate",
         "description": "solve a quadratic equation with approximation",
         "status": "Alpha"
      },
      {
         "domain": "algebra.equations.quadratic",
         "identifier": "no-abc",
         "description": "solve a quadratic equation without abc-formula",
         "status": "Alpha"
      },
      {
         "domain": "algebra.equations",
         "identifier": "rational",
         "description": "solve a rational equation (with a variable in a divisor)",
         "status": "Provisional"
      },
      {
         "domain": "algebra.inequalities",
         "identifier": "linear",
         "description": "solve a linear inequation",
         "status": "Provisional"
      },
      {
         "domain": "algebra.inequalities",
         "identifier": "polynomial",
         "description": "solve an inequation of higher degree",
         "status": "Provisional"
      },
      {
         "domain": "algebra.inequalities",
         "identifier": "quadratic",
         "description": "solve a quadratic inequation",
         "status": "Provisional"
      },
      {
         "domain": "algebra.manipulation.exponents",
         "identifier": "equation",
         "description": "solve power equation algebraically with x > 0",
         "status": "Provisional"
      },
      {
         "domain": "algebra.manipulation.exponents",
         "identifier": "nonnegative",
         "description": "write with a non-negative exponent",
         "status": "Provisional"
      },
      {
         "domain": "algebra.manipulation.exponents",
         "identifier": "powerof",
         "description": "write as a power of a",
         "status": "Provisional"
      },
      {
         "domain": "algebra.manipulation.exponents",
         "identifier": "simplify",
         "description": "simplify expression (powers)",
         "status": "Provisional"
      },
      {
         "domain": "algebra.manipulation.polynomial",
         "identifier": "factor",
         "description": "factorize the expression",
         "status": "Provisional"
      },
      {
         "domain": "algebra.manipulation.rational",
         "identifier": "simplify",
         "description": "simplify a rational expression (with a variable in a divisor)",
         "status": "Alpha"
      },
      {
         "domain": "arithmetic",
         "identifier": "exponents",
         "description": "simplify expression (powers)",
         "status": "Provisional"
      },
      {
         "domain": "arithmetic",
         "identifier": "fractions",
         "description": "simplify expression (fractions)",
         "status": "Alpha"
      },
      {
         "domain": "calculus",
         "identifier": "differentiation",
         "description": "Derivative",
         "status": "Experimental"
      },
      {
         "domain": "calculus.differentiation",
         "identifier": "polynomial",
         "description": "Find the derivative of a polynomial. First normalize the polynomial (e.g., with distribution). Don't make use of the product-rule, or other chain rules.",
         "status": "Provisional"
      },
      {
         "domain": "linearalgebra",
         "identifier": "gaussianelim",
         "description": "Gaussian Elimination",
         "status": "Stable"
      },
      {
         "domain": "linearalgebra",
         "identifier": "gramschmidt",
         "description": "Gram-Schmidt",
         "status": "Alpha"
      },
      {
         "domain": "linearalgebra",
         "identifier": "linsystem",
         "description": "Solve Linear System",
         "status": "Stable"
      },
      {
         "domain": "linearalgebra",
         "identifier": "systemwithmatrix",
         "description": "Solve Linear System with Matrix",
         "status": "Provisional"
      },
      {
         "domain": "logic.propositional",
         "identifier": "dnf",
         "description": "Proposition to DNF",
         "status": "Stable"
      },
      {
         "domain": "logic.propositional.dnf",
         "identifier": "unicode",
         "description": "Proposition to DNF (unicode support)",
         "status": "Stable"
      },
      {
         "domain": "relationalgebra",
         "identifier": "cnf",
         "description": "To conjunctive normal form",
         "status": "Alpha"
      }
   ],
   "error": null,
   "id": 421,
   "version": "0.6.5 (0)"
}
