{
   "result": [
      {
         "domain": "linalg",
         "identifier": "gaussianelim",
         "description": "Gaussian Elimination",
         "status": "Stable"
      },
      {
         "domain": "linalg",
         "identifier": "gramschmidt",
         "description": "Gram-Schmidt",
         "status": "Alpha"
      },
      {
         "domain": "linalg",
         "identifier": "linsystem",
         "description": "Solve Linear System",
         "status": "Stable"
      },
      {
         "domain": "linalg",
         "identifier": "systemwithmatrix",
         "description": "Solve Linear System with Matrix",
         "status": "Provisional"
      },
      {
         "domain": "logic",
         "identifier": "dnf",
         "description": "Proposition to DNF",
         "status": "Stable"
      },
      {
         "domain": "logic",
         "identifier": "dnf-unicode",
         "description": "Proposition to DNF (unicode support)",
         "status": "Stable"
      },
      {
         "domain": "math",
         "identifier": "calcpower",
         "description": "simplify expression (powers)",
         "status": "Provisional"
      },
      {
         "domain": "math",
         "identifier": "coverup",
         "description": "solve an equation by covering up",
         "status": "Provisional"
      },
      {
         "domain": "math",
         "identifier": "derivative",
         "description": "Derivative",
         "status": "Experimental"
      },
      {
         "domain": "math",
         "identifier": "factor",
         "description": "factorize the expression",
         "status": "Provisional"
      },
      {
         "domain": "math",
         "identifier": "fraction",
         "description": "simplify expression (fractions)",
         "status": "Alpha"
      },
      {
         "domain": "math",
         "identifier": "higherdegree",
         "description": "solve an equation (higher degree)",
         "status": "Provisional"
      },
      {
         "domain": "math",
         "identifier": "ineqhigherdegree",
         "description": "solve an inequation of higher degree",
         "status": "Provisional"
      },
      {
         "domain": "math",
         "identifier": "integer",
         "description": "simplify expression (integers)",
         "status": "Alpha"
      },
      {
         "domain": "math",
         "identifier": "lineq",
         "description": "solve a linear equation",
         "status": "Provisional"
      },
      {
         "domain": "math",
         "identifier": "lineq-mixed",
         "description": "solve a linear equation with mixed fractions",
         "status": "Provisional"
      },
      {
         "domain": "math",
         "identifier": "linineq",
         "description": "solve a linear inequation",
         "status": "Provisional"
      },
      {
         "domain": "math",
         "identifier": "natural",
         "description": "simplify expression (natural numbers)",
         "status": "Alpha"
      },
      {
         "domain": "math",
         "identifier": "nonnegexp",
         "description": "write with a non-negative exponent",
         "status": "Provisional"
      },
      {
         "domain": "math",
         "identifier": "powerof",
         "description": "write as a power of a",
         "status": "Provisional"
      },
      {
         "domain": "math",
         "identifier": "quadreq",
         "description": "solve a quadratic equation",
         "status": "Provisional"
      },
      {
         "domain": "math",
         "identifier": "quadreq-no-abc",
         "description": "solve a quadratic equation without abc-formula",
         "status": "Alpha"
      },
      {
         "domain": "math",
         "identifier": "quadreq-with-approx",
         "description": "solve a quadratic equation with approximation",
         "status": "Alpha"
      },
      {
         "domain": "math",
         "identifier": "quadrineq",
         "description": "solve a quadratic inequation",
         "status": "Provisional"
      },
      {
         "domain": "math",
         "identifier": "rational",
         "description": "simplify expression (rational numbers)",
         "status": "Alpha"
      },
      {
         "domain": "math",
         "identifier": "simplifypower",
         "description": "simplify expression (powers)",
         "status": "Provisional"
      },
      {
         "domain": "regexp",
         "identifier": "normalform",
         "description": "Rewrite a regular expression",
         "status": "Experimental"
      },
      {
         "domain": "relationalg",
         "identifier": "cnf",
         "description": "To conjunctive normal form",
         "status": "Alpha"
      }
   ],
   "error": null,
   "id": 421,
   "version": "0.5.13 (3010)"
}
