{
   "result": [
      {
         "name": "CommOr",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "CommAnd",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "AssocOr",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "AssocAnd",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "AndOverOr",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "OrOverAnd",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "IdempOr",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "IdempAnd",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "AbsorpOr",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "AbsorpAnd",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "TrueZeroOr",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "TrueZeroAnd",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "ComplOr",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "NotTrue",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "FalseZeroOr",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "FalseZeroAnd",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "ComplAnd",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "NotFalse",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "NotNot",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "DeMorganOr",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "DeMorganAnd",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "DefImpl",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "DefEquiv",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "FalseInEquiv",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "TrueInEquiv",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "FalseInImpl",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "TrueInImpl",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "CommEquiv",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "DefEquivImpls",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "EquivSame",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "ImplSame",
         "buggy": false,
         "rewriterule": true
      },
      {
         "name": "CommImp",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "AssImp",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "IdemImp",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "IdemEqui",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyEquivElim1",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyEquivElim2",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyImplElim",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyImplElim1",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyDeMorgan1",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyDeMorgan2",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyDeMorgan3",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyDeMorgan4",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyNotOverImpl",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyParenth1",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyParenth2",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyParenth3",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyAssoc",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "AndSame",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "AndComplBuggy",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "OrSame",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "OrComplBuggy",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "TrueProp",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "FalseProp",
         "buggy": true,
         "rewriterule": true
      },
      {
         "name": "BuggyDistr",
         "buggy": true,
         "rewriterule": true
      }
   ],
   "error": null,
   "id": 421
}
