<reply result="ok" version="0.6.3 (0)">
  <list>
    <elem ruleid="crossMultiply">
      <expr>
        (2*x+3)*2 == (x-1)*7
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        (2*x+3)*2-(x-1)*7 == 0
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        4*x+6-7*x+7 == 0
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        -3*x+13 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -3*x == -13
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 13/3
      </expr>
    </elem>
  </list>
</reply>

