<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.division-zero">
      <expr>
        7*x^2-21 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1/2*sqrt 10) (x/=1/2*sqrt 10)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        7*x^2 == 21
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1/2*sqrt 10) (x/=1/2*sqrt 10)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^2 == 3
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1/2*sqrt 10) (x/=1/2*sqrt 10)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt 3 or x == -sqrt 3
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1/2*sqrt 10) (x/=1/2*sqrt 10)]"/>
      </context>
    </elem>
  </list>
</reply>

