<reply result="ok" version="0.6.3 (0)">
  <list>
    <elem ruleid="cover-up plus [vars]">
      <expr>
        x^2/(2*x-3) == 4
      </expr>
    </elem>
    <elem ruleid="multiplyOneDiv">
      <expr>
        x^2 == (2*x-3)*4
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        -(2*x-3)*4+x^2 == 0
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        -8*x+12+x^2 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x-2)*(x-6) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 2 or x == 6
      </expr>
    </elem>
  </list>
</reply>

