<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.cross-multiply">
      <expr>
        (x+4)*(x+2) == (x+3)*(x+1)
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-3) (x/=-2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        (x+4)*(x+2)-(x+3)*(x+1) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-3) (x/=-2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^2+6*x+8-x^2-4*x-3 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-3) (x/=-2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        2*x+5 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-3) (x/=-2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        2*x == -5
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-3) (x/=-2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -5/2
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-3) (x/=-2)]"/>
      </context>
    </elem>
  </list>
</reply>

