<reply result="ok" version="0.6.3 (0)">
  <list>
    <elem ruleid="sameDivisor">
      <expr>
        x^2+6 == 5*x
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-5*x+6 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x-2)*(x-3) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 2 or x == 3
      </expr>
    </elem>
  </list>
</reply>

