<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.same-dividend">
      <expr>
        x^2-1 == 0 or 2*x+2 == x+8
      </expr>
      <context>
        <item name="clipboard" value="[condition == logic1.and (x /= -1) (x /= -8)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x^2 == 1 or 2*x+2 == x+8
      </expr>
      <context>
        <item name="clipboard" value="[condition == logic1.and (x /= -1) (x /= -8)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 1 or x == -1 or 2*x+2 == x+8
      </expr>
      <context>
        <item name="clipboard" value="[condition == logic1.and (x /= -1) (x /= -8)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x == 1 or x == -1 or x-6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition == logic1.and (x /= -1) (x /= -8)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 1 or x == -1 or x == 6
      </expr>
      <context>
        <item name="clipboard" value="[condition == logic1.and (x /= -1) (x /= -8)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.check-solution">
      <expr>
        x == 1 or x == 6
      </expr>
      <context>
        <item name="clipboard" value="[condition == logic1.and (x /= -1) (x /= -8)]"/>
      </context>
    </elem>
  </list>
</reply>

