<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="crossmultiply">
      <expr>
        (x+2)*3 == 12*x
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=0)]"/>
      </context>
    </elem>
    <elem ruleid="same constant factor">
      <expr>
        x+2 == 4*x
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=0)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        -3*x+2 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -3*x == -2
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 2/3
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=0)]"/>
      </context>
    </elem>
  </list>
</reply>

