<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="crossmultiply">
      <expr>
        (x+1)*(x-2) == (x-1)*(3*x-7)
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        (x+1)*(x-2)-(x-1)*(3*x-7) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^2-x-2-3*x^2+10*x-7 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        -2*x^2+9*x-9 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-poly">
      <expr>
        2*x^2-9*x+9 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        x == 3 or x == 3/2
      </expr>
      <context>
        <item name="clipboard" value="[D==9, a==2, b==-9, c==9, condition==logic1.and (x/=1) (x/=2)]"/>
      </context>
    </elem>
  </list>
</reply>

