<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.same-dividend">
      <expr>
        x^2-3*x == 0 or 2*x-6 == 4*x+2
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=3) (x/=-1/2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.power-factors">
      <expr>
        x == 0 or x-3 == 0 or 2*x-6 == 4*x+2
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=3) (x/=-1/2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 0 or x == 3 or 2*x-6 == 4*x+2
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=3) (x/=-1/2)]"/>
        <item name="location" value="[2,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.same-con-factor">
      <expr>
        x == 0 or x == 3 or x-3 == 2*x+1
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=3) (x/=-1/2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x == 0 or x == 3 or -x-4 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=3) (x/=-1/2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 0 or x == 3 or -x == 4
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=3) (x/=-1/2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.negate">
      <expr>
        x == 0 or x == 3 or x == -4
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=3) (x/=-1/2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.check-solution">
      <expr>
        x == 0 or x == -4
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=3) (x/=-1/2)]"/>
      </context>
    </elem>
  </list>
</reply>

