<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.plus">
      <expr>
        (x+5)/(2*x) == 3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.rational.multiply-one-div">
      <expr>
        x+5 == 6*x
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        -5*x+5 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -5*x == -5
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 1
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 0)]"/>
      </context>
    </elem>
  </list>
</reply>

