<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.division-zero">
      <expr>
        4*x^2-24 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1/3*sqrt 3) (x/=1/3*sqrt 3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        4*x^2 == 24
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1/3*sqrt 3) (x/=1/3*sqrt 3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^2 == 6
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1/3*sqrt 3) (x/=1/3*sqrt 3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt 6 or x == -sqrt 6
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1/3*sqrt 3) (x/=1/3*sqrt 3)]"/>
      </context>
    </elem>
  </list>
</reply>

