<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="crossmultiply">
      <expr>
        (x-2)*2 == (x-3)*x
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=3)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        (x-2)*2-(x-3)*x == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=3)]"/>
      </context>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        2*x-4-x^2+3*x == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=3)]"/>
      </context>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        5*x-4-x^2 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=3)]"/>
      </context>
    </elem>
    <elem ruleid="simpler polynomial">
      <expr>
        x^2-5*x+4 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=3)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x-1)*(x-4) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=3)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 1 or x == 4
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=3)]"/>
      </context>
    </elem>
  </list>
</reply>

