<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="divisionIsZero">
      <expr>
        7*x^2-21 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        7*x^2 == 21
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x^2 == 3
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt 3 or x == -sqrt 3
      </expr>
    </elem>
  </list>
</reply>

