<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="crossMultiply">
      <expr>
        (x+2)*3 == 12*x
      </expr>
    </elem>
    <elem ruleid="same constant factor">
      <expr>
        x+2 == 4*x
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        -3*x+2 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -3*x == -2
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 2/3
      </expr>
    </elem>
  </list>
</reply>

