<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="samedividend">
      <expr>
        x^2-1 == 0 or 2*x+2 == x+8
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1) (x/=-8)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x^2 == 1 or 2*x+2 == x+8
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1) (x/=-8)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 1 or x == -1 or 2*x+2 == x+8
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1) (x/=-8)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x == 1 or x == -1 or x-6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1) (x/=-8)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 1 or x == -1 or x == 6
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1) (x/=-8)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="check solution">
      <expr>
        x == 1 or x == 6
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-1) (x/=-8)]"/>
      </context>
    </elem>
  </list>
</reply>

