<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.cross-multiply">
      <expr>
        4*x == (x+1)*7
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        -(x+1)*7+4*x == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        -7*x-7+4*x == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        -3*x-7 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -3*x == 7
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -7/3
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-1)]"/>
      </context>
    </elem>
  </list>
</reply>

