<reply result="ok" version="0.6.3 (0)">
  <list>
    <elem ruleid="crossMultiply">
      <expr>
        (x+1)*(x-2) == (x-1)*(3*x-7)
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        (x+1)*(x-2)-(x-1)*(3*x-7) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        x^2-x-2-3*x^2+10*x-7 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        -2*x^2+9*x-9 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="simpler polynomial">
      <expr>
        2*x^2-9*x+9 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == 3 or x == 3/2
      </expr>
      <context>
        <item name="clipboard" value="[D==9, a==2, b==-9, c==9, condition==logic1.and (x/=1) (x/=2)]"/>
      </context>
    </elem>
  </list>
</reply>

