<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.same-divisor">
      <expr>
        x^2+6 == 5*x
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-5*x+6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x-2)*(x-3) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 2 or x == 3
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.check-solution">
      <expr>
        x == 2
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 3)]"/>
      </context>
    </elem>
  </list>
</reply>

