<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="samedividend">
      <expr>
        x^2-9 == 0 or 4*x-1 == 2*x+7
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/4) (x/=-7/2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x^2 == 9 or 4*x-1 == 2*x+7
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/4) (x/=-7/2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 3 or x == -3 or 4*x-1 == 2*x+7
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/4) (x/=-7/2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x == 3 or x == -3 or 2*x-8 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/4) (x/=-7/2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 3 or x == -3 or 2*x == 8
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/4) (x/=-7/2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 3 or x == -3 or x == 4
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/4) (x/=-7/2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
  </list>
</reply>

