<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.same-divisor">
      <expr>
        x^2+2*x-4 == 4*x+11
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=5)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-2*x-15 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=5)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+3)*(x-5) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=5)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -3 or x == 5
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=5)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.check-solution">
      <expr>
        x == -3
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=5)]"/>
      </context>
    </elem>
  </list>
</reply>

