<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.same-dividend">
      <expr>
        5*x+2 == 0 or 2*x-1 == 3*x+5
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/2) (x/=-5/3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        5*x == -2 or 2*x-1 == 3*x+5
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/2) (x/=-5/3)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -2/5 or 2*x-1 == 3*x+5
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/2) (x/=-5/3)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x == -2/5 or -x-6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/2) (x/=-5/3)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == -2/5 or -x == 6
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/2) (x/=-5/3)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.negate">
      <expr>
        x == -2/5 or x == -6
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/2) (x/=-5/3)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

