<reply result="ok" version="0.6.3 (0)">
  <list>
    <elem ruleid="cover-up plus [vars]">
      <expr>
        x^2/(5*x+6) == 1
      </expr>
    </elem>
    <elem ruleid="divisionIsOne">
      <expr>
        x^2 == 5*x+6
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-5*x-6 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+1)*(x-6) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -1 or x == 6
      </expr>
    </elem>
  </list>
</reply>

