<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="samedividend">
      <expr>
        x^2-4 == 0 or 3*x-6 == 2*x+1
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=2) (x/=-1/2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x^2 == 4 or 3*x-6 == 2*x+1
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=2) (x/=-1/2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2 or x == -2 or 3*x-6 == 2*x+1
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=2) (x/=-1/2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x == 2 or x == -2 or x-7 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=2) (x/=-1/2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 2 or x == -2 or x == 7
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=2) (x/=-1/2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="check solution">
      <expr>
        x == -2 or x == 7
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=2) (x/=-1/2)]"/>
      </context>
    </elem>
  </list>
</reply>

