<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="crossMultiply">
      <expr>
        (x+9)*x == (x-5)*2
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        (x+9)*x-(x-5)*2 == 0
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        x^2+9*x-2*x+10 == 0
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        x^2+7*x+10 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == -2 or x == -5
      </expr>
      <context>
        <item name="clipboard" value="[D==9, a==1, b==7, c==10]"/>
      </context>
    </elem>
  </list>
</reply>

