<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="crossmultiply">
      <expr>
        (2*x+3)*2 == (x-1)*7
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        (2*x+3)*2-(x-1)*7 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        4*x+6-7*x+7 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        -3*x+13 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -3*x == -13
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 13/3
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
  </list>
</reply>

