<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="crossmultiply">
      <expr>
        (x-3)*5 == (1-x)*7
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        (x-3)*5-(1-x)*7 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        5*x-22+7*x == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        12*x-22 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        12*x == 22
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 11/6
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
  </list>
</reply>

