<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="samedivisor">
      <expr>
        x^2+6 == 7*x
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-sqrt 2) (x/=sqrt 2)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-7*x+6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-sqrt 2) (x/=sqrt 2)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x-1)*(x-6) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-sqrt 2) (x/=sqrt 2)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 1 or x == 6
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-sqrt 2) (x/=sqrt 2)]"/>
      </context>
    </elem>
  </list>
</reply>

