<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="crossmultiply">
      <expr>
        -3*(x+1) == (x-5)*(x+3)
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        -3*(x+1)-(x-5)*(x+3) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        -3*x-3-x^2+2*x+15 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        -x+12-x^2 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-poly">
      <expr>
        x^2+x-12 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x-3)*(x+4) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 3 or x == -4
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=-1)]"/>
      </context>
    </elem>
  </list>
</reply>

