<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.plus">
      <expr>
        x^2/(5*x+6) == 1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.rational.division-one">
      <expr>
        x^2 == 5*x+6
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-6/5)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-5*x-6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-6/5)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+1)*(x-6) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-6/5)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -1 or x == 6
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-6/5)]"/>
      </context>
    </elem>
  </list>
</reply>

