<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="samedivisor">
      <expr>
        x^2+4*x == 3*x+6
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-2) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2+x-6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-2) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x-2)*(x+3) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-2) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 2 or x == -3
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-2) (x/=2)]"/>
      </context>
    </elem>
    <elem ruleid="check solution">
      <expr>
        x == -3
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-2) (x/=2)]"/>
      </context>
    </elem>
  </list>
</reply>

