<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.cross-multiply">
      <expr>
        (3*x+6)*(x+1) == (3*x-1)*(x+4)
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/3) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        (3*x+6)*(x+1)-(3*x-1)*(x+4) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/3) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        3*x^2+9*x+6-3*x^2-11*x+4 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/3) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        -2*x+10 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/3) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -2*x == -10
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/3) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 5
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=1/3) (x/=-1)]"/>
      </context>
    </elem>
  </list>
</reply>

