<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.same-divisor">
      <expr>
        x^2 == 3*x+4
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-4)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-3*x-4 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-4)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+1)*(x-4) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-4)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -1 or x == 4
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-4)]"/>
      </context>
    </elem>
  </list>
</reply>

