<reply result="ok" version="0.6.3 (0)">
  <list>
    <elem ruleid="crossMultiply">
      <expr>
        (x+9)*x == (x-5)*2
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        (x+9)*x-(x-5)*2 == 0
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        x^2+9*x-2*x+10 == 0
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        x^2+7*x+10 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+2)*(x+5) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -2 or x == -5
      </expr>
    </elem>
  </list>
</reply>

