<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.cross-multiply">
      <expr>
        (2*x-7)*(3*x-7) == (5-x)*(x+1)
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=7/3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        (2*x-7)*(3*x-7)-(5-x)*(x+1) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=7/3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        6*x^2-35*x+49-4*x-5+x^2 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=7/3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        7*x^2-39*x+44 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=7/3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        x == 4 or x == 11/7
      </expr>
      <context>
        <item name="clipboard" value="[D==289, a==7, b==-39, c==44, condition==logic1.and (x/=5) (x/=7/3)]"/>
      </context>
    </elem>
  </list>
</reply>

