<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.same-dividend">
      <expr>
        x^2+5*x == 0 or 2*x^2 == x^2+4
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.power-factors">
      <expr>
        x == 0 or x+5 == 0 or 2*x^2 == x^2+4
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 0)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == 0 or x == -5 or 2*x^2 == x^2+4
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 0)]"/>
        <item name="location" value="[2,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x == 0 or x == -5 or x^2-4 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 0)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 0 or x == -5 or x^2 == 4
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 0)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 0 or x == -5 or x == 2 or x == -2
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 0)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.check-solution">
      <expr>
        x == -5 or x == 2 or x == -2
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= 0)]"/>
      </context>
    </elem>
  </list>
</reply>

