<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="crossmultiply">
      <expr>
        (x+9)*x == (x-5)*2
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        (x+9)*x-(x-5)*2 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^2+9*x-2*x+10 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        x^2+7*x+10 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+2)*(x+5) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -2 or x == -5
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=5) (x/=0)]"/>
      </context>
    </elem>
  </list>
</reply>

