<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.cross-multiply">
      <expr>
        (x+2)*(x+1) == (x+4)*2
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-4) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        (x+2)*(x+1)-(x+4)*2 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-4) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^2+3*x+2-2*x-8 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-4) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        x^2+x-6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-4) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x-2)*(x+3) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-4) (x/=-1)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 2 or x == -3
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-4) (x/=-1)]"/>
      </context>
    </elem>
  </list>
</reply>

