<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="sameDividend">
      <expr>
        2*x+1 == 0 or x^2+3*x == 5*x+8
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        2*x == -1 or x^2+3*x == 5*x+8
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -1/2 or x^2+3*x == 5*x+8
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x == -1/2 or x^2-2*x-8 == 0
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == -1/2 or x == 4 or x == -2
      </expr>
      <context>
        <item name="clipboard" value="[D==36, a==1, b==-2, c==-8]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

