<reply result="ok" version="0.6.3 (0)">
  <list>
    <elem ruleid="sameDividend">
      <expr>
        2*x+1 == 0 or x^2+3*x == 5*x+8
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (logic1.and (x/=-3) (x/=0)) (x/=-8/5)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        2*x == -1 or x^2+3*x == 5*x+8
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (logic1.and (x/=-3) (x/=0)) (x/=-8/5)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -1/2 or x^2+3*x == 5*x+8
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (logic1.and (x/=-3) (x/=0)) (x/=-8/5)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x == -1/2 or x^2-2*x-8 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (logic1.and (x/=-3) (x/=0)) (x/=-8/5)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        x == -1/2 or (x+2)*(x-4) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (logic1.and (x/=-3) (x/=0)) (x/=-8/5)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -1/2 or x == -2 or x == 4
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (logic1.and (x/=-3) (x/=0)) (x/=-8/5)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

