<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.same-dividend">
      <expr>
        x^2-4 == 0 or 3*x-6 == 2*x+1
      </expr>
      <context>
        <item name="clipboard" value="[condition == logic1.and (x /= 2) (x /= -1/2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x^2 == 4 or 3*x-6 == 2*x+1
      </expr>
      <context>
        <item name="clipboard" value="[condition == logic1.and (x /= 2) (x /= -1/2)]"/>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2 or x == -2 or 3*x-6 == 2*x+1
      </expr>
      <context>
        <item name="clipboard" value="[condition == logic1.and (x /= 2) (x /= -1/2)]"/>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x == 2 or x == -2 or x-7 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition == logic1.and (x /= 2) (x /= -1/2)]"/>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 2 or x == -2 or x == 7
      </expr>
      <context>
        <item name="clipboard" value="[condition == logic1.and (x /= 2) (x /= -1/2)]"/>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.check-solution">
      <expr>
        x == -2 or x == 7
      </expr>
      <context>
        <item name="clipboard" value="[condition == logic1.and (x /= 2) (x /= -1/2)]"/>
      </context>
    </elem>
  </list>
</reply>

