<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="samedivisor">
      <expr>
        x^2+2*x-4 == 4*x+11
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=5)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-2*x-15 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=5)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+3)*(x-5) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=5)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -3 or x == 5
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=5)]"/>
      </context>
    </elem>
    <elem ruleid="check solution">
      <expr>
        x == -3
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=5)]"/>
      </context>
    </elem>
  </list>
</reply>

