<reply result="ok" version="0.6.3 (0)">
  <list>
    <elem ruleid="sameDivisor">
      <expr>
        x^2 == 3*x+4
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-3*x-4 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+1)*(x-4) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -1 or x == 4
      </expr>
    </elem>
  </list>
</reply>

