<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="crossMultiply">
      <expr>
        (2*x-7)*(3*x-7) == (5-x)*(x+1)
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        (2*x-7)*(3*x-7)-(5-x)*(x+1) == 0
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        6*x^2-35*x+49-4*x-5+x^2 == 0
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        7*x^2-39*x+44 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == 4 or x == 11/7
      </expr>
      <context>
        <item name="clipboard" value="[D==289, a==7, b==-39, c==44]"/>
      </context>
    </elem>
  </list>
</reply>

