<reply result="ok" version="0.6.3 (0)">
  <list>
    <elem ruleid="sameDivisor">
      <expr>
        x^2+2*x-4 == 4*x+11
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-2*x-15 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+3)*(x-5) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -3 or x == 5
      </expr>
    </elem>
  </list>
</reply>

