<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.minus-left">
      <expr>
        (3*x+4)/(x+2) == 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.rational.multiply-one-div">
      <expr>
        3*x+4 == (x+2)*5
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        -(x+2)*5+3*x+4 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        -5*x-10+3*x+4 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        -2*x-6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -2*x == 6
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -3
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-2)]"/>
      </context>
    </elem>
  </list>
</reply>

