<reply result="ok" version="0.6.3 (0)">
  <list>
    <elem ruleid="crossMultiply">
      <expr>
        (x+2)*(x+1) == (x+4)*2
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        (x+2)*(x+1)-(x+4)*2 == 0
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        x^2+3*x+2-2*x-8 == 0
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        x^2+x-6 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x-2)*(x+3) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 2 or x == -3
      </expr>
    </elem>
  </list>
</reply>

