<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="crossmultiply">
      <expr>
        (x+2)*(2*x-3) == (2*x+5)*(x+4)
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-5/2) (x/=3/2)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        (x+2)*(2*x-3)-(2*x+5)*(x+4) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-5/2) (x/=3/2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        2*x^2+x-6-2*x^2-13*x-20 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-5/2) (x/=3/2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        -12*x-26 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-5/2) (x/=3/2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -12*x == 26
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-5/2) (x/=3/2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -13/6
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-5/2) (x/=3/2)]"/>
      </context>
    </elem>
  </list>
</reply>

