<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.same-dividend">
      <expr>
        3*x-2 == 0 or 2*x^2 == x^2+4
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        3*x == 2 or 2*x^2 == x^2+4
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=0)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 2/3 or 2*x^2 == x^2+4
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=0)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x == 2/3 or x^2-4 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=0)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 2/3 or x^2 == 4
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=0)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2/3 or x == 2 or x == -2
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=0)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

