<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.same-divisor">
      <expr>
        x^2+6 == 7*x
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-sqrt 2) (x/=sqrt 2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-7*x+6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-sqrt 2) (x/=sqrt 2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x-1)*(x-6) == 0
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-sqrt 2) (x/=sqrt 2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 1 or x == 6
      </expr>
      <context>
        <item name="clipboard" value="[condition==logic1.and (x/=-sqrt 2) (x/=sqrt 2)]"/>
      </context>
    </elem>
  </list>
</reply>

