<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="fraction scale">
      <expr>
        (x-4)*(x+3)/((x-1)*(x-4))+(x-1)*(x+2)/((x-1)*(x-4))
      </expr>
    </elem>
    <elem ruleid="fraction plus">
      <expr>
        ((x-4)*(x+3)+(x-1)*(x+2))/((x-1)*(x-4))
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        (x^2-x-12+x^2+x-2)/((x-1)*(x-4))
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        (2*x^2-14)/((x-1)*(x-4))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

