<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="fraction scale">
      <expr>
        (x+2)*(x-2)/((x+3)*(x+2))+(x+3)*(x-1)/((x+3)*(x+2))
      </expr>
    </elem>
    <elem ruleid="fraction plus">
      <expr>
        ((x+2)*(x-2)+(x+3)*(x-1))/((x+3)*(x+2))
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        (x^2-4+x^2+2*x-3)/((x+3)*(x+2))
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        (2*x^2-7+2*x)/((x+3)*(x+2))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

