<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="nice factors">
      <expr>
        (2*p^2+8*p)/((p+4)*(p-4))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="common factor var">
      <expr>
        2*p*(p+4)/((p+4)*(p-4))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cancel terms div">
      <expr>
        2*p/(p-4)
      </expr>
    </elem>
  </list>
</reply>

