<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="fraction scale">
      <expr>
        (x-2)*6/((x-1)*(x-2))-(x-1)*3/((x-1)*(x-2))
      </expr>
    </elem>
    <elem ruleid="fraction plus">
      <expr>
        ((x-2)*6-(x-1)*3)/((x-1)*(x-2))
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        (6*x-12-3*x+3)/((x-1)*(x-2))
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        (3*x-9)/((x-1)*(x-2))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

