<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="fraction scale">
      <expr>
        (x+1)*7/((x-3)*(x+1))-(x-3)*2/((x-3)*(x+1))
      </expr>
    </elem>
    <elem ruleid="fraction plus">
      <expr>
        ((x+1)*7-(x-3)*2)/((x-3)*(x+1))
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        (7*x+7-2*x+6)/((x-3)*(x+1))
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        (5*x+13)/((x-3)*(x+1))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

