<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="nice factors">
      <expr>
        (x^2-16)/((x-3)*(x+4))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+4)*(x-4)/((x-3)*(x+4))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cancel terms div">
      <expr>
        (x-4)/(x-3)
      </expr>
    </elem>
  </list>
</reply>

