<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        D(x) (5*(x-3)^2+10*x-5)
      </expr>
      <context>
        <item name="location" value="[0,1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.distr-square">
      <expr>
        D(x) (5*(x^2-6*x+9)+10*x-5)
      </expr>
      <context>
        <item name="location" value="[0,1,0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        D(x) (5*x^2-30*x+45+10*x-5)
      </expr>
      <context>
        <item name="location" value="[0,1,0,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        D(x) (5*x^2-20*x+40)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        10*x-20
      </expr>
    </elem>
  </list>
</reply>

