<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.distr-square">
      <expr>
        D(x) (9*x^2+36*x+36-8*x)
      </expr>
      <context>
        <item name="location" value="[0,1,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        D(x) (9*x^2+28*x+36)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        18*x+28
      </expr>
    </elem>
  </list>
</reply>

