<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.distr-square">
      <expr>
        D(x) (16*x^2-24*x+9)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        32*x-24
      </expr>
    </elem>
  </list>
</reply>

