<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        D(x) (3*x^3+5*x^2+6*x^2+10*x)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        D(x) (3*x^3+11*x^2+10*x)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        9*x^2+22*x+10
      </expr>
    </elem>
  </list>
</reply>

