<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        D(x) (15*x^5+12*x^4-21*x^3+10*x^3+8*x^2-14*x)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        D(x) (15*x^5+12*x^4-11*x^3+8*x^2-14*x)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        75*x^4+48*x^3-33*x^2+16*x-14
      </expr>
    </elem>
  </list>
</reply>

