<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.distr-square">
      <expr>
        D(x) (25*x^6+70*x^4+49*x^2)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        150*x^5+280*x^3+98*x
      </expr>
    </elem>
  </list>
</reply>

