<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.distr-square">
      <expr>
        D(x) (-1+6*x-9*x^2)
      </expr>
      <context>
        <item name="location" value="[0,1,0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        -18*x+6
      </expr>
    </elem>
  </list>
</reply>

