<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        D(x) (12*x^4-4*x^3+8*x^2+3*x^3-x^2+2*x)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        D(x) (12*x^4-x^3+7*x^2+2*x)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        48*x^3-3*x^2+14*x+2
      </expr>
    </elem>
  </list>
</reply>

