<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        D(x) (x^5-4*x^4+3*x^2+2*x^4-8*x^3+6*x)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        D(x) (x^5-2*x^4+3*x^2-8*x^3+6*x)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        5*x^4-8*x^3-24*x^2+6*x+6
      </expr>
    </elem>
  </list>
</reply>

