<reply result="ok" version="0.6.7 (3651)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.equation.greatest-power">
      <expr>
        x^14 == 5^2
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.common-power">
      <expr>
        x^7 == 5
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.nth-root">
      <expr>
        x == root 5 7
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.approx-power">
      <expr>
        x ~= 1.26
      </expr>
    </elem>
  </list>
</reply>

