<reply result="ok" version="0.6.7 (3710)">
  <list>
    <elem ruleid="algebra.equations.coverup.plus">
      <expr>
        3*x^5 == 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^5 == 8/3
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.nth-root">
      <expr>
        x == root (8/3) 5
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.approx-power">
      <expr>
        x ~= 1.22
      </expr>
    </elem>
  </list>
</reply>

