<reply result="ok" version="0.6.6 (3601)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.nth-power">
      <expr>
        x^3 == 720^4
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.nth-root">
      <expr>
        x == 720^(4/3)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.approx-power">
      <expr>
        x ~= 6453.22
      </expr>
    </elem>
  </list>
</reply>

