<reply result="ok" version="0.6.6 (3601)">
  <list>
    <elem ruleid="algebra.equations.coverup.minus-left">
      <expr>
        8*x^(-19/10) == 7
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^(-19/10) == 7/8
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.nth-root">
      <expr>
        x == (7/8)^(-10/19)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.approx-power">
      <expr>
        x ~= 1.07
      </expr>
    </elem>
  </list>
</reply>

