<reply result="ok" version="0.6.6 (3601)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.nth-power">
      <expr>
        x^2 == (11/2)^5
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.nth-root">
      <expr>
        x == (11/2)^(5/2)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.approx-power">
      <expr>
        x ~= 70.94
      </expr>
    </elem>
  </list>
</reply>

