<reply result="ok" version="0.6.5 (3554)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.scale-factor">
      <expr>
        x^(7/2) == 35
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.nth-root">
      <expr>
        x == 35^(2/7)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.approx-power">
      <expr>
        x ~= 2.76
      </expr>
    </elem>
  </list>
</reply>

