<reply result="ok" version="0.6.6 (3601)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.greatest-power">
      <expr>
        x^14 == 5^2
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.common-power">
      <expr>
        x^7 == 5
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.nth-root">
      <expr>
        x == 5^(1/7)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.approx-power">
      <expr>
        x ~= 1.26
      </expr>
    </elem>
  </list>
</reply>

