<reply result="ok" version="0.6.6 (3601)">
  <list>
    <elem ruleid="algebra.equations.coverup.plus">
      <expr>
        9*x^(16/5) == 20
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^(16/5) == 20/9
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.nth-root">
      <expr>
        x == (20/9)^(5/16)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.approx-power">
      <expr>
        x ~= 1.28
      </expr>
    </elem>
  </list>
</reply>

