<reply result="ok" version="0.6.7 (3651)">
  <list>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        root x 3 == 7/5
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.nth-root">
      <expr>
        x == (7/5)^3
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.approx-power">
      <expr>
        x ~= 2.74
      </expr>
    </elem>
  </list>
</reply>

