<reply result="ok" version="0.6.6 (3601)">
  <list>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^(-46/5) == 125
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.nth-root">
      <expr>
        x == 125^(-5/46)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.approx-power">
      <expr>
        x ~= 0.59
      </expr>
    </elem>
  </list>
</reply>

