<reply result="ok" version="0.6.5 (3554)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.scale-factor">
      <expr>
        x^(-46/5) == 125
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.greatest-power">
      <expr>
        x^(-46/5) == 5^3
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

