<reply result="ok" version="0.6.7 (3710)">
  <list>
    <elem ruleid="algebra.equations.coverup.plus">
      <expr>
        4*root x 7 == 24/5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        root x 7 == 6/5
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.nth-root">
      <expr>
        x == (6/5)^7
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.approx-power">
      <expr>
        x ~= 3.58
      </expr>
    </elem>
  </list>
</reply>

