<reply result="ok" version="0.6.7 (3651)">
  <list>
    <elem ruleid="algebra.equations.coverup.plus">
      <expr>
        7*x^(51/10) == 84
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^(51/10) == 12
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.nth-root">
      <expr>
        x == 12^(10/51)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.approx-power">
      <expr>
        x ~= 1.63
      </expr>
    </elem>
  </list>
</reply>

