<reply result="ok" version="0.6.7 (3651)">
  <list>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^(7/2) == 35
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.nth-root">
      <expr>
        x == 35^(2/7)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.approx-power">
      <expr>
        x ~= 2.76
      </expr>
    </elem>
  </list>
</reply>

