<reply result="ok" version="0.6.7 (3710)">
  <list>
    <elem ruleid="algebra.equations.coverup.minus-left">
      <expr>
        7/10*x^4 == 33/10
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^4 == 33/7
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.nth-root">
      <expr>
        x == root (33/7) 4
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.approx-power">
      <expr>
        x ~= 1.47
      </expr>
    </elem>
  </list>
</reply>

