<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        5*x
      </argument>
      <expr>
        -x+5 &lt; -3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -x &lt; -8
      </expr>
    </elem>
    <elem ruleid="algebra.inequalities.flip-sign">
      <expr>
        x &gt; 8
      </expr>
    </elem>
  </list>
</reply>

