<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <argument description="factor">
        4
      </argument>
      <expr>
        4*x+24 &gt; 8-3*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        (-3)*x
      </argument>
      <expr>
        7*x+24 &gt; 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        7*x &gt; -16
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times-positive">
      <expr>
        x &gt; -16/7
      </expr>
    </elem>
  </list>
</reply>

