<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        -4*x+1 &lt; 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -4*x &lt; 4
      </expr>
    </elem>
    <elem ruleid="algebra.inequalities.flip-sign">
      <expr>
        4*x &gt; -4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times-positive">
      <expr>
        x &gt; -1
      </expr>
    </elem>
  </list>
</reply>

