<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        2*x-2-3*x+6 &gt; 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        -x+4 &gt; 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -x &gt; 2
      </expr>
    </elem>
    <elem ruleid="algebra.inequalities.flip-sign">
      <expr>
        x &lt; -2
      </expr>
    </elem>
  </list>
</reply>

