<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        5*x
      </argument>
      <expr>
        2*x-12 &lt; 3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        2*x &lt; 15
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times-positive">
      <expr>
        x &lt; 15/2
      </expr>
    </elem>
  </list>
</reply>

