<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="remove division">
      <expr>
        4*x+24 &gt; 8-3*x
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        7*x+24 &gt; 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        7*x &gt; -16
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times positive">
      <expr>
        x &gt; -16/7
      </expr>
    </elem>
  </list>
</reply>

