<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        6*x-2 &lt; 3+9*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        -3*x-2 &lt; 3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus left">
      <expr>
        -3*x &lt; 5
      </expr>
    </elem>
    <elem ruleid="flip sign">
      <expr>
        3*x &gt; -5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times positive">
      <expr>
        x &gt; -5/3
      </expr>
    </elem>
  </list>
</reply>

