<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="distribution multiplication">
      <expr>
        5-2*a+6 &gt; 15-5*a
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        11-2*a &gt; 15-5*a
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        11+3*a &gt; 15
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        3*a &gt; 4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times positive">
      <expr>
        a &gt; 4/3
      </expr>
    </elem>
  </list>
</reply>

