<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        5*x-5 &lt; 7*x-1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        7*x
      </argument>
      <expr>
        -2*x-5 &lt; -1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -2*x &lt; 4
      </expr>
    </elem>
    <elem ruleid="algebra.inequalities.flip-sign">
      <expr>
        2*x &gt; -4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times-positive">
      <expr>
        x &gt; -2
      </expr>
    </elem>
  </list>
</reply>

