<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        -12*x+3 &gt; 2-x+1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        -12*x+3 &gt; 3-x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        -11*x+3 &gt; 3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -11*x &gt; 0
      </expr>
    </elem>
    <elem ruleid="algebra.inequalities.flip-sign">
      <expr>
        11*x &lt; 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times-positive">
      <expr>
        x &lt; 0
      </expr>
    </elem>
  </list>
</reply>

