<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        6*a+6 &lt; 3*a-6+4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        6*a+6 &lt; 3*a-2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        3*a+6 &lt; -2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        3*a &lt; -8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times positive">
      <expr>
        a &lt; -8/3
      </expr>
    </elem>
  </list>
</reply>

