<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="distribution multiplication">
      <expr>
        4*x-12 &gt; 3*x-12
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        x-12 &gt; -12
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus left">
      <expr>
        x &gt; 0
      </expr>
    </elem>
  </list>
</reply>

