<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <argument description="factor">
        6
      </argument>
      <expr>
        -3*(x-12) &gt; 2*(x+3)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        -3*x+36 &gt; 2*x+6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        2*x
      </argument>
      <expr>
        -5*x+36 &gt; 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -5*x &gt; -30
      </expr>
    </elem>
    <elem ruleid="algebra.inequalities.flip-sign">
      <expr>
        5*x &lt; 30
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times-positive">
      <expr>
        x &lt; 6
      </expr>
    </elem>
  </list>
</reply>

