<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        4*x-12 &gt; 3*x-12
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        3*x
      </argument>
      <expr>
        x-12 &gt; -12
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x &gt; 0
      </expr>
    </elem>
  </list>
</reply>

