<reply result="ok" version="0.7.6 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.balance.con-left-minus" location="[]">
      <argument description="term">
        1
      </argument>
      <state>
        <prefix>
          [7,0,0,1,1,1,1,1,1,0,0]
        </prefix>
        <expr>
          1 == 3*x
        </expr>
      </state>
    </elem>
    <elem ruleid="algebra.equations.linear.flip" location="[]">
      <state>
        <prefix>
          [8,0,0,1,1,1,1,1,1,1,0,0]
        </prefix>
        <expr>
          3*x+1 == 2
        </expr>
      </state>
    </elem>
  </list>
</reply>

