{
   "result": [
      [
         "logic.propositional.idempor",
         "[]",
         [
            "logic.propositional.dnf",
            "[3,1,0,1,1,0]",
            "s || p || q || q || t",
            {
            }
         ]
      ],
      [
         "logic.propositional.idempor",
         "[]",
         [
            "logic.propositional.dnf",
            "[3,1,0,1,1,0]",
            "s || p || p || q || t",
            {
            }
         ]
      ]
   ],
   "error": null,
   "id": 421,
   "version": "0.6.5 (0)"
}
