{
   "result": [
      [
         "IdempOr",
         "[]",
         [
            "logic.propositional.dnf",
            "[0,3,0]",
            "s || p || q || q || t",
            {
            }
         ]
      ],
      [
         "IdempOr",
         "[]",
         [
            "logic.propositional.dnf",
            "[0,3,0]",
            "s || p || p || q || t",
            {
            }
         ]
      ]
   ],
   "error": null,
   "id": 421,
   "version": "0.6.4 (0)"
}
