{
   "result": [
      [
         "logic.propositional.defequiv",
         [
         ],
         "((r /\\ p) || (~r /\\ ~p) || (q -> s)) /\\ (~s <-> (p || r))"
      ],
      [
         "logic.propositional.defequiv",
         [
         ],
         "((r /\\ p) || (~r /\\ ~p) || (q -> s)) /\\ ((~s /\\ (p || r)) || (~~s /\\ ~(p || r)))"
      ],
      [
         "logic.propositional.notnot",
         [
         ],
         "((r /\\ p) || (~r /\\ ~p) || (q -> s)) /\\ ((~s /\\ (p || r)) || (s /\\ ~(p || r)))"
      ],
      [
         "logic.propositional.defimpl",
         [
         ],
         "((r /\\ p) || (~r /\\ ~p) || ~q || s) /\\ ((~s /\\ (p || r)) || (s /\\ ~(p || r)))"
      ],
      [
         "logic.propositional.demorganor",
         [
         ],
         "((r /\\ p) || (~r /\\ ~p) || ~q || s) /\\ ((~s /\\ (p || r)) || (s /\\ ~p /\\ ~r))"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(((r /\\ p) || (~r /\\ ~p) || ~q || s) /\\ ~s /\\ (p || r)) || (((r /\\ p) || (~r /\\ ~p) || ~q || s) /\\ s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.absorpand",
         [
         ],
         "(((r /\\ p) || (~r /\\ ~p) || ~q || s) /\\ ~s /\\ (p || r)) || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(((r /\\ p) || (~r /\\ ~p) || ~q || s) /\\ ~s /\\ p) || (((r /\\ p) || (~r /\\ ~p) || ~q || s) /\\ ~s /\\ r) || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(r /\\ p /\\ ~s /\\ p) || (((~r /\\ ~p) || ~q || s) /\\ ~s /\\ p) || (((r /\\ p) || (~r /\\ ~p) || ~q || s) /\\ ~s /\\ r) || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(r /\\ p /\\ ~s /\\ p) || (~r /\\ ~p /\\ ~s /\\ p) || ((~q || s) /\\ ~s /\\ p) || (((r /\\ p) || (~r /\\ ~p) || ~q || s) /\\ ~s /\\ r) || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(r /\\ p /\\ ~s /\\ p) || (~r /\\ ~p /\\ ~s /\\ p) || (~q /\\ ~s /\\ p) || (s /\\ ~s /\\ p) || (((r /\\ p) || (~r /\\ ~p) || ~q || s) /\\ ~s /\\ r) || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(r /\\ p /\\ ~s /\\ p) || (~r /\\ ~p /\\ ~s /\\ p) || (~q /\\ ~s /\\ p) || (s /\\ ~s /\\ p) || (r /\\ p /\\ ~s /\\ r) || (((~r /\\ ~p) || ~q || s) /\\ ~s /\\ r) || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(r /\\ p /\\ ~s /\\ p) || (~r /\\ ~p /\\ ~s /\\ p) || (~q /\\ ~s /\\ p) || (s /\\ ~s /\\ p) || (r /\\ p /\\ ~s /\\ r) || (~r /\\ ~p /\\ ~s /\\ r) || ((~q || s) /\\ ~s /\\ r) || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.andoveror",
         [
         ],
         "(r /\\ p /\\ ~s /\\ p) || (~r /\\ ~p /\\ ~s /\\ p) || (~q /\\ ~s /\\ p) || (s /\\ ~s /\\ p) || (r /\\ p /\\ ~s /\\ r) || (~r /\\ ~p /\\ ~s /\\ r) || (~q /\\ ~s /\\ r) || (s /\\ ~s /\\ r) || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.compland",
         [
         ],
         "(r /\\ p /\\ ~s /\\ p) || (~r /\\ ~p /\\ ~s /\\ p) || (~q /\\ ~s /\\ p) || (F /\\ p) || (r /\\ p /\\ ~s /\\ r) || (~r /\\ ~p /\\ ~s /\\ r) || (~q /\\ ~s /\\ r) || (s /\\ ~s /\\ r) || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.compland",
         [
         ],
         "(r /\\ p /\\ ~s /\\ p) || (~r /\\ ~p /\\ ~s /\\ p) || (~q /\\ ~s /\\ p) || (F /\\ p) || (r /\\ p /\\ ~s /\\ r) || (~r /\\ ~p /\\ ~s /\\ r) || (~q /\\ ~s /\\ r) || (F /\\ r) || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.falsezeroand",
         [
         ],
         "(r /\\ p /\\ ~s /\\ p) || (~r /\\ ~p /\\ ~s /\\ p) || (~q /\\ ~s /\\ p) || F || (r /\\ p /\\ ~s /\\ r) || (~r /\\ ~p /\\ ~s /\\ r) || (~q /\\ ~s /\\ r) || (F /\\ r) || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.falsezeroand",
         [
         ],
         "(r /\\ p /\\ ~s /\\ p) || (~r /\\ ~p /\\ ~s /\\ p) || (~q /\\ ~s /\\ p) || F || (r /\\ p /\\ ~s /\\ r) || (~r /\\ ~p /\\ ~s /\\ r) || (~q /\\ ~s /\\ r) || F || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.falsezeroor",
         [
         ],
         "(r /\\ p /\\ ~s /\\ p) || (~r /\\ ~p /\\ ~s /\\ p) || (~q /\\ ~s /\\ p) || (r /\\ p /\\ ~s /\\ r) || (~r /\\ ~p /\\ ~s /\\ r) || (~q /\\ ~s /\\ r) || F || (s /\\ ~p /\\ ~r)"
      ],
      [
         "logic.propositional.falsezeroor",
         [
         ],
         "(r /\\ p /\\ ~s /\\ p) || (~r /\\ ~p /\\ ~s /\\ p) || (~q /\\ ~s /\\ p) || (r /\\ p /\\ ~s /\\ r) || (~r /\\ ~p /\\ ~s /\\ r) || (~q /\\ ~s /\\ r) || (s /\\ ~p /\\ ~r)"
      ]
   ],
   "error": null,
   "id": 2805,
   "version": "0.7.3 (0)"
}
