<reply result="ok" version="0.6.4 (0)">
  <list>
    <elem ruleid="simpler polynomial">
      []
      <state>
        <prefix>
          [5,1,0,0,0,1,1,0]
        </prefix>
        <expr>
          x^2-2*x+4 == 0
        </expr>
      </state>
    </elem>
    <elem ruleid="simpler polynomial">
      []
      <state>
        <prefix>
          [5,1,0,0,0,1,1,0]
        </prefix>
        <expr>
          -x^2+2*x-4 == 0
        </expr>
      </state>
    </elem>
    <elem ruleid="abc formula">
      []
      <state>
        <prefix>
          [5,1,0,0,1]
        </prefix>
        <context>
          <item name="clipboard" value="[D==-48, a==-2, b==4, c==-8]"/>
        </context>
        <expr>
          false
        </expr>
      </state>
    </elem>
  </list>
</reply>

