<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="linearalgebra.gaussianelim.scale">
      []
      <argument description="row">
        0
      </argument>
      <argument description="scale factor">
        1/1
      </argument>
      <state>
        <prefix>
          [11,1,1,0]
        </prefix>
        <expr>
          (1 , 3, 4)
(-4, 2, 7)
        </expr>
        <context>
          <item name="columnJ" value="0"/>
        </context>
      </state>
    </elem>
  </list>
</reply>

