<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="same constant factor">
      []
      <state>
        <prefix>
          [0,0,4,1,0,3,0,0]
        </prefix>
        <expr>
          x^2+1/2 == 2+2*x
        </expr>
      </state>
    </elem>
    <elem ruleid="distribution multiplication">
      []
      <state>
        <prefix>
          [0,0,4,1,0,3,5,0]
        </prefix>
        <expr>
          3*x^2+3/2 == 6+6*x
        </expr>
      </state>
    </elem>
  </list>
</reply>

