<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.same-con-factor" location="[]">
      <state>
        <prefix>
          [5,1,1,1,1,1,1,0,0,0]
        </prefix>
        <expr>
          x^2+1/2 == 2+2*x
        </expr>
      </state>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times" location="[]">
      <state>
        <prefix>
          [5,1,1,1,1,1,1,0,1,1,1,0]
        </prefix>
        <expr>
          3*x^2+3/2 == 6+6*x
        </expr>
      </state>
    </elem>
  </list>
</reply>

