<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        x^2-2*x-15 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-2*x-15>=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+3)*(x-5) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-2*x-15>=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -3 or x == 5
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-2*x-15>=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        x &lt;= -3 or x &gt;= 5
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

