<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        x^2-x-6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x-6<=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+2)*(x-3) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x-6<=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -2 or x == 3
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x-6<=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        -2 &lt;= x &lt;= 3
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

