<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="square both sides">
      <expr>
        x-5 == 3-2*x or x-5 == -3+2*x
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        3*x-8 == 0 or x-5 == -3+2*x
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        3*x == 8 or x-5 == -3+2*x
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 8/3 or x-5 == -3+2*x
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x == 8/3 or -x-2 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 8/3 or -x == 2
      </expr>
    </elem>
    <elem ruleid="cover-up negate [vars]">
      <expr>
        x == 8/3 or x == -2
      </expr>
    </elem>
  </list>
</reply>

