<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="linearalgebra.linsystem.scale">
      <argument description="equation">
        0
      </argument>
      <argument description="scale factor">
        1/1
      </argument>
      <expr>
        x+3*y+1 == 2
2*x == 5
      </expr>
    </elem>
    <elem ruleid="linearalgebra.linsystem.eliminate">
      <argument description="equation 1">
        1
      </argument>
      <argument description="equation 2">
        0
      </argument>
      <argument description="scale factor">
        (-2*1)/1
      </argument>
      <expr>
        x+3*y+1 == 2
(-6)*y-2 == 1
      </expr>
    </elem>
    <elem ruleid="linearalgebra.linsystem.scale">
      <argument description="equation">
        1
      </argument>
      <argument description="scale factor">
        1/((-6)*1)
      </argument>
      <expr>
        x+3*y+1 == 2
y+1/3 == -1/6
      </expr>
      <context>
        <item name="covered" value="1"/>
      </context>
    </elem>
    <elem ruleid="linearalgebra.linsystem.scale">
      <argument description="equation">
        1
      </argument>
      <argument description="scale factor">
        1/1
      </argument>
      <expr>
        x+3*y == 1
y == -1/2
      </expr>
      <context>
        <item name="covered" value="1"/>
      </context>
    </elem>
    <elem ruleid="linearalgebra.linsystem.subst">
      <argument description="equation 1">
        0
      </argument>
      <argument description="equation 2">
        1
      </argument>
      <argument description="scale factor">
        -3*1
      </argument>
      <expr>
        x == 5/2
y == -1/2
      </expr>
      <context>
        <item name="covered" value="1"/>
      </context>
    </elem>
    <elem ruleid="linearalgebra.linsystem.scale">
      <argument description="equation">
        0
      </argument>
      <argument description="scale factor">
        1/1
      </argument>
      <expr>
        x == 5/2
y == -1/2
      </expr>
      <context>
        <item name="covered" value="0"/>
      </context>
    </elem>
  </list>
</reply>

