<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="bring a to one">
      <expr>
        x^2+2*x-1/2 == 0
      </expr>
    </elem>
    <elem ruleid="prepare split square">
      <expr>
        x^2+2*x+1 == 3/2
      </expr>
    </elem>
    <elem ruleid="factor left as square">
      <expr>
        (x+1)^2 == 3/2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x+1 == sqrt (3/2) or x+1 == -sqrt (3/2)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == -1+sqrt (3/2) or x+1 == -sqrt (3/2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == -1+sqrt (3/2) or x == -1-sqrt (3/2)
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == -1+1/2*sqrt 6 or x == -1-1/2*sqrt 6
      </expr>
    </elem>
  </list>
</reply>

