<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.power">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="logic1" name="or"/>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMV name="x"/>
            <OMA>
              <OMS cd="arith1" name="root"/>
              <OMI>
                2
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMV name="x"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMA>
                <OMS cd="arith1" name="root"/>
                <OMI>
                  2
                </OMI>
                <OMI>
                  2
                </OMI>
              </OMA>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="algebra.equations.quadratic.approx">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="logic1" name="or"/>
          <OMA>
            <OMS cd="relation1" name="approx"/>
            <OMV name="x"/>
            <OMF dec="1.4142"/>
          </OMA>
          <OMA>
            <OMS cd="relation1" name="approx"/>
            <OMV name="x"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMF dec="1.4142"/>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
  </list>
</reply>

