<reply result="ok" version="0.6.4 (0)">
  <elem ruleid="cover-up power [vars]">
    []
    <state>
      <prefix>
        [0,0,1,4,0]
      </prefix>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="logic1" name="or"/>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMV name="x"/>
            <OMA>
              <OMS cd="arith1" name="root"/>
              <OMF dec="2.4"/>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="relation1" name="eq"/>
            <OMV name="x"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMA>
                <OMS cd="arith1" name="root"/>
                <OMF dec="2.4"/>
                <OMI>
                  2
                </OMI>
              </OMA>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </state>
  </elem>
</reply>

