<reply result="ok" version="0.7.1 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      []
      <state>
        <prefix>
          [5,1,0,0,0,1,1,1,1,0]
        </prefix>
        <expr>
          (x-12)*(x-13) == 0
        </expr>
      </state>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      []
      <state>
        <prefix>
          [5,1,0,0,1]
        </prefix>
        <expr>
          x == 13 or x == 12
        </expr>
        <context>
          <item name="clipboard" value="[D==1, a==1, b==-25, c==156]"/>
        </context>
      </state>
    </elem>
  </list>
</reply>

