<reply result="ok" version="0.7.6 (0)">
  <elem ruleid="algebra.equations.coverup.times" location="[]">
    <state>
      <prefix>
        [6,0,1,1,1,1,1,0]
      </prefix>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="relation1" name="eq"/>
          <OMV name="x"/>
          <OMA>
            <OMS cd="arith1" name="divide"/>
            <OMI>
              5
            </OMI>
            <OMI>
              9
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </state>
  </elem>
</reply>

