<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x-1 == 10 or x-1 == -10
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 11 or x-1 == -10
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 11 or x == -9
      </expr>
    </elem>
  </list>
</reply>

