<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="remove division">
      <expr>
        -2*x+3 == 10*x+12
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -12*x+3 == 12
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -12*x == 9
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -3/4
      </expr>
    </elem>
  </list>
</reply>

