<reply result="ok" version="0.5.10">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        x^2-4*x-12 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-4*x-12>0)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+2)*(x-6) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-4*x-12>0)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -2 or x == 6
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-4*x-12>0)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        x &lt; -2 or x &gt; 6
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

