<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        x^2-x == 12
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x>12)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-x-12 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x>12)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+3)*(x-4) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x>12)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -3 or x == 4
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x>12)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        x &lt; -3 or x &gt; 4
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x>12)]"/>
      </context>
    </elem>
  </list>
</reply>

