<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="distribution">
      <expr>
        40-4*x^2 == -2*x*(2*x+10)
      </expr>
    </elem>
    <elem ruleid="distribution">
      <expr>
        40-4*x^2 == -4*x^2-20*x
      </expr>
    </elem>
    <elem ruleid="cancel terms">
      <expr>
        40 == -20*x
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        -2 == x
      </expr>
    </elem>
    <elem ruleid="flip equation">
      <expr>
        x == -2
      </expr>
    </elem>
  </list>
</reply>

