<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up minus right [one var]">
      <expr>
        11*x^7 == -44
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x^7 == -4
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == -root 4 7
      </expr>
    </elem>
  </list>
</reply>

