<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="cover-up minus right [one var]">
      <expr>
        (2*x+1)^2 == 6
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        2*x+1 == sqrt 6 or 2*x+1 == -sqrt 6
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        2*x == -1+sqrt 6 or 2*x+1 == -sqrt 6
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == (-1+sqrt 6)/2 or 2*x+1 == -sqrt 6
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == (-1+sqrt 6)/2 or 2*x == -1-sqrt 6
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == (-1+sqrt 6)/2 or x == (-1-sqrt 6)/2
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        x == -1/2+sqrt 6/2 or x == -1/2-sqrt 6/2
      </expr>
    </elem>
  </list>
</reply>

