<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        -1/2*x^4 == -81/2
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-1/2*x^4<-81/2)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x^4 == 81
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-1/2*x^4<-81/2)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 3 or x == -3
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-1/2*x^4<-81/2)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        x &lt; -3 or x &gt; 3
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-1/2*x^4<-81/2)]"/>
      </context>
    </elem>
  </list>
</reply>

