<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (x+9)^2 == 8
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x+9 == 2*sqrt 2 or x+9 == -2*sqrt 2
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == -9+2*sqrt 2 or x+9 == -2*sqrt 2
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == -9+2*sqrt 2 or x == -9-2*sqrt 2
      </expr>
    </elem>
  </list>
</reply>

