<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="distribution">
      <expr>
        4*x-16 == 5*(2*x+1)
      </expr>
    </elem>
    <elem ruleid="distribution">
      <expr>
        4*x-16 == 10*x+5
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -6*x-16 == 5
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -6*x == 21
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -7/2
      </expr>
    </elem>
  </list>
</reply>

