<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="all power factors">
      <expr>
        x == 0 or x^2-4*x-9 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == 0 or x == (4+sqrt 52)/2 or x == (4-sqrt 52)/2
      </expr>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == 0 or x == 2+sqrt 13 or x == 2-sqrt 13
      </expr>
    </elem>
  </list>
</reply>

