<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="all power factors">
      <expr>
        x == 0 or x^2 == 3*x+10
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x == 0 or x^2-3*x-10 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        x == 0 or (x+2)*(x-5) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 0 or x == -2 or x == 5
      </expr>
    </elem>
  </list>
</reply>

