<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        1/3*x^6 == 4
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x^6 == 12
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == root 12 6 or x == -root 12 6
      </expr>
    </elem>
  </list>
</reply>

