<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="distribution">
      <expr>
        x^2-3*x == 3*x-6
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-6*x+6 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == (6+sqrt 12)/2 or x == (6-sqrt 12)/2
      </expr>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == 3+sqrt 3 or x == 3-sqrt 3
      </expr>
    </elem>
  </list>
</reply>

