<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up minus right [one var]">
      <expr>
        8*x^2 == 18
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x^2 == 9/4
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt (9/4) or x == -sqrt (9/4)
      </expr>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == 3/2 or x == -3/2
      </expr>
    </elem>
  </list>
</reply>

