<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="nice factors">
      <expr>
        (x-3)*(x-6) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x-3 == 0 or x-6 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == 3 or x-6 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == 3 or x == 6
      </expr>
    </elem>
  </list>
</reply>

