<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        5*(1-4*x)^3 == -625
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (1-4*x)^3 == -125
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        1-4*x == -5
      </expr>
    </elem>
    <elem ruleid="cover-up minus right [one var]">
      <expr>
        4*x == 6
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 3/2
      </expr>
    </elem>
  </list>
</reply>

