<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up minus right [one var]">
      <expr>
        7*x^5 == -42
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x^5 == -6
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == -root 6 5
      </expr>
    </elem>
  </list>
</reply>

