<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="move to left">
      <expr>
        4*x-12+x^2 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x-2)*(x+6) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x-2 == 0 or x+6 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == 2 or x+6 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == 2 or x == -6
      </expr>
    </elem>
  </list>
</reply>

