<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        2*x^3 == 54
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^3>54)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x^3 == 27
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^3>54)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 3
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^3>54)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        x &gt; 3
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^3>54)]"/>
      </context>
    </elem>
  </list>
</reply>

