<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="higher subst">
      <expr>
        3*p^2-14*p-5 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        p == 5 or p == -1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==256, a==3, b==-14, c==-5, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="subst back var">
      <expr>
        x^2 == 5 or x^2 == -1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==256, a==3, b==-14, c==-5, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt 5 or x == -sqrt 5 or x^2 == -1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==256, a==3, b==-14, c==-5, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt 5 or x == -sqrt 5
      </expr>
      <context>
        <item name="clipboard" value="[D==256, a==3, b==-14, c==-5, subst==(p==x^2)]"/>
      </context>
    </elem>
  </list>
</reply>

