<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="reciprocal">
      <expr>
        1/a^2*b^(-3)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="reciprocal">
      <expr>
        1/a^2*(1/b^3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="fraction times">
      <expr>
        1/(a^2*b^3)
      </expr>
    </elem>
  </list>
</reply>

