<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="remove division">
      <expr>
        4*x-5/2 == 5*x+15/2
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -x-5/2 == 15/2
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -x == 10
      </expr>
    </elem>
    <elem ruleid="cover-up negate [vars]">
      <expr>
        x == -10
      </expr>
    </elem>
  </list>
</reply>

