<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="reciprocal">
      <expr>
        (2*a)^(-3)*(1/b^4)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="distribute power">
      <expr>
        1/8*a^(-3)*(1/b^4)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="reciprocal">
      <expr>
        1/(8*a^3)*(1/b^4)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="fraction times">
      <expr>
        1/(8*a^3*b^4)
      </expr>
    </elem>
  </list>
</reply>

