<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="distribute power">
      <expr>
        a^5/(1/4*b^(-2))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="reciprocal">
      <expr>
        a^5/(1/(4*b^2))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="division denominator">
      <expr>
        a^5*4*b^2
      </expr>
    </elem>
  </list>
</reply>

