<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="distribution multiplication">
      <expr>
        x^2+2*x == 8
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2+2*x-8 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x-2)*(x+4) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 2 or x == -4
      </expr>
    </elem>
  </list>
</reply>

