<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="reciprocal">
      <expr>
        1/(5/6*a)^2
      </expr>
    </elem>
    <elem ruleid="distribute power">
      <expr>
        1/(25/36*a^2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="fraction times">
      <expr>
        1/(25*a^2/36)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="division denominator">
      <expr>
        36/(25*a^2)
      </expr>
    </elem>
  </list>
</reply>

