<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="reciprocal">
      <expr>
        (a^3)^4*(1/a)^3
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="mul exponents">
      <expr>
        a^12*(1/a)^3
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="reciprocal">
      <expr>
        a^12*(a^(-1))^3
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
    <elem ruleid="mul exponents">
      <expr>
        a^12*a^(-3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        a^9
      </expr>
    </elem>
  </list>
</reply>

