<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up minus right [one var]">
      <expr>
        1/5*x^7 == -5
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x^7 == -25
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == -root 25 7
      </expr>
    </elem>
  </list>
</reply>

