<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="all power factors">
      <expr>
        x == 0 or x^2-5 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 0 or x^2 == 5
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 0 or x == sqrt 5 or x == -sqrt 5
      </expr>
    </elem>
  </list>
</reply>

