<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="distribution">
      <expr>
        4*x-(x-2) == 12+(5*x-5)
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        3*x+2 == 7+5*x
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -2*x+2 == 7
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -2*x == 5
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -5/2
      </expr>
    </elem>
  </list>
</reply>

