<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="reciprocal">
      <expr>
        3/a^(3/5)*b^(1/3)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="write as root">
      <expr>
        3/root (a^3) 5*b^(1/3)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="write as root">
      <expr>
        3/root (a^3) 5*root b 3
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="fraction times">
      <expr>
        3*root b 3/root (a^3) 5
      </expr>
    </elem>
  </list>
</reply>

