<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up minus right [one var]">
      <expr>
        (2*x-1)^3 == 5
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        2*x-1 == root 5 3
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        2*x == root 5 3+1
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == (root 5 3+1)/2
      </expr>
    </elem>
    <elem ruleid="distribution division">
      <expr>
        x == root 5 3/2+1/2
      </expr>
    </elem>
  </list>
</reply>

