<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="move to left">
      <expr>
        3*x^2-6*x == 0
      </expr>
    </elem>
    <elem ruleid="no constant c">
      <expr>
        3*x*(x-2) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 0 or x-2 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == 0 or x == 2
      </expr>
    </elem>
  </list>
</reply>

