<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="all power factors">
      <expr>
        x == 0 or x^2+2*x == 24
      </expr>
    </elem>
    <elem ruleid="power factor">
      <expr>
        x == 0 or x*(x+2) == 24
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        x == 0 or x^2+2*x == 24
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x == 0 or x^2+2*x-24 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        x == 0 or (x-4)*(x+6) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 0 or x == 4 or x == -6
      </expr>
    </elem>
  </list>
</reply>

