<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="distribution square">
      <expr>
        1-2*x+x^2 == x+2
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-3*x-1 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == (3+sqrt 13)/2 or x == (3-sqrt 13)/2
      </expr>
    </elem>
    <elem ruleid="distribution">
      <expr>
        x == 3/2+sqrt 13/2 or x == 3/2-sqrt 13/2
      </expr>
    </elem>
  </list>
</reply>

