<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        2*x^2-10*x == x^2-3*x
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^2-10*x>x^2-3*x)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-7*x == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^2-10*x>x^2-3*x)]"/>
      </context>
    </elem>
    <elem ruleid="common factor var">
      <expr>
        x*(x-7) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^2-10*x>x^2-3*x)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 0 or x == 7
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^2-10*x>x^2-3*x)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        x &lt; 0 or x &gt; 7
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^2-10*x>x^2-3*x)]"/>
      </context>
    </elem>
  </list>
</reply>

