<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="distribution multiplication">
      <expr>
        4-5*x+x^2 == 3*x
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-8*x+4 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == (8+sqrt 48)/2 or x == (8-sqrt 48)/2
      </expr>
      <context>
        <item name="clipboard" value="[D==48, a==1, b==-8, c==4]"/>
      </context>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == 4+2*sqrt 3 or x == 4-2*sqrt 3
      </expr>
      <context>
        <item name="clipboard" value="[D==48, a==1, b==-8, c==4]"/>
      </context>
    </elem>
  </list>
</reply>

