<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="cover-up times [vars]">
      <expr>
        17-x^2 == 8
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -x^2 == -9
      </expr>
    </elem>
    <elem ruleid="cover-up negate [vars]">
      <expr>
        x^2 == 9
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 3 or x == -3
      </expr>
    </elem>
  </list>
</reply>

