<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="remove division">
      <expr>
        8*x-5 == 10*x+15
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -2*x-5 == 15
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        -2*x == 20
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -10
      </expr>
    </elem>
  </list>
</reply>

