<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="move to left">
      <expr>
        x^2+8*x-15 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == (-8+sqrt 124)/2 or x == (-8-sqrt 124)/2
      </expr>
      <context>
        <item name="clipboard" value="[D==124, a==1, b==8, c==-15]"/>
      </context>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == -4+sqrt 31 or x == -4-sqrt 31
      </expr>
      <context>
        <item name="clipboard" value="[D==124, a==1, b==8, c==-15]"/>
      </context>
    </elem>
  </list>
</reply>

