<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="reciprocal">
      <expr>
        4*a^(1/2)/b^(1/5)
      </expr>
    </elem>
    <elem ruleid="write as root">
      <expr>
        4*sqrt a/b^(1/5)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="write as root">
      <expr>
        4*sqrt a/root b 5
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

