<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        -x^2+3*x+18 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2+3*x+18>0)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+3)*(x-6) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2+3*x+18>0)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -3 or x == 6
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2+3*x+18>0)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        -3 &lt; x &lt; 6
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2+3*x+18>0)]"/>
      </context>
    </elem>
  </list>
</reply>

