<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="write as power">
      <expr>
        a^2*a^(1/5)/(a^3*root a 3)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        a^(11/5)/(a^3*root a 3)
      </expr>
    </elem>
    <elem ruleid="write as power">
      <expr>
        a^(11/5)/(a^3*a^(1/3))
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        a^(11/5)/a^(10/3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="sub exponents">
      <expr>
        a^(-17/15)
      </expr>
    </elem>
  </list>
</reply>

