<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="simpler polynomial">
      <expr>
        x^2+2*x-4 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == (-2+sqrt 20)/2 or x == (-2-sqrt 20)/2
      </expr>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == -1+sqrt 5 or x == -1-sqrt 5
      </expr>
    </elem>
  </list>
</reply>

