<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="distribute power">
      <expr>
        4*(a^3)^2+6*(3*a)^2*(4*a^4)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="mul exponents">
      <expr>
        4*a^6+6*(3*a)^2*(4*a^4)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="distribute power">
      <expr>
        4*a^6+54*a^2*(4*a^4)
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        4*a^6+216*a^6
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="calculate power plus">
      <expr>
        220*a^6
      </expr>
    </elem>
  </list>
</reply>

