<reply result="ok" version="0.5.8">
  <list>
    <elem ruleid="variable to left">
      <expr>
        2*x-12 &lt; 3
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        2*x &lt; 15
      </expr>
    </elem>
    <elem ruleid="cover-up times positive [vars]">
      <expr>
        x &lt; 15/2
      </expr>
    </elem>
  </list>
</reply>

