<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="remove division">
      <expr>
        5*x-1-12 == -24*x+3*(3*x-6)
      </expr>
    </elem>
    <elem ruleid="distribution">
      <expr>
        5*x-1-12 == -24*x+(9*x-18)
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        5*x-13 == -15*x-18
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        20*x-13 == -18
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        20*x == -5
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -1/4
      </expr>
    </elem>
  </list>
</reply>

