<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        (2*x-3)^4 == 1
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        2*x-3 == 1 or 2*x-3 == -1
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        2*x == 4 or 2*x-3 == -1
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 2 or 2*x-3 == -1
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 2 or 2*x == 2
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 2 or x == 1
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        x &lt; 1 or x &gt; 2
      </expr>
      <context>
        <item name="clipboard" value="[ineq==((2*x-3)^4>1)]"/>
      </context>
    </elem>
  </list>
</reply>

