<reply result="ok" version="0.5.8">
  <list>
    <elem ruleid="distribution multiplication">
      <expr>
        6*a+6 &lt; 3*a-6+4
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        6*a+6 &lt; 3*a-2
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        3*a+6 &lt; -2
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        3*a &lt; -8
      </expr>
    </elem>
    <elem ruleid="cover-up times positive [vars]">
      <expr>
        a &lt; -8/3
      </expr>
    </elem>
  </list>
</reply>

