<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="reciprocal">
      <expr>
        a^(-2)/b^3
      </expr>
    </elem>
    <elem ruleid="reciprocal">
      <expr>
        1/a^2/b^3
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="division numerator">
      <expr>
        1/(a^2*b^3)
      </expr>
    </elem>
  </list>
</reply>

