<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="mul exponents">
      <expr>
        (-2*a^6)^2+a^12
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="distribute power">
      <expr>
        4*(a^6)^2+a^12
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="mul exponents">
      <expr>
        4*a^12+a^12
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculate power plus">
      <expr>
        5*a^12
      </expr>
    </elem>
  </list>
</reply>

