<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="move to left">
      <expr>
        3*x^2-6*x-9 == 0
      </expr>
    </elem>
    <elem ruleid="simpler polynomial">
      <expr>
        x^2-2*x-3 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+1)*(x-3) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -1 or x == 3
      </expr>
    </elem>
  </list>
</reply>

