<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="distribution multiplication">
      <expr>
        x^2-5*x+4 == 11
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-5*x-7 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == (5+sqrt 53)/2 or x == (5-sqrt 53)/2
      </expr>
    </elem>
    <elem ruleid="distribution division">
      <expr>
        x == 5/2+sqrt 53/2 or x == 5/2-sqrt 53/2
      </expr>
    </elem>
  </list>
</reply>

