<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="remove division">
      <expr>
        -4*x+9 == 3*x+2
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -7*x+9 == 2
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -7*x == -7
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 1
      </expr>
    </elem>
  </list>
</reply>

