<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        -2*x^2+10*x == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-2*x^2+10*x>0)]"/>
      </context>
    </elem>
    <elem ruleid="common factor var">
      <expr>
        2*x*(-x+5) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-2*x^2+10*x>0)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 0 or x == 5
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-2*x^2+10*x>0)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        0 &lt; x &lt; 5
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-2*x^2+10*x>0)]"/>
      </context>
    </elem>
  </list>
</reply>

