<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        3*(2*x+7)^3 == 24
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (2*x+7)^3 == 8
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        2*x+7 == 2
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        2*x == -5
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -5/2
      </expr>
    </elem>
  </list>
</reply>

