<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="write as power">
      <expr>
        a^3*a^(1/2)/(a^2*root (a^2) 3)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        a^(7/2)/(a^2*root (a^2) 3)
      </expr>
    </elem>
    <elem ruleid="write as power">
      <expr>
        a^(7/2)/(a^2*a^(2/3))
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        a^(7/2)/a^(8/3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="sub exponents">
      <expr>
        a^(5/6)
      </expr>
    </elem>
  </list>
</reply>

