<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="all power factors">
      <expr>
        x == 0 or 14 == x^2+5*x
      </expr>
    </elem>
    <elem ruleid="flip equation">
      <expr>
        x == 0 or x^2+5*x == 14
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x == 0 or x^2+5*x-14 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        x == 0 or (x-2)*(x+7) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 0 or x == 2 or x == -7
      </expr>
    </elem>
  </list>
</reply>

