<reply result="ok" version="0.5.10">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        -x^2-4*x+5 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2-4*x+5<0)]"/>
      </context>
    </elem>
    <elem ruleid="simpler polynomial">
      <expr>
        x^2+4*x-5 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2-4*x+5<0)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x-1)*(x+5) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2-4*x+5<0)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 1 or x == -5
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2-4*x+5<0)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        x &lt; -5 or x &gt; 1
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

