<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="distribution square">
      <expr>
        3*x^2-11 == 9+12*x+4*x^2
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        3*x^2-20-12*x-4*x^2 == 0
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        -x^2-20-12*x == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+2)*(x+10) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x+2 == 0 or x+10 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == -2 or x+10 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == -2 or x == -10
      </expr>
    </elem>
  </list>
</reply>

