<reply result="ok" version="0.5.10">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        1/4*(1/2*x-2)^4 == 4
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(1/4*(1/2*x-2)^4<4)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (1/2*x-2)^4 == 16
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(1/4*(1/2*x-2)^4<4)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        1/2*x-2 == 2 or 1/2*x-2 == -2
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(1/4*(1/2*x-2)^4<4)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        1/2*x == 4 or 1/2*x-2 == -2
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(1/4*(1/2*x-2)^4<4)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 8 or 1/2*x-2 == -2
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(1/4*(1/2*x-2)^4<4)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 8 or 1/2*x == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(1/4*(1/2*x-2)^4<4)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 8 or x == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(1/4*(1/2*x-2)^4<4)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        0 &lt; x &lt; 8
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

