<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        2*x^2+6*x-10 == x^2+2*x-5
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^2+6*x-10>x^2+2*x-5)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2+4*x-5 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^2+6*x-10>x^2+2*x-5)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x-1)*(x+5) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^2+6*x-10>x^2+2*x-5)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 1 or x == -5
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^2+6*x-10>x^2+2*x-5)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        x &lt; -5 or x &gt; 1
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(2*x^2+6*x-10>x^2+2*x-5)]"/>
      </context>
    </elem>
  </list>
</reply>

