<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        4*x^2+6*x == x^2+3*x+18
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(4*x^2+6*x<x^2+3*x+18)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        3*x^2+3*x-18 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(4*x^2+6*x<x^2+3*x+18)]"/>
      </context>
    </elem>
    <elem ruleid="simpler polynomial">
      <expr>
        x^2+x-6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(4*x^2+6*x<x^2+3*x+18)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x-2)*(x+3) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(4*x^2+6*x<x^2+3*x+18)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 2 or x == -3
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(4*x^2+6*x<x^2+3*x+18)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        -3 &lt; x &lt; 2
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(4*x^2+6*x<x^2+3*x+18)]"/>
      </context>
    </elem>
  </list>
</reply>

