<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="remove division">
      <expr>
        -3*(x+2) == 54*(2/3*x+1/3)-10
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        -3*x-6 == 36*x+18-10
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        -3*x-6 == 36*x+8
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -39*x-6 == 8
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        -39*x == 14
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -14/39
      </expr>
    </elem>
  </list>
</reply>

