<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="remove division">
      <expr>
        -x+4 == 12+10*(x-1)
      </expr>
    </elem>
    <elem ruleid="distribution">
      <expr>
        -x+4 == 12+10*x-10
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        -x+4 == 2+10*x
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -11*x+4 == 2
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -11*x == -2
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 2/11
      </expr>
    </elem>
  </list>
</reply>

