<reply result="ok" version="0.5.8">
  <list>
    <elem ruleid="variable to left">
      <expr>
        -4*x+1 &lt; 5
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -4*x &lt; 4
      </expr>
    </elem>
    <elem ruleid="flip sign">
      <expr>
        4*x &gt; -4
      </expr>
    </elem>
    <elem ruleid="cover-up times positive [vars]">
      <expr>
        x &gt; -1
      </expr>
    </elem>
  </list>
</reply>

