<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        2*(1/2*x+3)^7 == 2
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (1/2*x+3)^7 == 1
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        1/2*x+3 == 1
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        1/2*x == -2
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -4
      </expr>
    </elem>
  </list>
</reply>

