<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        3*(2*x-1)^3 == 648
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (2*x-1)^3 == 216
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        2*x-1 == 6
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        2*x == 7
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 7/2
      </expr>
    </elem>
  </list>
</reply>

