<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="reciprocal">
      <expr>
        1/(3*a)^(3/5)
      </expr>
    </elem>
    <elem ruleid="write as root">
      <expr>
        1/root ((3*a)^3) 5
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="distribute power">
      <expr>
        1/root (27*a^3) 5
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
  </list>
</reply>

