<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="move to left">
      <expr>
        x^2-6*x-4 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == (6+sqrt 52)/2 or x == (6-sqrt 52)/2
      </expr>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == 3+sqrt 13 or x == 3-sqrt 13
      </expr>
    </elem>
  </list>
</reply>

