<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        x^2+9*x == 3*x-5
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2+9*x<3*x-5)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2+6*x+5 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2+9*x<3*x-5)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+1)*(x+5) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2+9*x<3*x-5)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -1 or x == -5
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2+9*x<3*x-5)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        -5 &lt; x &lt; -1
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2+9*x<3*x-5)]"/>
      </context>
    </elem>
  </list>
</reply>

