<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        1/2*(3*x-4)^5 == 16
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (3*x-4)^5 == 32
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        3*x-4 == 2
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        3*x == 6
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 2
      </expr>
    </elem>
  </list>
</reply>

