<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="remove division">
      <expr>
        -x+3/2 == 5*x+6
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -6*x+3/2 == 6
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -6*x == 9/2
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -3/4
      </expr>
    </elem>
  </list>
</reply>

