<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="higher subst">
      <expr>
        3*p^2-80*p-27 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        p == 27 or p == -1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==6724, a==3, b==-80, c==-27, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="subst back var">
      <expr>
        x^3 == 27 or x^3 == -1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==6724, a==3, b==-80, c==-27, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 3 or x^3 == -1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==6724, a==3, b==-80, c==-27, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 3 or x == -1/root 3 3
      </expr>
      <context>
        <item name="clipboard" value="[D==6724, a==3, b==-80, c==-27, subst==(p==x^3)]"/>
      </context>
    </elem>
  </list>
</reply>

