<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="reciprocal">
      <expr>
        9/a^7*(2*b)^(-4)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="distribute power">
      <expr>
        9/(16*a^7)*b^(-4)
      </expr>
    </elem>
    <elem ruleid="reciprocal">
      <expr>
        9/(16*a^7)*(1/b^4)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="fraction times">
      <expr>
        9/(16*a^7*b^4)
      </expr>
    </elem>
  </list>
</reply>

