<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="mul exponents">
      <expr>
        1/a^(-3)*b^(-4)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="reciprocal">
      <expr>
        1/(1/a^3)*b^(-4)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="reciprocal">
      <expr>
        1/(1/a^3)*(1/b^4)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="fraction times">
      <expr>
        a^3/b^4
      </expr>
    </elem>
  </list>
</reply>

