<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        4*(1/2*x+2)^6 == 4
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (1/2*x+2)^6 == 1
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        1/2*x+2 == 1 or 1/2*x+2 == -1
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        1/2*x == -1 or 1/2*x+2 == -1
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -2 or 1/2*x+2 == -1
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == -2 or 1/2*x == -3
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -2 or x == -6
      </expr>
    </elem>
  </list>
</reply>

