<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.factor-varpower">
      <expr>
        (a^2-2*a-15)/(a*(a^2-3*a-10))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (a^2-2*a-15)/(a*((a+2)*(a-5)))
      </expr>
      <context>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (a+3)*(a-5)/(a*((a+2)*(a-5)))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cancel terms div">
      <expr>
        (a+3)/(a*(a+2))
      </expr>
      <context>
        <item name="clipboard" value="[condition==(a/=5)]"/>
      </context>
    </elem>
  </list>
</reply>

