<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.factor-varpower">
      <expr>
        (x^2+3*x-4)/(x*(x^2-6*x+5))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x^2+3*x-4)/(x*(x-1)*(x-5))
      </expr>
      <context>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x-1)*(x+4)/(x*(x-1)*(x-5))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        (x+4)/(x*(x-5))
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
  </list>
</reply>

