<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.rational-scale">
      <expr>
        (x+3)*3/((x-1)*(x+3))+(x-1)*2/((x-1)*(x+3))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.rational.rational-plus">
      <expr>
        ((x+3)*3+(x-1)*2)/((x-1)*(x+3))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (3*x+9+2*x-2)/((x-1)*(x+3))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (5*x+7)/((x-1)*(x+3))
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
  </list>
</reply>

