<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="nice factors">
      <expr>
        (x^3+10*x^2+24*x)/((x+1)*(x+6))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="factor variable power">
      <expr>
        x*(x^2+10*x+24)/((x+1)*(x+6))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        x*((x+4)*(x+6))/((x+1)*(x+6))
      </expr>
      <context>
        <item name="location" value="[1,2]"/>
      </context>
    </elem>
    <elem ruleid="cancel terms div">
      <expr>
        x*(x+4)/(x+1)
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        (x^2+4*x)/(x+1)
      </expr>
    </elem>
  </list>
</reply>

