<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.rational-scale">
      <expr>
        (x-3)*4/((x+5)*(x-3))+(x+5)*2/((x+5)*(x-3))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.rational.rational-plus">
      <expr>
        ((x-3)*4+(x+5)*2)/((x+5)*(x-3))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (4*x-12+2*x+10)/((x+5)*(x-3))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (6*x-2)/((x+5)*(x-3))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

