<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="common factor var">
      <expr>
        (p^2-12*p+36)/(p*(p-6))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (p-6)^2/(p*(p-6))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cancel terms div">
      <expr>
        (p-6)/p
      </expr>
    </elem>
  </list>
</reply>

