<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x^2-9)/(x+3)^2
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+3)*(x-3)/(x+3)^2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        (x-3)/(x+3)
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-3)]"/>
      </context>
    </elem>
  </list>
</reply>

