<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="fraction scale">
      <expr>
        (x-2)*(x-1)/((x+1)*(x-2))+(x+1)*(-x-2)/((x+1)*(x-2))
      </expr>
    </elem>
    <elem ruleid="fraction plus">
      <expr>
        ((x-2)*(x-1)+(x+1)*(-x-2))/((x+1)*(x-2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (x^2-3*x+2-x^2-3*x-2)/((x+1)*(x-2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        -6*x/((x+1)*(x-2))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

