<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.rational-scale">
      <expr>
        (x+4)*(x-3)/((x-1)*(x+4))+(x-1)*(-x-2)/((x-1)*(x+4))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.rational.rational-plus">
      <expr>
        ((x+4)*(x-3)+(x-1)*(-x-2))/((x-1)*(x+4))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (x^2+x-12-x^2-x+2)/((x-1)*(x+4))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        -10/((x-1)*(x+4))
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
  </list>
</reply>

