<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (a^3+7*a^2+12*a)/(a+3)^2
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.factor-varpower">
      <expr>
        a*(a^2+7*a+12)/(a+3)^2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        a*(a+3)*(a+4)/(a+3)^2
      </expr>
      <context>
        <item name="location" value="[1,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        a*(a+4)/(a+3)
      </expr>
      <context>
        <item name="clipboard" value="[condition==(a/=-3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (a^2+4*a)/(a+3)
      </expr>
      <context>
        <item name="clipboard" value="[condition==(a/=-3)]"/>
      </context>
    </elem>
  </list>
</reply>

