<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (a^2-3*a-10)/((a+4)*(a-5))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (a+2)*(a-5)/((a+4)*(a-5))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        (a+2)/(a+4)
      </expr>
      <context>
        <item name="clipboard" value="[condition==(a/=5)]"/>
      </context>
    </elem>
  </list>
</reply>

