<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (2*p^2+8*p)/((p+4)*(p-4))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.common-factor">
      <expr>
        2*p*(p+4)/((p+4)*(p-4))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        2*p/(p-4)
      </expr>
      <context>
        <item name="clipboard" value="[condition == (p /= -4)]"/>
      </context>
    </elem>
  </list>
</reply>

