<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x^2+4*x-5)/((x-1)*(x+6))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x-1)*(x+5)/((x-1)*(x+6))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cancel terms div">
      <expr>
        (x+5)/(x+6)
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=1)]"/>
      </context>
    </elem>
  </list>
</reply>

