<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (a^2-2*a-15)/((a+3)*(a-6))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (a+3)*(a-5)/((a+3)*(a-6))
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        (a-5)/(a-6)
      </expr>
      <context>
        <item name="clipboard" value="[condition == (a /= -3)]"/>
      </context>
    </elem>
  </list>
</reply>

