<reply result="ok" version="0.6.3 (0)">
  <list>
    <elem ruleid="nice factors">
      <expr>
        (a^2-a-2)/((a-2)*(a+6))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (a+1)*(a-2)/((a-2)*(a+6))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cancel terms div">
      <expr>
        (a+1)/(a+6)
      </expr>
      <context>
        <item name="clipboard" value="[condition==(a/=2)]"/>
      </context>
    </elem>
  </list>
</reply>

