<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="nice factors">
      <expr>
        (a^3+7*a^2+10*a)/((a+2)*(a-3))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="factor variable power">
      <expr>
        a*(a^2+7*a+10)/((a+2)*(a-3))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        a*((a+2)*(a+5))/((a+2)*(a-3))
      </expr>
      <context>
        <item name="location" value="[1,2]"/>
      </context>
    </elem>
    <elem ruleid="cancel terms div">
      <expr>
        a*(a+5)/(a-3)
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        (a^2+5*a)/(a-3)
      </expr>
    </elem>
  </list>
</reply>

