<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x^2-16)/((x-3)*(x+4))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+4)*(x-4)/((x-3)*(x+4))
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        (x-4)/(x-3)
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= -4)]"/>
      </context>
    </elem>
  </list>
</reply>

