<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.rational-scale">
      <expr>
        (x-2)*(3*x)/((x-4)*(x-2))+(x-4)*(5*x)/((x-4)*(x-2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.rational.rational-plus">
      <expr>
        ((x-2)*(3*x)+(x-4)*(5*x))/((x-4)*(x-2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (3*x^2-6*x+5*x^2-20*x)/((x-4)*(x-2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (8*x^2-26*x)/((x-4)*(x-2))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

