<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x^2+2*x-8)/((x+4)*(x+6))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x-2)*(x+4)/((x+4)*(x+6))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cancel terms div">
      <expr>
        (x-2)/(x+6)
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-4)]"/>
      </context>
    </elem>
  </list>
</reply>

