<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="fraction scale">
      <expr>
        (x-4)/((x+5)*(x-4))-(x+5)*3/((x+5)*(x-4))
      </expr>
    </elem>
    <elem ruleid="fraction plus">
      <expr>
        (x-4-(x+5)*3)/((x+5)*(x-4))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (x-4-3*x-15)/((x+5)*(x-4))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (-2*x-19)/((x+5)*(x-4))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

