<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="fraction scale">
      <expr>
        (x-3)*3/((x-2)*(x-3))+(x-2)*2/((x-2)*(x-3))
      </expr>
    </elem>
    <elem ruleid="fraction plus">
      <expr>
        ((x-3)*3+(x-2)*2)/((x-2)*(x-3))
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        (3*x-9+2*x-4)/((x-2)*(x-3))
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        (5*x-13)/((x-2)*(x-3))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

