<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="fraction scale">
      <expr>
        (x+3)*5/((x+2)*(x+3))+(x+2)*4/((x+2)*(x+3))
      </expr>
    </elem>
    <elem ruleid="fraction plus">
      <expr>
        ((x+3)*5+(x+2)*4)/((x+2)*(x+3))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (5*x+15+4*x+8)/((x+2)*(x+3))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (9*x+23)/((x+2)*(x+3))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

