<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.rational-scale">
      <expr>
        (x-2)*6/((x-1)*(x-2))-(x-1)*3/((x-1)*(x-2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.rational.rational-plus">
      <expr>
        ((x-2)*6-(x-1)*3)/((x-1)*(x-2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (6*x-12-3*x+3)/((x-1)*(x-2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (3*x-9)/((x-1)*(x-2))
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
  </list>
</reply>

