<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x^3+10*x^2+24*x)/((x+1)*(x+6))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.factor-varpower">
      <expr>
        x*(x^2+10*x+24)/((x+1)*(x+6))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        x*(x+4)*(x+6)/((x+1)*(x+6))
      </expr>
      <context>
        <item name="location" value="[1,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        x*(x+4)/(x+1)
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= -6)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (x^2+4*x)/(x+1)
      </expr>
      <context>
        <item name="clipboard" value="[condition == (x /= -6)]"/>
      </context>
    </elem>
  </list>
</reply>

