<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x^3+3*x^2+2*x)/(x+2)^2
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.factor-varpower">
      <expr>
        x*(x^2+3*x+2)/(x+2)^2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        x*(x+1)*(x+2)/(x+2)^2
      </expr>
      <context>
        <item name="location" value="[1,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        x*(x+1)/(x+2)
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (x^2+x)/(x+2)
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-2)]"/>
      </context>
    </elem>
  </list>
</reply>

