<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.factor-varpower">
      <expr>
        (x^2+5*x+6)/(x*(x^2-x-6))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x^2+5*x+6)/(x*(x+2)*(x-3))
      </expr>
      <context>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+2)*(x+3)/(x*(x+2)*(x-3))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        (x+3)/(x*(x-3))
      </expr>
      <context>
        <item name="clipboard" value="[condition==(x/=-2)]"/>
      </context>
    </elem>
  </list>
</reply>

