<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.common-factor">
      <expr>
        (p^2-4)/(4*p*(p+2))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (p+2)*(p-2)/(4*p*(p+2))
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        (p-2)/(4*p)
      </expr>
      <context>
        <item name="clipboard" value="[condition == (p /= -2)]"/>
      </context>
    </elem>
  </list>
</reply>

