<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.common-factor">
      <expr>
        (p^2-12*p+36)/(p*(p-6))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (p-6)^2/(p*(p-6))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        (p-6)/p
      </expr>
      <context>
        <item name="clipboard" value="[condition == (p /= 6)]"/>
      </context>
    </elem>
  </list>
</reply>

