<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="fraction scale">
      <expr>
        (x+2)*4/((x+3)*(x+2))-(x+3)*6/((x+3)*(x+2))
      </expr>
    </elem>
    <elem ruleid="fraction plus">
      <expr>
        ((x+2)*4-(x+3)*6)/((x+3)*(x+2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (4*x+8-6*x-18)/((x+3)*(x+2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (-2*x-10)/((x+3)*(x+2))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

