<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="fraction scale">
      <expr>
        (x-3)*(x-4)/((x+5)*(x-3))+(x+5)*(x-2)/((x+5)*(x-3))
      </expr>
    </elem>
    <elem ruleid="fraction plus">
      <expr>
        ((x-3)*(x-4)+(x+5)*(x-2))/((x+5)*(x-3))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (x^2-7*x+12+x^2+3*x-10)/((x+5)*(x-3))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (2*x^2-4*x+2)/((x+5)*(x-3))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

