<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (a^3+7*a^2+10*a)/((a+2)*(a-3))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.factor-varpower">
      <expr>
        a*(a^2+7*a+10)/((a+2)*(a-3))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        a*(a+2)*(a+5)/((a+2)*(a-3))
      </expr>
      <context>
        <item name="location" value="[1,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.rational.cancel-div">
      <expr>
        a*(a+5)/(a-3)
      </expr>
      <context>
        <item name="clipboard" value="[condition==(a/=-2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (a^2+5*a)/(a-3)
      </expr>
      <context>
        <item name="clipboard" value="[condition==(a/=-2)]"/>
      </context>
    </elem>
  </list>
</reply>

