<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="algebra.equations.rational.rational-scale">
      <expr>
        (x+2)*2*x/((x-1)*(x+2))+(x-1)*x/((x-1)*(x+2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.rational.rational-plus">
      <expr>
        ((x+2)*2*x+(x-1)*x)/((x-1)*(x+2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (2*x^2+4*x+x^2-x)/((x-1)*(x+2))
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (3*x^2+3*x)/((x-1)*(x+2))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

