<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (a^2-2*a-15)/((a+3)*(a-6))
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (a+3)*(a-5)/((a+3)*(a-6))
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cancel terms div">
      <expr>
        (a-5)/(a-6)
      </expr>
      <context>
        <item name="clipboard" value="[condition==(a/=-3)]"/>
      </context>
    </elem>
  </list>
</reply>

