<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        x^2 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2<=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2<=0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        x == 0
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

