<reply result="ok" version="0.5.12">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        x^2-x-7 == -100
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x-7>-100)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-x+93 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x-7>-100)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        false
      </expr>
      <context>
        <item name="clipboard" value="[D==-371, a==1, b==-1, c==93, ineq==(x^2-x-7>-100)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        true
      </expr>
      <context>
        <item name="clipboard" value="[D==-371, a==1, b==-1, c==93]"/>
      </context>
    </elem>
  </list>
</reply>

