<reply result="ok" version="0.5.10">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        x^2-4*x-12 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-4*x-12>0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+2)*(x-6) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-4*x-12>0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -2 or x == 6
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-4*x-12>0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        x &lt; -2 or x &gt; 6
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

