<reply result="ok" version="0.5.14">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        1/2*x^2-3*x-8 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(1/2*x^2-3*x-8<0)]"/>
      </context>
    </elem>
    <elem ruleid="simpler polynomial">
      <expr>
        x^2-6*x-16 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(1/2*x^2-3*x-8<0)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+2)*(x-8) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(1/2*x^2-3*x-8<0)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -2 or x == 8
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(1/2*x^2-3*x-8<0)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        -2 &lt; x &lt; 8
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

