<reply result="ok" version="0.5.10">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        -x^2-4*x+5 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2-4*x+5<0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-poly">
      <expr>
        x^2+4*x-5 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2-4*x+5<0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x-1)*(x+5) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2-4*x+5<0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 1 or x == -5
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2-4*x+5<0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        x &lt; -5 or x &gt; 1
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

