<reply result="ok" version="1.0.7 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        x^2+3*x-4 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (x^2+3*x-4 &lt; 0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x-1)*(x+4) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (x^2+3*x-4 &lt; 0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 1 or x == -4
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (x^2+3*x-4 &lt; 0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        -4 &lt; x &lt; 1
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

