<reply result="ok" version="0.5.14">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        x^2-9/2*x == 7-3*x
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-9/2*x<7-3*x)]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-3/2*x-7 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-9/2*x<7-3*x)]"/>
      </context>
    </elem>
    <elem ruleid="simpler polynomial">
      <expr>
        2*x^2-3*x-14 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-9/2*x<7-3*x)]"/>
      </context>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == 7/2 or x == -2
      </expr>
      <context>
        <item name="clipboard" value="[D==121, a==2, b==-3, c==-14, ineq==(x^2-9/2*x<7-3*x)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        -2 &lt; x &lt; 7/2
      </expr>
      <context>
        <item name="clipboard" value="[D==121, a==2, b==-3, c==-14]"/>
      </context>
    </elem>
  </list>
</reply>

