<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        2*x^2+6*x-10 == x^2+2*x-5
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (2*x^2+6*x-10 > x^2+2*x-5)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2+4*x-5 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (2*x^2+6*x-10 > x^2+2*x-5)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x-1)*(x+5) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (2*x^2+6*x-10 > x^2+2*x-5)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 1 or x == -5
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (2*x^2+6*x-10 > x^2+2*x-5)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        x &lt; -5 or x &gt; 1
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

