<reply result="ok" version="0.5.10">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        x^2-x == 12
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x>12)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-x-12 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x>12)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+3)*(x-4) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x>12)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -3 or x == 4
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2-x>12)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        x &lt; -3 or x &gt; 4
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

