<reply result="ok" version="0.5.10">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        -x^2+3*x+18 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2+3*x+18>0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-poly">
      <expr>
        x^2-3*x-18 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2+3*x+18>0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+3)*(x-6) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2+3*x+18>0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -3 or x == 6
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-x^2+3*x+18>0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        -3 &lt; x &lt; 6
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

