<reply result="ok" version="1.0.7 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        1/2*x^2-3*x-8 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1/2*x^2-3*x-8 &lt; 0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-poly">
      <expr>
        x^2-6*x-16 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1/2*x^2-3*x-8 &lt; 0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+2)*(x-8) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1/2*x^2-3*x-8 &lt; 0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -2 or x == 8
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (1/2*x^2-3*x-8 &lt; 0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        -2 &lt; x &lt; 8
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

