<reply result="ok" version="0.5.12">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        x^2 == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2<=0)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2<=0)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        x == 0
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

