<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="turn into equation">
      <expr>
        true
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(x^2<x^2)]"/>
      </context>
    </elem>
    <elem ruleid="solution inequation">
      <expr>
        false
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

