<reply result="ok" version="0.7.9 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        -2*x^2+10*x == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-2*x^2+10*x>0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.common-factor">
      <expr>
        -2*x*(x-5) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-2*x^2+10*x>0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 0 or x == 5
      </expr>
      <context>
        <item name="clipboard" value="[ineq==(-2*x^2+10*x>0)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        0 &lt; x &lt; 5
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

