<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.inequalities.to-equation">
      <expr>
        2*x^2-10*x == x^2-3*x
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (2*x^2-10*x > x^2-3*x)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-7*x == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (2*x^2-10*x > x^2-3*x)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.common-factor">
      <expr>
        x*(x-7) == 0
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (2*x^2-10*x > x^2-3*x)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 0 or x == 7
      </expr>
      <context>
        <item name="clipboard" value="[ineq == (2*x^2-10*x > x^2-3*x)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.inequalities.give-solution">
      <expr>
        x &lt; 0 or x &gt; 7
      </expr>
      <context>
        <item name="clipboard" value="[]"/>
      </context>
    </elem>
  </list>
</reply>

