-- Automatically generated by Makefile.  Do not change.
module Ideas.Main.Revision where

ideasVersion :: String
ideasVersion = "1.8"

ideasRevision :: String
ideasRevision = "6ed63bb8d0f08b17fcedc033b06da0d3fc2018a1"

ideasLastChanged :: String
ideasLastChanged = "Wed Aug 14 14:52:07 2019 +0200"
