-- Automatically generated by Makefile.  Do not change.
module Ideas.Main.Revision where
version :: String
version = "1.0.11"
revision :: Int
revision = 0
lastChanged :: String 
lastChanged = "unknown"
