-- Automatically generated by Makefile.  Do not change.
module Ideas.Main.Revision where

ideasVersion :: String
ideasVersion = "1.8.1"

ideasRevision :: String
ideasRevision = "27a352d26571dad5913f9786c09ce5cda3021793"

ideasLastChanged :: String
ideasLastChanged = "Thu Sep 26 13:14:08 2019 +0200"
