<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="remove division">
      <expr>
        -x+3 == 4*x-10
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -5*x+3 == -10
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -5*x == -13
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 13/5
      </expr>
    </elem>
  </list>
</reply>

