<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        2*x
      </argument>
      <expr>
        4*x-2 == 14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        4*x == 16
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 4
      </expr>
    </elem>
  </list>
</reply>

