<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <expr>
        x+2 == 10*x+8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        -9*x+2 == 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -9*x == 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -2/3
      </expr>
    </elem>
  </list>
</reply>

