<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <argument description="factor">
        4
      </argument>
      <expr>
        x-3 == 8*x+2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        8*x
      </argument>
      <expr>
        -7*x-3 == 2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -7*x == 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -5/7
      </expr>
    </elem>
  </list>
</reply>

