<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        9*x-7 == -24
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        9*x == -17
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -17/9
      </expr>
    </elem>
  </list>
</reply>

