<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        (-3)*x
      </argument>
      <expr>
        -2*x+6 == 2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -2*x == -4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 2
      </expr>
    </elem>
  </list>
</reply>

