<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="distribution multiplication">
      <expr>
        -5*x-5 == 9*x+36-5
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        -5*x-5 == 9*x+31
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -14*x-5 == 31
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        -14*x == 36
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -18/7
      </expr>
    </elem>
  </list>
</reply>

