<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="distribution multiplication">
      <expr>
        -3*x+6 == 3*x+12-7
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        -3*x+6 == 3*x+5
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -6*x+6 == 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -6*x == -1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 1/6
      </expr>
    </elem>
  </list>
</reply>

