<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <expr>
        12-4*(4*x+2) == 36*x-3*(5*x-1)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        12-16*x-8 == 36*x-15*x+3
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        4-16*x == 21*x+3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        4-37*x == 3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        37*x == 1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 1/37
      </expr>
    </elem>
  </list>
</reply>

