<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <expr>
        -x+3 == 4*x-10
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        -5*x+3 == -10
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -5*x == -13
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 13/5
      </expr>
    </elem>
  </list>
</reply>

