<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="remove division">
      <expr>
        -5*(x-7) == 3*(x+2)-18
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        -5*x+35 == 3*x+6-18
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        -5*x+35 == 3*x-12
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -8*x+35 == -12
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -8*x == -47
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 47/8
      </expr>
    </elem>
  </list>
</reply>

