<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        16*x-4-2 == -3*x+6*x-15
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        16*x-6 == 3*x-15
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        13*x-6 == -15
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        13*x == -9
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -9/13
      </expr>
    </elem>
  </list>
</reply>

