<reply result="ok" version="0.5.12">
  <list>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        4-10*x == 17
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        10*x == -13
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -13/10
      </expr>
    </elem>
  </list>
</reply>

