<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        2*x-3*x-5 == 10+5*x-5
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        -x-5 == 5+5*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        -6*x-5 == 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -6*x == 10
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -5/3
      </expr>
    </elem>
  </list>
</reply>

