<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <expr>
        63-6*x == 36+2*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        63-8*x == 36
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        8*x == 27
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 27/8
      </expr>
    </elem>
  </list>
</reply>

