<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <expr>
        60*x-6*(2*x+2) == 360+5*(x-1)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        60*x-12*x-12 == 360+5*x-5
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        48*x-12 == 355+5*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        43*x-12 == 355
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        43*x == 367
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 367/43
      </expr>
    </elem>
  </list>
</reply>

