<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <argument description="factor">
        10
      </argument>
      <expr>
        -6*x+35 == 6*x+9
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        6*x
      </argument>
      <expr>
        -12*x+35 == 9
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -12*x == -26
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 13/6
      </expr>
    </elem>
  </list>
</reply>

