<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="remove division">
      <expr>
        5*x-1-12 == -24*x+3*(3*x-6)
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        5*x-1-12 == -24*x+9*x-18
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        5*x-13 == -15*x-18
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        20*x-13 == -18
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        20*x == -5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -1/4
      </expr>
    </elem>
  </list>
</reply>

