<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <argument description="factor">
        2
      </argument>
      <expr>
        x-8 == 4*x+5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        4*x
      </argument>
      <expr>
        -3*x-8 == 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -3*x == 13
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -13/3
      </expr>
    </elem>
  </list>
</reply>

