<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <expr>
        -6*x+35 == 6*x+9
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        -12*x+35 == 9
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -12*x == -26
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 13/6
      </expr>
    </elem>
  </list>
</reply>

