<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <expr>
        8*x-5 == 10*x+15
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        -2*x-5 == 15
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -2*x == 20
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -10
      </expr>
    </elem>
  </list>
</reply>

