<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <argument description="factor">
        6
      </argument>
      <expr>
        -3*(x+2) == 54*(2/3*x+1/3)-10
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        -3*x-6 == 36*x+8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        36*x
      </argument>
      <expr>
        -39*x-6 == 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -39*x == 14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -14/39
      </expr>
    </elem>
  </list>
</reply>

