<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        12*x-3+3 == 7*x-14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        12*x == 7*x-14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        5*x == -14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -14/5
      </expr>
    </elem>
  </list>
</reply>

