<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <expr>
        x-3 == 8*x+2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        -7*x-3 == 2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -7*x == 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -5/7
      </expr>
    </elem>
  </list>
</reply>

