<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        4*x-16 == 10*x+5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        -6*x-16 == 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -6*x == 21
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -7/2
      </expr>
    </elem>
  </list>
</reply>

