<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        3/5*x+2 == 7*x-14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.remove-div">
      <expr>
        3*x+10 == 35*x-70
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        -32*x+10 == -70
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -32*x == -80
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 5/2
      </expr>
    </elem>
  </list>
</reply>

