<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="remove division">
      <expr>
        -6*x+35 == 6*x+9
      </expr>
    </elem>
    <elem ruleid="variable to left">
      <expr>
        -12*x+35 == 9
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -12*x == -26
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 13/6
      </expr>
    </elem>
  </list>
</reply>

