<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        -5*x-5 == 9*x+31
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        9*x
      </argument>
      <expr>
        -14*x-5 == 31
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -14*x == 36
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -18/7
      </expr>
    </elem>
  </list>
</reply>

