<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <expr>
        5*x-13 == -24*x+3*(3*x-6)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        5*x-13 == -24*x+9*x-18
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        5*x-13 == -15*x-18
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        20*x-13 == -18
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        20*x == -5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -1/4
      </expr>
    </elem>
  </list>
</reply>

