<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <argument description="factor">
        4
      </argument>
      <expr>
        x-3 == 2*x-16
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        2*x
      </argument>
      <expr>
        -x-3 == -16
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -x == -13
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.negate">
      <expr>
        x == 13
      </expr>
    </elem>
  </list>
</reply>

