<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.remove-div">
      <expr>
        -x+4 == 12+10*(x-1)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        -x+4 == 12+10*x-10
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        -x+4 == 2+10*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        -11*x+4 == 2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -11*x == -2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 2/11
      </expr>
    </elem>
  </list>
</reply>

