<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        18-8*x-4 == 7*x-16*x+8
      </expr>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        14-8*x == -9*x+8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.var-left">
      <expr>
        14+x == 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == -6
      </expr>
    </elem>
  </list>
</reply>

