<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.var-left">
      <argument description="term">
        7*x
      </argument>
      <expr>
        -3*x-6 == -14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        -3*x == -8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 8/3
      </expr>
    </elem>
  </list>
</reply>

