<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="write as power">
      <expr>
        1/(a^4*a^(2/3))
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        1/a^(14/3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="reciprocal">
      <expr>
        a^(-14/3)
      </expr>
    </elem>
  </list>
</reply>

