<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="algebra.manipulation.exponents.write-as-power">
      <expr>
        a^3/(a^2*a^(1/3))
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        a^3/a^(7/3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.sub-exponents">
      <expr>
        a^(2/3)
      </expr>
    </elem>
  </list>
</reply>

