<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="write as power">
      <expr>
        a^2*a^(1/2)/(a*root a 3)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        a^(5/2)/(a*root a 3)
      </expr>
    </elem>
    <elem ruleid="write as power">
      <expr>
        a^(5/2)/(a*a^(1/3))
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        a^(5/2)/a^(4/3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="sub exponents">
      <expr>
        a^(7/6)
      </expr>
    </elem>
  </list>
</reply>

