<reply result="ok" version="0.6.7 (3629)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.write-as-power">
      <expr>
        a^4*a^(1/3)/(a^6*sqrt a)
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.write-as-power">
      <expr>
        a^4*a^(1/3)/(a^6*a^(1/2))
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        a^(13/3)/(a^6*a^(1/2))
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        a^(13/3)/a^(13/2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.sub-exponents">
      <expr>
        a^(-13/6)
      </expr>
    </elem>
  </list>
</reply>

