<reply result="ok" version="0.6.7 (3629)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.write-as-power">
      <expr>
        a^2*(a^3)^(1/5)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        a^2*a^(3/5)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        a^(13/5)
      </expr>
    </elem>
  </list>
</reply>

