<reply result="ok" version="0.6.7 (3629)">
  <list>
    <elem ruleid="algebra.manipulation.exponents.write-as-power">
      <expr>
        (1/a^5)^(1/2)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal-var">
      <expr>
        (a^(-5))^(1/2)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.mul-exponents">
      <expr>
        a^(-5/2)
      </expr>
    </elem>
  </list>
</reply>

