<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="algebra.manipulation.exponents.write-as-power">
      <expr>
        1/(a^4*a^(2/3))
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.add-exponents">
      <expr>
        1/a^(14/3)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.reciprocal">
      <expr>
        a^(-14/3)
      </expr>
    </elem>
  </list>
</reply>

