<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="reciprocal">
      <expr>
        root x 3*root (x^(-2)) 4
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
    <elem ruleid="write as power">
      <expr>
        x^(1/3)*root (x^(-2)) 4
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="write as power">
      <expr>
        x^(1/3)*x^(-1/2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        x^(-1/6)
      </expr>
    </elem>
  </list>
</reply>

