<reply result="ok" version="0.5.13">
  <list>
    <elem ruleid="write as power">
      <expr>
        a^2/(a*a^(1/2))
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="add exponents">
      <expr>
        a^2/a^(3/2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="sub exponents">
      <expr>
        a^(1/2)
      </expr>
    </elem>
  </list>
</reply>

