<reply result="ok" version="0.5.14">
  <list>
    <elem ruleid="algebra.equations.quadratic.same-con-factor">
      <expr>
        (x-2)*(x+6) == 4*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^2+4*x-12 == 4*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.cancel">
      <expr>
        x^2-12 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.no-lin">
      <expr>
        x^2 == 12
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt 12 or x == -sqrt 12
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-sqrt">
      <expr>
        x == 2*sqrt 3 or x == -2*sqrt 3
      </expr>
    </elem>
  </list>
</reply>

