<reply result="ok" version="0.5.14">
  <list>
    <elem ruleid="same constant factor">
      <expr>
        2*(10-x^2) == -x*(2*x+10)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        20-2*x^2 == -2*x^2-10*x
      </expr>
    </elem>
    <elem ruleid="cancel terms">
      <expr>
        20 == -10*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        -2 == x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x == -2
      </expr>
    </elem>
  </list>
</reply>

