<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        (6*x-3)^2 == 6
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        6*x-3 == sqrt 6 or 6*x-3 == -sqrt 6
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        6*x == 3+sqrt 6 or 6*x-3 == -sqrt 6
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == (3+sqrt 6)/6 or 6*x-3 == -sqrt 6
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == (3+sqrt 6)/6 or 6*x == 3-sqrt 6
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == (3+sqrt 6)/6 or x == (3-sqrt 6)/6
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="distribution division">
      <expr>
        x == 1/2+sqrt 6/6 or x == 1/2-sqrt 6/6
      </expr>
    </elem>
  </list>
</reply>

