<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-5*x == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.common-factor">
      <expr>
        x*(x-5) == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 0 or x == 5
      </expr>
    </elem>
  </list>
</reply>

