<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.distr-square">
      <expr>
        x^2-7*x+49/4 == 2*(x+4)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^2-7*x+49/4 == 2*x+8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-9*x+17/4 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-poly">
      <expr>
        4*x^2-36*x+17 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        x == 17/2 or x == 1/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 1024, a == 4, b == -36, c == 17]"/>
      </context>
    </elem>
  </list>
</reply>

