<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        7+2*x == sqrt 7 or 7+2*x == -sqrt 7
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        2*x == -7+sqrt 7 or 7+2*x == -sqrt 7
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == (-7+sqrt 7)/2 or 7+2*x == -sqrt 7
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == (-7+sqrt 7)/2 or 2*x == -7-sqrt 7
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == (-7+sqrt 7)/2 or x == (-7-sqrt 7)/2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.distr-div">
      <expr>
        x == -7/2+sqrt 7/2 or x == -7/2-sqrt 7/2
      </expr>
    </elem>
  </list>
</reply>

