<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="algebra.equations.quadratic.cancel">
      <expr>
        5*x^2 == 2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^2 == 2/5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt (2/5) or x == -sqrt (2/5)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-sqrt">
      <expr>
        x == 1/5*sqrt 10 or x == -1/5*sqrt 10
      </expr>
    </elem>
  </list>
</reply>

