<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.distr-square">
      <expr>
        1-2*x+x^2 == x+2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-3*x-1 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        x == (3+sqrt 13)/2 or x == (3-sqrt 13)/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 13, a == 1, b == -3, c == -1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.distr-div">
      <expr>
        x == 3/2+sqrt 13/2 or x == 3/2-sqrt 13/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 13, a == 1, b == -3, c == -1]"/>
      </context>
    </elem>
  </list>
</reply>

