<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="distribution square">
      <expr>
        9*x^2+30*x+25+(x-5)^2 == 40
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="distribution square">
      <expr>
        9*x^2+30*x+25+x^2-10*x+25 == 40
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="merge similar terms">
      <expr>
        10*x^2+20*x+50 == 40
      </expr>
    </elem>
    <elem ruleid="same constant factor">
      <expr>
        x^2+2*x+5 == 4
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2+2*x+1 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+1)^2 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x+1 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == -1
      </expr>
    </elem>
  </list>
</reply>

