<reply result="ok" version="0.5.14">
  <list>
    <elem ruleid="same constant factor">
      <expr>
        (x-2)*(x+6) == 4*x
      </expr>
    </elem>
    <elem ruleid="distribution multiplication">
      <expr>
        x^2+4*x-12 == 4*x
      </expr>
    </elem>
    <elem ruleid="cancel terms">
      <expr>
        x^2-12 == 0
      </expr>
    </elem>
    <elem ruleid="no linear term b">
      <expr>
        x^2 == 12
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt 12 or x == -sqrt 12
      </expr>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == 2*sqrt 3 or x == -2*sqrt 3
      </expr>
    </elem>
  </list>
</reply>

