<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x-1 == 10 or x-1 == -10
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 11 or x-1 == -10
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 11 or x == -9
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

