<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="cover-up power [vars]">
      <expr>
        6-2*x == 9 or 6-2*x == -9
      </expr>
    </elem>
    <elem ruleid="cover-up minus right [one var]">
      <expr>
        2*x == -3 or 6-2*x == -9
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -3/2 or 6-2*x == -9
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus right [one var]">
      <expr>
        x == -3/2 or 2*x == 15
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == -3/2 or x == 15/2
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

