<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-6*x-4 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        x == (6+sqrt 52)/2 or x == (6-sqrt 52)/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 52, a == 1, b == -6, c == -4]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-sqrt">
      <expr>
        x == 3+sqrt 13 or x == 3-sqrt 13
      </expr>
      <context>
        <item name="clipboard" value="[D == 52, a == 1, b == -6, c == -4]"/>
      </context>
    </elem>
  </list>
</reply>

