<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^2-5*x+4 == 11
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-5*x-7 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        x == (5+sqrt 53)/2 or x == (5-sqrt 53)/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 53, a == 1, b == -5, c == -7]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.distr-div">
      <expr>
        x == 5/2+sqrt 53/2 or x == 5/2-sqrt 53/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 53, a == 1, b == -5, c == -7]"/>
      </context>
    </elem>
  </list>
</reply>

