<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        9*x^2 == 81
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^2 == 9
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 3 or x == -3
      </expr>
    </elem>
  </list>
</reply>

