<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        (2*x+1)^2 == 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        2*x+1 == sqrt 6 or 2*x+1 == -sqrt 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        2*x == -1+sqrt 6 or 2*x+1 == -sqrt 6
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == (-1+sqrt 6)/2 or 2*x+1 == -sqrt 6
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == (-1+sqrt 6)/2 or 2*x == -1-sqrt 6
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == (-1+sqrt 6)/2 or x == (-1-sqrt 6)/2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.distr-div">
      <expr>
        x == -1/2+sqrt 6/2 or x == -1/2-sqrt 6/2
      </expr>
    </elem>
  </list>
</reply>

