<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        3*x^2-6*x-9 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-poly">
      <expr>
        x^2-2*x-3 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+1)*(x-3) == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -1 or x == 3
      </expr>
    </elem>
  </list>
</reply>

