<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="move to left">
      <expr>
        -2*x^2+3*x == 0
      </expr>
    </elem>
    <elem ruleid="common factor var">
      <expr>
        x*(-2*x+3) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 0 or -2*x+3 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == 0 or -2*x == -3
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 0 or x == 3/2
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

