<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^2-3*x == 3*x-6
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-6*x+6 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == (6+sqrt 12)/2 or x == (6-sqrt 12)/2
      </expr>
      <context>
        <item name="clipboard" value="[D==12, a==1, b==-6, c==6]"/>
      </context>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == 3+sqrt 3 or x == 3-sqrt 3
      </expr>
      <context>
        <item name="clipboard" value="[D==12, a==1, b==-6, c==6]"/>
      </context>
    </elem>
  </list>
</reply>

