<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="multiplication is zero">
      <expr>
        3*x-1 == 0 or x == -3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        3*x == 1 or x == -3
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 1/3 or x == -3
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

