<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 0 or 1-6*x == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        x == 0 or 6*x == 1
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 0 or x == 1/6
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

