<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        8*x^2+4*x-24 == x^2-5*x-24
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.cancel">
      <expr>
        8*x^2+4*x == x^2-5*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        7*x^2+9*x == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.common-factor">
      <expr>
        x*(7*x+9) == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 0 or 7*x+9 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == 0 or 7*x == -9
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 0 or x == -9/7
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

