<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        (6*x-3)^2 == 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        6*x-3 == sqrt 6 or 6*x-3 == -sqrt 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        6*x == 3+sqrt 6 or 6*x-3 == -sqrt 6
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == (3+sqrt 6)/6 or 6*x-3 == -sqrt 6
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == (3+sqrt 6)/6 or 6*x == 3-sqrt 6
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == (3+sqrt 6)/6 or x == (3-sqrt 6)/6
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.distr-div">
      <expr>
        x == 1/2+sqrt 6/6 or x == 1/2-sqrt 6/6
      </expr>
    </elem>
  </list>
</reply>

