<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^2+2*x == 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2+2*x-8 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x-2)*(x+4) == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 2 or x == -4
      </expr>
    </elem>
  </list>
</reply>

