<reply result="ok" version="0.5.14">
  <list>
    <elem ruleid="same constant factor">
      <expr>
        x^2 == 2*x
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-2*x == 0
      </expr>
    </elem>
    <elem ruleid="common factor var">
      <expr>
        x*(x-2) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 0 or x == 2
      </expr>
    </elem>
  </list>
</reply>

