<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        2*x^2-6*x-3 == x^2+8*x+12
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-14*x-15 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+1)*(x-15) == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -1 or x == 15
      </expr>
    </elem>
  </list>
</reply>

