<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="distribution square">
      <expr>
        3*x^2-11 == 9+12*x+4*x^2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        -x^2-12*x-20 == 0
      </expr>
    </elem>
    <elem ruleid="simpler polynomial">
      <expr>
        x^2+12*x+20 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+2)*(x+10) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -2 or x == -10
      </expr>
    </elem>
  </list>
</reply>

