<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        4-5*x+x^2 == 3*x
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-8*x+4 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        x == (8+sqrt 48)/2 or x == (8-sqrt 48)/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 48, a == 1, b == -8, c == 4]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-sqrt">
      <expr>
        x == 4+2*sqrt 3 or x == 4-2*sqrt 3
      </expr>
      <context>
        <item name="clipboard" value="[D == 48, a == 1, b == -8, c == 4]"/>
      </context>
    </elem>
  </list>
</reply>

