<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        1/4*x^2 == 4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^2 == 16
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 4 or x == -4
      </expr>
    </elem>
  </list>
</reply>

