<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="algebra.equations.coverup.numerator">
      <expr>
        3-x^2 == 20
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        x^2 == -17
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        false
      </expr>
    </elem>
  </list>
</reply>

