<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="distribution square">
      <expr>
        1-2*x+x^2 == x+2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-3*x-1 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == (3+sqrt 13)/2 or x == (3-sqrt 13)/2
      </expr>
      <context>
        <item name="clipboard" value="[D==13, a==1, b==-3, c==-1]"/>
      </context>
    </elem>
    <elem ruleid="distribution division">
      <expr>
        x == 3/2+sqrt 13/2 or x == 3/2-sqrt 13/2
      </expr>
      <context>
        <item name="clipboard" value="[D==13, a==1, b==-3, c==-1]"/>
      </context>
    </elem>
  </list>
</reply>

