<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        1/10*x^2 == -2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^2 == -20
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        false
      </expr>
    </elem>
  </list>
</reply>

