<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="cover-up power [vars]">
      <expr>
        7+2*x == sqrt 7 or 7+2*x == -sqrt 7
      </expr>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        2*x == -7+sqrt 7 or 7+2*x == -sqrt 7
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == (-7+sqrt 7)/2 or 7+2*x == -sqrt 7
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == (-7+sqrt 7)/2 or 2*x == -7-sqrt 7
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == (-7+sqrt 7)/2 or x == (-7-sqrt 7)/2
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="distribution division">
      <expr>
        x == -7/2+sqrt 7/2 or x == -7/2-sqrt 7/2
      </expr>
    </elem>
  </list>
</reply>

