<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        (2*x+3)^2 == 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        2*x+3 == sqrt 6 or 2*x+3 == -sqrt 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        2*x == -3+sqrt 6 or 2*x+3 == -sqrt 6
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == (-3+sqrt 6)/2 or 2*x+3 == -sqrt 6
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == (-3+sqrt 6)/2 or 2*x == -3-sqrt 6
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == (-3+sqrt 6)/2 or x == (-3-sqrt 6)/2
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="distribution division">
      <expr>
        x == -3/2+sqrt 6/2 or x == -3/2-sqrt 6/2
      </expr>
    </elem>
  </list>
</reply>

