<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        (x-7)^2 == 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x-7 == sqrt 8 or x-7 == -sqrt 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 7+sqrt 8 or x-7 == -sqrt 8
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 7+sqrt 8 or x == 7-sqrt 8
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-sqrt">
      <expr>
        x == 7+2*sqrt 2 or x == 7-2*sqrt 2
      </expr>
    </elem>
  </list>
</reply>

