<reply result="ok" version="0.7.9 (0)">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^2+12*x == 2*x^2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        -x^2+12*x == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.common-factor">
      <expr>
        -x*(x-12) == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 0 or x == 12
      </expr>
    </elem>
  </list>
</reply>

