<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 0 or 1-6*x == 0
      </expr>
    </elem>
    <elem ruleid="cover-up minus right [one var]">
      <expr>
        x == 0 or 6*x == 1
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 0 or x == 1/6
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

