<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        x == (-4+sqrt 32)/2 or x == (-4-sqrt 32)/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 32, a == 1, b == 4, c == -4]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-sqrt">
      <expr>
        x == -2+2*sqrt 2 or x == -2-2*sqrt 2
      </expr>
      <context>
        <item name="clipboard" value="[D == 32, a == 1, b == 4, c == -4]"/>
      </context>
    </elem>
  </list>
</reply>

