<reply result="ok" version="0.5.5">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        2*x^2 == 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^2 == 4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2 or x == -2
      </expr>
    </elem>
  </list>
</reply>

