<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        x^2-3*x == 4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-3*x-4 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+1)*(x-4) == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == -1 or x == 4
      </expr>
    </elem>
  </list>
</reply>

