<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 0 or 2*x-4 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 0 or 2*x == 4
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 0 or x == 2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

