<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        12*(x^2-3*x) == 48
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^2-3*x == 4
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^2-3*x-4 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (x+1)*(x-4) == 0
      </expr>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == -1 or x == 4
      </expr>
    </elem>
  </list>
</reply>

