<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="multiplication is zero">
      <expr>
        3*x-1 == 0 or x == -3
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        3*x == 1 or x == -3
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 1/3 or x == -3
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
  </list>
</reply>

