<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        2*x^2 == x^2+2*x+7
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2-2*x-7 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        x == (2+sqrt 32)/2 or x == (2-sqrt 32)/2
      </expr>
      <context>
        <item name="clipboard" value="[D==32, a==1, b==-2, c==-7]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-sqrt">
      <expr>
        x == 1+2*sqrt 2 or x == 1-2*sqrt 2
      </expr>
      <context>
        <item name="clipboard" value="[D==32, a==1, b==-2, c==-7]"/>
      </context>
    </elem>
  </list>
</reply>

