<reply result="ok" version="0.5.9">
  <list>
    <elem ruleid="simpler polynomial">
      <expr>
        x^2+2*x-4 == 0
      </expr>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        x == (-2+sqrt 20)/2 or x == (-2-sqrt 20)/2
      </expr>
      <context>
        <item name="clipboard" value="[D==20, a==1, b==2, c==-4]"/>
      </context>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == -1+sqrt 5 or x == -1-sqrt 5
      </expr>
      <context>
        <item name="clipboard" value="[D==20, a==1, b==2, c==-4]"/>
      </context>
    </elem>
  </list>
</reply>

