<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="distribution multiplication">
      <expr>
        x^2-4*x-5 == x^2-5*x+6
      </expr>
    </elem>
    <elem ruleid="cancel terms">
      <expr>
        -4*x-5 == -5*x+6
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x-11 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 11
      </expr>
    </elem>
  </list>
</reply>

