<reply result="ok" version="0.7.9 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        x^2/10 == -2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.numerator">
      <expr>
        x^2 == -20
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        false
      </expr>
    </elem>
  </list>
</reply>

