<reply result="ok" version="0.5.6">
  <list>
    <elem ruleid="cancel terms">
      <expr>
        5*x^2 == 2
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x^2 == 2/5
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt (2/5) or x == -sqrt (2/5)
      </expr>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == 1/5*sqrt 10 or x == -1/5*sqrt 10
      </expr>
    </elem>
  </list>
</reply>

