<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.simpler-poly">
      <expr>
        x^2+2*x-4 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        x == (-2+sqrt 20)/2 or x == (-2-sqrt 20)/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 20, a == 1, b == 2, c == -4]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-sqrt">
      <expr>
        x == -1+sqrt 5 or x == -1-sqrt 5
      </expr>
      <context>
        <item name="clipboard" value="[D == 20, a == 1, b == 2, c == -4]"/>
      </context>
    </elem>
  </list>
</reply>

