<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.distr-square">
      <expr>
        9*x^2+30*x+25+(x-5)^2 == 40
      </expr>
      <context>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.distr-square">
      <expr>
        9*x^2+30*x+25+x^2-10*x+25 == 40
      </expr>
      <context>
        <item name="location" value="[1,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        10*x^2+20*x+50 == 40
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.same-con-factor">
      <expr>
        x^2+2*x+5 == 4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x^2+2*x+1 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (x+1)^2 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x+1 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == -1
      </expr>
    </elem>
  </list>
</reply>

