<reply result="ok" version="0.6.7 (3710)">
  <list>
    <elem ruleid="algebra.equations.coverup.minus-left">
      <expr>
        5*x^4 == 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^4 == 1
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.nth-root">
      <expr>
        x == root 1 4
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.approx-power">
      <expr>
        x ~= 1.0
      </expr>
    </elem>
  </list>
</reply>

