<reply result="ok" version="0.7.9 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.minus-right">
      <expr>
        3*x^5 == -96
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^5 == -32
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.nth-root">
      <expr>
        x == -root 32 5
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.approx-power">
      <expr>
        x ~= -2.0
      </expr>
    </elem>
  </list>
</reply>

