<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="all power factors">
      <expr>
        x == 0 or x^2-5 == 0
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 0 or x^2 == 5
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 0 or x == sqrt 5 or x == -sqrt 5
      </expr>
    </elem>
  </list>
</reply>

