<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        4*(1/2*x+2)^6 == 4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (1/2*x+2)^6 == 1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        1/2*x+2 == 1 or 1/2*x+2 == -1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        1/2*x == -1 or 1/2*x+2 == -1
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -2 or 1/2*x+2 == -1
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == -2 or 1/2*x == -3
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -2 or x == -6
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

