<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.expose-factor">
      <expr>
        (x-1)*(x^3-6*x) == (x-1)*3*x^2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.same-factor">
      <expr>
        x-1 == 0 or x^3-6*x == 3*x^2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.polynomial.power-factors">
      <expr>
        x-1 == 0 or x == 0 or x^2-6 == 3*x
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 1 or x == 0 or x^2-6 == 3*x
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x == 1 or x == 0 or x^2-3*x-6 == 0
      </expr>
      <context>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        x == 1 or x == 0 or x == (3+sqrt 33)/2 or x == (3-sqrt 33)/2
      </expr>
      <context>
        <item name="clipboard" value="[D==33, a==1, b==-3, c==-6]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.distr-div">
      <expr>
        x == 1 or x == 0 or x == 3/2+sqrt 33/2 or x == 3/2-sqrt 33/2
      </expr>
      <context>
        <item name="clipboard" value="[D==33, a==1, b==-3, c==-6]"/>
      </context>
    </elem>
  </list>
</reply>

