<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        3*(x-2)^4 == 30
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (x-2)^4 == 10
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x-2 == root 10 4 or x-2 == -root 10 4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == root 10 4+2 or x-2 == -root 10 4
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == root 10 4+2 or x == -root 10 4+2
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

