<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        2*p^2-15*p+25 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == 5 or p == 5/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 25, a == 2, b == -15, c == 25, subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^2 == 5 or x^2 == 5/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 25, a == 2, b == -15, c == 25, subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt 5 or x == -sqrt 5 or x^2 == 5/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 25, a == 2, b == -15, c == 25, subst == (p == x^2)]"/>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt 5 or x == -sqrt 5 or x == sqrt (5/2) or x == -sqrt (5/2)
      </expr>
      <context>
        <item name="clipboard" value="[D == 25, a == 2, b == -15, c == 25, subst == (p == x^2)]"/>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
  </list>
</reply>

