<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        1/3*(x+5)^6 == 7
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (x+5)^6 == 21
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x+5 == root 21 6 or x+5 == -root 21 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == root 21 6-5 or x+5 == -root 21 6
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == root 21 6-5 or x == -root 21 6-5
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

