<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="all power factors">
      <expr>
        x == 0 or x^2-5*x+4 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        x == 0 or (x-1)*(x-4) == 0
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        x == 0 or x == 1 or x == 4
      </expr>
    </elem>
  </list>
</reply>

