<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="higher subst">
      <expr>
        2*p^2-15*p+25 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        p == 5 or p == 5/2
      </expr>
      <context>
        <item name="clipboard" value="[D==25, a==2, b==-15, c==25, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="subst back var">
      <expr>
        x^2 == 5 or x^2 == 5/2
      </expr>
      <context>
        <item name="clipboard" value="[D==25, a==2, b==-15, c==25, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt 5 or x == -sqrt 5 or x^2 == 5/2
      </expr>
      <context>
        <item name="clipboard" value="[D==25, a==2, b==-15, c==25, subst==(p==x^2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt 5 or x == -sqrt 5 or x == sqrt (5/2) or x == -sqrt (5/2)
      </expr>
      <context>
        <item name="clipboard" value="[D==25, a==2, b==-15, c==25, subst==(p==x^2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
  </list>
</reply>

