<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up minus right [one var]">
      <expr>
        1/3*(4*x-3)^5 == 81
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (4*x-3)^5 == 243
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        4*x-3 == 3
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        4*x == 6
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 3/2
      </expr>
    </elem>
  </list>
</reply>

