<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        -x^4+7*x^2+18 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        -p^2+7*p+18 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-poly">
      <expr>
        p^2-7*p-18 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (p+2)*(p-9) == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        p == -2 or p == 9
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^2 == -2 or x^2 == 9
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x^2 == 9
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 3 or x == -3
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
  </list>
</reply>

