<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.power-factors">
      <expr>
        x == 0 or x^2-5 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 0 or x^2 == 5
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 0 or x == sqrt 5 or x == -sqrt 5
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

