<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="move to left">
      <expr>
        x^4-x^2-12 == 0
      </expr>
    </elem>
    <elem ruleid="higher subst">
      <expr>
        p^2-p-12 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (p+3)*(p-4) == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        p == -3 or p == 4
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="subst back var">
      <expr>
        x^2 == -3 or x^2 == 4
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x^2 == 4
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2 or x == -2
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
  </list>
</reply>

