<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.power-factors">
      <expr>
        x == 0 or x^2-4*x-9 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        x == 0 or x == (4+sqrt 52)/2 or x == (4-sqrt 52)/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 52, a == 1, b == -4, c == -9]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-sqrt">
      <expr>
        x == 0 or x == 2+sqrt 13 or x == 2-sqrt 13
      </expr>
      <context>
        <item name="clipboard" value="[D == 52, a == 1, b == -4, c == -9]"/>
      </context>
    </elem>
  </list>
</reply>

