<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        5*(1-4*x)^3 == -625
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (1-4*x)^3 == -125
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        1-4*x == -5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        4*x == 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 3/2
      </expr>
    </elem>
  </list>
</reply>

