<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        3*x^5 == -96
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^5 == -32
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == -2
      </expr>
    </elem>
  </list>
</reply>

