<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        8*x^6+31*x^3-4 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        8*p^2+31*p-4 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == 1/8 or p == -4
      </expr>
      <context>
        <item name="clipboard" value="[D==1089, a==8, b==31, c==-4, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^3 == 1/8 or x^3 == -4
      </expr>
      <context>
        <item name="clipboard" value="[D==1089, a==8, b==31, c==-4, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 1/2 or x^3 == -4
      </expr>
      <context>
        <item name="clipboard" value="[D==1089, a==8, b==31, c==-4, subst==(p==x^3)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 1/2 or x == -root 4 3
      </expr>
      <context>
        <item name="clipboard" value="[D==1089, a==8, b==31, c==-4, subst==(p==x^3)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

