<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="all power factors">
      <expr>
        x == 0 or x^2+6*x+9 == 0
      </expr>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        x == 0 or (x+3)^2 == 0
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 0 or x+3 == 0
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        x == 0 or x == -3
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

