<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.power-factors">
      <expr>
        x == 0 or x^2-5*x+4 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        x == 0 or (x-1)*(x-4) == 0
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 0 or x == 1 or x == 4
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

