<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        4*x^8 == 28
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^8 == 7
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == root 7 8 or x == -root 7 8
      </expr>
    </elem>
  </list>
</reply>

