<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        7*p^2+8*p+1 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == -1/7 or p == -1
      </expr>
      <context>
        <item name="clipboard" value="[D==36, a==7, b==8, c==1, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^3 == -1/7 or x^3 == -1
      </expr>
      <context>
        <item name="clipboard" value="[D==36, a==7, b==8, c==1, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == -1/root 7 3 or x^3 == -1
      </expr>
      <context>
        <item name="clipboard" value="[D==36, a==7, b==8, c==1, subst==(p==x^3)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == -1/root 7 3 or x == -1
      </expr>
      <context>
        <item name="clipboard" value="[D==36, a==7, b==8, c==1, subst==(p==x^3)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

