<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        1/2*(3*x-4)^5 == 16
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (3*x-4)^5 == 32
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        3*x-4 == 2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        3*x == 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 2
      </expr>
    </elem>
  </list>
</reply>

