<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="all power factors">
      <expr>
        x == 0 or x^2 == 4*x+12
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x == 0 or x^2-4*x-12 == 0
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        x == 0 or (x+2)*(x-6) == 0
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 0 or x == -2 or x == 6
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

