<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        -2*(4*x-5)^4 == -8192
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (4*x-5)^4 == 4096
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        4*x-5 == 8 or 4*x-5 == -8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        4*x == 13 or 4*x-5 == -8
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 13/4 or 4*x-5 == -8
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 13/4 or 4*x == -3
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 13/4 or x == -3/4
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

