<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="all power factors">
      <expr>
        x == 0 or 64*x^2 == 1
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 0 or x^2 == 1/64
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 0 or x == sqrt (1/64) or x == -sqrt (1/64)
      </expr>
    </elem>
    <elem ruleid="simpler square root">
      <expr>
        x == 0 or x == 1/8 or x == -1/8
      </expr>
    </elem>
  </list>
</reply>

