<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        -x^4+29*x^2-100 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        -p^2+29*p-100 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.simpler-poly">
      <expr>
        p^2-29*p+100 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        (p-4)*(p-25) == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        p == 4 or p == 25
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^2 == 4 or x^2 == 25
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2 or x == -2 or x^2 == 25
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2 or x == -2 or x == 5 or x == -5
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
  </list>
</reply>

