<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        15*x^8 == 30
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^8 == 2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == root 2 8 or x == -root 2 8
      </expr>
    </elem>
  </list>
</reply>

