<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        1/2*(x-1)^5 == -4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (x-1)^5 == -8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x-1 == -root 8 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == -root 8 5+1
      </expr>
    </elem>
  </list>
</reply>

