<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        3*p^2-14*p-5 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == 5 or p == -1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==256, a==3, b==-14, c==-5, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^2 == 5 or x^2 == -1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==256, a==3, b==-14, c==-5, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt 5 or x == -sqrt 5 or x^2 == -1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==256, a==3, b==-14, c==-5, subst==(p==x^2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt 5 or x == -sqrt 5
      </expr>
      <context>
        <item name="clipboard" value="[D==256, a==3, b==-14, c==-5, subst==(p==x^2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
  </list>
</reply>

