<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        8*p^2-9*p+1 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == 1 or p == 1/8
      </expr>
      <context>
        <item name="clipboard" value="[D == 49, a == 8, b == -9, c == 1, subst == (p == x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^3 == 1 or x^3 == 1/8
      </expr>
      <context>
        <item name="clipboard" value="[D == 49, a == 8, b == -9, c == 1, subst == (p == x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 1 or x^3 == 1/8
      </expr>
      <context>
        <item name="clipboard" value="[D == 49, a == 8, b == -9, c == 1, subst == (p == x^3)]"/>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 1 or x == 1/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 49, a == 8, b == -9, c == 1, subst == (p == x^3)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

