<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        9*p^2-28*p+3 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == 3 or p == 1/9
      </expr>
      <context>
        <item name="clipboard" value="[D == 676, a == 9, b == -28, c == 3, subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^2 == 3 or x^2 == 1/9
      </expr>
      <context>
        <item name="clipboard" value="[D == 676, a == 9, b == -28, c == 3, subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt 3 or x == -sqrt 3 or x^2 == 1/9
      </expr>
      <context>
        <item name="clipboard" value="[D == 676, a == 9, b == -28, c == 3, subst == (p == x^2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt 3 or x == -sqrt 3 or x == sqrt (1/9) or x == -sqrt (1/9)
      </expr>
      <context>
        <item name="clipboard" value="[D == 676, a == 9, b == -28, c == 3, subst == (p == x^2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
  </list>
</reply>

