<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        2*x^4-x^2-3 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        2*p^2-p-3 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == 3/2 or p == -1
      </expr>
      <context>
        <item name="clipboard" value="[D == 25, a == 2, b == -1, c == -3, subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^2 == 3/2 or x^2 == -1
      </expr>
      <context>
        <item name="clipboard" value="[D == 25, a == 2, b == -1, c == -3, subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt (3/2) or x == -sqrt (3/2) or x^2 == -1
      </expr>
      <context>
        <item name="clipboard" value="[D == 25, a == 2, b == -1, c == -3, subst == (p == x^2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt (3/2) or x == -sqrt (3/2)
      </expr>
      <context>
        <item name="clipboard" value="[D == 25, a == 2, b == -1, c == -3, subst == (p == x^2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
  </list>
</reply>

