<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (3*x-1)^4 == 16
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        3*x-1 == 2 or 3*x-1 == -2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        3*x == 3 or 3*x-1 == -2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 1 or 3*x-1 == -2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 1 or 3*x == -1
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 1 or x == -1/3
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

