<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="move to left">
      <expr>
        4*x^4-17*x^2+4 == 0
      </expr>
    </elem>
    <elem ruleid="higher subst">
      <expr>
        4*p^2-17*p+4 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        p == 4 or p == 1/4
      </expr>
      <context>
        <item name="clipboard" value="[D==225, a==4, b==-17, c==4, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="subst back var">
      <expr>
        x^2 == 4 or x^2 == 1/4
      </expr>
      <context>
        <item name="clipboard" value="[D==225, a==4, b==-17, c==4, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 2 or x == -2 or x^2 == 1/4
      </expr>
      <context>
        <item name="clipboard" value="[D==225, a==4, b==-17, c==4, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == 2 or x == -2 or x == sqrt (1/4) or x == -sqrt (1/4)
      </expr>
      <context>
        <item name="clipboard" value="[D==225, a==4, b==-17, c==4, subst==(p==x^2)]"/>
      </context>
    </elem>
  </list>
</reply>

