<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        4*x^6+9*x^3+2 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        4*p^2+9*p+2 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == -1/4 or p == -2
      </expr>
      <context>
        <item name="clipboard" value="[D==49, a==4, b==9, c==2, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^3 == -1/4 or x^3 == -2
      </expr>
      <context>
        <item name="clipboard" value="[D==49, a==4, b==9, c==2, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == -1/root 4 3 or x^3 == -2
      </expr>
      <context>
        <item name="clipboard" value="[D==49, a==4, b==9, c==2, subst==(p==x^3)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == -1/root 4 3 or x == -root 2 3
      </expr>
      <context>
        <item name="clipboard" value="[D==49, a==4, b==9, c==2, subst==(p==x^3)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

