<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="move to left">
      <expr>
        9*x^4+14*x^2-8 == 0
      </expr>
    </elem>
    <elem ruleid="higher subst">
      <expr>
        9*p^2+14*p-8 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        p == 4/9 or p == -2
      </expr>
      <context>
        <item name="clipboard" value="[D==484, a==9, b==14, c==-8, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="subst back var">
      <expr>
        x^2 == 4/9 or x^2 == -2
      </expr>
      <context>
        <item name="clipboard" value="[D==484, a==9, b==14, c==-8, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt (4/9) or x == -sqrt (4/9) or x^2 == -2
      </expr>
      <context>
        <item name="clipboard" value="[D==484, a==9, b==14, c==-8, subst==(p==x^2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt (4/9) or x == -sqrt (4/9)
      </expr>
      <context>
        <item name="clipboard" value="[D==484, a==9, b==14, c==-8, subst==(p==x^2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
  </list>
</reply>

