<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        (2*x-1)^3 == 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        2*x-1 == root 5 3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        2*x == root 5 3+1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == (root 5 3+1)/2
      </expr>
    </elem>
    <elem ruleid="distribution division">
      <expr>
        x == root 5 3/2+1/2
      </expr>
    </elem>
  </list>
</reply>

