<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        4*x^3 == 108
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^3 == 27
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 3
      </expr>
    </elem>
  </list>
</reply>

