<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        3*p^2-80*p-27 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == 27 or p == -1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==6724, a==3, b==-80, c==-27, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^3 == 27 or x^3 == -1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==6724, a==3, b==-80, c==-27, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 3 or x^3 == -1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==6724, a==3, b==-80, c==-27, subst==(p==x^3)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 3 or x == -1/root 3 3
      </expr>
      <context>
        <item name="clipboard" value="[D==6724, a==3, b==-80, c==-27, subst==(p==x^3)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

