<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        3*(2*x-1)^3 == 648
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (2*x-1)^3 == 216
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        2*x-1 == 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        2*x == 7
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 7/2
      </expr>
    </elem>
  </list>
</reply>

