<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        2*(1/2*x+3)^7 == 2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (1/2*x+3)^7 == 1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        1/2*x+3 == 1
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        1/2*x == -2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -4
      </expr>
    </elem>
  </list>
</reply>

