<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        27*x^6-217*x^3+8 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        27*p^2-217*p+8 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == 8 or p == 1/27
      </expr>
      <context>
        <item name="clipboard" value="[D==46225, a==27, b==-217, c==8, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^3 == 8 or x^3 == 1/27
      </expr>
      <context>
        <item name="clipboard" value="[D==46225, a==27, b==-217, c==8, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2 or x^3 == 1/27
      </expr>
      <context>
        <item name="clipboard" value="[D==46225, a==27, b==-217, c==8, subst==(p==x^3)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2 or x == 1/3
      </expr>
      <context>
        <item name="clipboard" value="[D==46225, a==27, b==-217, c==8, subst==(p==x^3)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

