<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        1/2*x^4 == 7
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^4 == 14
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == root 14 4 or x == -root 14 4
      </expr>
    </elem>
  </list>
</reply>

