<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        1/5*x^3 == 25
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^3 == 125
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 5
      </expr>
    </elem>
  </list>
</reply>

