<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        -2*(4*x-5)^4 == -8192
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (4*x-5)^4 == 4096
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        4*x-5 == 8 or 4*x-5 == -8
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        4*x == 13 or 4*x-5 == -8
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 13/4 or 4*x-5 == -8
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 13/4 or 4*x == -3
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 13/4 or x == -3/4
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

