<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="higher subst">
      <expr>
        9*p^2-28*p+3 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="abc formula">
      <expr>
        p == 3 or p == 1/9
      </expr>
      <context>
        <item name="clipboard" value="[D==676, a==9, b==-28, c==3, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="subst back var">
      <expr>
        x^2 == 3 or x^2 == 1/9
      </expr>
      <context>
        <item name="clipboard" value="[D==676, a==9, b==-28, c==3, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt 3 or x == -sqrt 3 or x^2 == 1/9
      </expr>
      <context>
        <item name="clipboard" value="[D==676, a==9, b==-28, c==3, subst==(p==x^2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt 3 or x == -sqrt 3 or x == sqrt (1/9) or x == -sqrt (1/9)
      </expr>
      <context>
        <item name="clipboard" value="[D==676, a==9, b==-28, c==3, subst==(p==x^2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
  </list>
</reply>

