<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="cover-up plus [one var]">
      <expr>
        3*(x-2)^4 == 30
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (x-2)^4 == 10
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x-2 == root 10 4 or x-2 == -root 10 4
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == root 10 4+2 or x-2 == -root 10 4
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == root 10 4+2 or x == -root 10 4+2
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

