<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        5*x^6-39*x^3-8 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        5*p^2-39*p-8 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == 8 or p == -1/5
      </expr>
      <context>
        <item name="clipboard" value="[D==1681, a==5, b==-39, c==-8, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^3 == 8 or x^3 == -1/5
      </expr>
      <context>
        <item name="clipboard" value="[D==1681, a==5, b==-39, c==-8, subst==(p==x^3)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2 or x^3 == -1/5
      </expr>
      <context>
        <item name="clipboard" value="[D==1681, a==5, b==-39, c==-8, subst==(p==x^3)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2 or x == -1/root 5 3
      </expr>
      <context>
        <item name="clipboard" value="[D==1681, a==5, b==-39, c==-8, subst==(p==x^3)]"/>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

