<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        3*(2*x+7)^3 == 24
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (2*x+7)^3 == 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        2*x+7 == 2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        2*x == -5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -5/2
      </expr>
    </elem>
  </list>
</reply>

