<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.power-factors">
      <expr>
        x == 0 or 7*x == 8
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 0 or x == 8/7
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
  </list>
</reply>

