<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (3*x-1)^4 == 16
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        3*x-1 == 2 or 3*x-1 == -2
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        3*x == 3 or 3*x-1 == -2
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 1 or 3*x-1 == -2
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 1 or 3*x == -1
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 1 or x == -1/3
      </expr>
    </elem>
  </list>
</reply>

