<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        2*(3*x-6)^6 == 2
      </expr>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        (3*x-6)^6 == 1
      </expr>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        3*x-6 == 1 or 3*x-6 == -1
      </expr>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        3*x == 7 or 3*x-6 == -1
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 7/3 or 3*x-6 == -1
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up minus left [one var]">
      <expr>
        x == 7/3 or 3*x == 5
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="cover-up times [vars]">
      <expr>
        x == 7/3 or x == 5/3
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

