<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.power-factors">
      <expr>
        x == 0 or x^2+2*x == 24
      </expr>
    </elem>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        x == 0 or x^2+2*x-24 == 0
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.nice-factors">
      <expr>
        x == 0 or (x-4)*(x+6) == 0
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.product-zero">
      <expr>
        x == 0 or x == 4 or x == -6
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

