<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        3*(2*x+5)^2 == 12
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (2*x+5)^2 == 4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        2*x+5 == 2 or 2*x+5 == -2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        2*x == -3 or 2*x+5 == -2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -3/2 or 2*x+5 == -2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.plus">
      <expr>
        x == -3/2 or 2*x == -7
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -3/2 or x == -7/2
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

