<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        1/3*(4*x-3)^5 == 81
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        (4*x-3)^5 == 243
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        4*x-3 == 3
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        4*x == 6
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == 3/2
      </expr>
    </elem>
  </list>
</reply>

