<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.equations.quadratic.move-left">
      <expr>
        4*x^4-17*x^2+4 == 0
      </expr>
    </elem>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        4*p^2-17*p+4 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == 4 or p == 1/4
      </expr>
      <context>
        <item name="clipboard" value="[D == 225, a == 4, b == -17, c == 4, subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^2 == 4 or x^2 == 1/4
      </expr>
      <context>
        <item name="clipboard" value="[D == 225, a == 4, b == -17, c == 4, subst == (p == x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2 or x == -2 or x^2 == 1/4
      </expr>
      <context>
        <item name="clipboard" value="[D == 225, a == 4, b == -17, c == 4, subst == (p == x^2)]"/>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 2 or x == -2 or x == 1/2 or x == -1/2
      </expr>
      <context>
        <item name="clipboard" value="[D == 225, a == 4, b == -17, c == 4, subst == (p == x^2)]"/>
        <item name="location" value="[1,1]"/>
      </context>
    </elem>
  </list>
</reply>

