<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="algebra.equations.polynomial.subst">
      <expr>
        4*p^2-29*p-24 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.quadratic.abc">
      <expr>
        p == 8 or p == -3/4
      </expr>
      <context>
        <item name="clipboard" value="[D==1225, a==4, b==-29, c==-24, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.polynomial.back-subst">
      <expr>
        x^2 == 8 or x^2 == -3/4
      </expr>
      <context>
        <item name="clipboard" value="[D==1225, a==4, b==-29, c==-24, subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt 8 or x == -sqrt 8 or x^2 == -3/4
      </expr>
      <context>
        <item name="clipboard" value="[D==1225, a==4, b==-29, c==-24, subst==(p==x^2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == sqrt 8 or x == -sqrt 8
      </expr>
      <context>
        <item name="clipboard" value="[D==1225, a==4, b==-29, c==-24, subst==(p==x^2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
  </list>
</reply>

