<reply result="ok" version="0.5.11">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        1/9*x^8 == 5
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^8 == 45
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == root 45 8 or x == -root 45 8
      </expr>
    </elem>
  </list>
</reply>

