<reply result="ok" version="0.6.2 (0)">
  <list>
    <elem ruleid="same constant factor">
      <expr>
        x^4+x^2 == 6
      </expr>
    </elem>
    <elem ruleid="move to left">
      <expr>
        x^4+x^2-6 == 0
      </expr>
    </elem>
    <elem ruleid="higher subst">
      <expr>
        p^2+p-6 == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="nice factors">
      <expr>
        (p-2)*(p+3) == 0
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="multiplication is zero">
      <expr>
        p == 2 or p == -3
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="subst back var">
      <expr>
        x^2 == 2 or x^2 == -3
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt 2 or x == -sqrt 2 or x^2 == -3
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="cover-up power [vars]">
      <expr>
        x == sqrt 2 or x == -sqrt 2
      </expr>
      <context>
        <item name="clipboard" value="[subst==(p==x^2)]"/>
        <item name="location" value="[2,2]"/>
      </context>
    </elem>
  </list>
</reply>

