<reply result="ok" version="1.0.3 (0)">
  <list>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        8*x^2 == 18
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x^2 == 9/4
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 3/2 or x == -3/2
      </expr>
    </elem>
  </list>
</reply>

