<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.plus">
      <expr>
        D(x) ((3-2*x)/(2*x^2-3))+D(x) (x^3)
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.quotient">
      <expr>
        ((2*x^2-3)*D(x) (3-2*x)-(3-2*x)*D(x) (2*x^2-3))/(2*x^2-3)^2+D(x) (x^3)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (-(2*x^2-3)*2-(3-2*x)*D(x) (2*x^2-3))/(2*x^2-3)^2+D(x) (x^3)
      </expr>
      <context>
        <item name="location" value="[0,0,0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (-(2*x^2-3)*2-(3-2*x)*(4*x))/(2*x^2-3)^2+D(x) (x^3)
      </expr>
      <context>
        <item name="location" value="[0,0,1,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (-(2*x^2-3)*2-(3-2*x)*(4*x))/(2*x^2-3)^2+3*x^2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (-4*x^2+6-(3-2*x)*(4*x))/(2*x^2-3)^2+3*x^2
      </expr>
      <context>
        <item name="location" value="[0,0,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (-4*x^2+6-12*x+8*x^2)/(2*x^2-3)^2+3*x^2
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (4*x^2+6-12*x)/(2*x^2-3)^2+3*x^2
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
  </list>
</reply>

