<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="calculus.differentiation.plus">
      <expr>
        D(x) ((x^3-3)/(4-x))+D(x) (x^2)
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.quotient">
      <expr>
        ((4-x)*D(x) (x^3-3)-(x^3-3)*D(x) (4-x))/(4-x)^2+D(x) (x^2)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        ((4-x)*3*x^2-(x^3-3)*D(x) (4-x))/(4-x)^2+D(x) (x^2)
      </expr>
      <context>
        <item name="location" value="[0,0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        ((4-x)*3*x^2+x^3-3)/(4-x)^2+D(x) (x^2)
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        ((4-x)*3*x^2+x^3-3)/(4-x)^2+2*x
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (12*x^2-3*x^3+x^3-3)/(4-x)^2+2*x
      </expr>
      <context>
        <item name="location" value="[0,0,0,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (12*x^2-2*x^3-3)/(4-x)^2+2*x
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
  </list>
</reply>

