<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.quotient">
      <expr>
        ((2*x-1)*D(x) 3-3*D(x) (2*x-1))/(2*x-1)^2
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        -3*D(x) (2*x-1)/(2*x-1)^2
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        -6/(2*x-1)^2
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
  </list>
</reply>

