<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.plus">
      <expr>
        D(x) ((2*x^3-4)/(6-5*x))+D(x) (4*x^2)
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.quotient">
      <expr>
        ((6-5*x)*D(x) (2*x^3-4)-(2*x^3-4)*D(x) (6-5*x))/(6-5*x)^2+D(x) (4*x^2)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        ((6-5*x)*(6*x^2)-(2*x^3-4)*D(x) (6-5*x))/(6-5*x)^2+D(x) (4*x^2)
      </expr>
      <context>
        <item name="location" value="[0,0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        ((6-5*x)*(6*x^2)+(2*x^3-4)*5)/(6-5*x)^2+D(x) (4*x^2)
      </expr>
      <context>
        <item name="location" value="[0,0,1,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        ((6-5*x)*(6*x^2)+(2*x^3-4)*5)/(6-5*x)^2+8*x
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (36*x^2-30*x^3+(2*x^3-4)*5)/(6-5*x)^2+8*x
      </expr>
      <context>
        <item name="location" value="[0,0,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (36*x^2-30*x^3+10*x^3-20)/(6-5*x)^2+8*x
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (36*x^2-20*x^3-20)/(6-5*x)^2+8*x
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
  </list>
</reply>

