<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.quotient">
      <expr>
        ((3*x-1)*D(x) (-4)+4*D(x) (3*x-1))/(3*x-1)^2
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        4*D(x) (3*x-1)/(3*x-1)^2
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        12/(3*x-1)^2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
  </list>
</reply>

