<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.quotient">
      <expr>
        ((3*x+4)*D(x) 2-2*D(x) (3*x+4))/(3*x+4)^2
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        -2*D(x) (3*x+4)/(3*x+4)^2
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        -6/(3*x+4)^2
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
  </list>
</reply>

