<reply result="ok" version="0.6.6 (0)">
  <list>
    <elem ruleid="calculus.differentiation.quotient">
      <expr>
        ((4*x^3-2)*D(x) (x^2)-x^2*D(x) (4*x^3-2))/(4*x^3-2)^2
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        ((4*x^3-2)*2*x-x^2*D(x) (4*x^3-2))/(4*x^3-2)^2
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        ((4*x^3-2)*2*x-12*x^4)/(4*x^3-2)^2
      </expr>
      <context>
        <item name="location" value="[0,1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (8*x^4-4*x-12*x^4)/(4*x^3-2)^2
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (-4*x^4-4*x)/(4*x^3-2)^2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
  </list>
</reply>

