<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.quotient">
      <expr>
        ((x+1)*D(x) (1-2*x^3)-(1-2*x^3)*D(x) (x+1))/(x+1)^2
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (-(x+1)*(6*x^2)-(1-2*x^3)*D(x) (x+1))/(x+1)^2
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (-(x+1)*(6*x^2)-1+2*x^3)/(x+1)^2
      </expr>
      <context>
        <item name="location" value="[0,1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (-6*x^3-6*x^2-1+2*x^3)/(x+1)^2
      </expr>
      <context>
        <item name="location" value="[0,0,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (-4*x^3-6*x^2-1)/(x+1)^2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
  </list>
</reply>

