<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.quotient">
      <expr>
        ((2-3*x^2)*D(x) (x+5)-(x+5)*D(x) (2-3*x^2))/(2-3*x^2)^2
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (2-3*x^2-(x+5)*D(x) (2-3*x^2))/(2-3*x^2)^2
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (2-3*x^2+(x+5)*(6*x))/(2-3*x^2)^2
      </expr>
      <context>
        <item name="location" value="[0,1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (2-3*x^2+6*x^2+30*x)/(2-3*x^2)^2
      </expr>
      <context>
        <item name="location" value="[0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (2+3*x^2+30*x)/(2-3*x^2)^2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
  </list>
</reply>

