<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.quotient">
      <expr>
        ((3*x^2-1)*D(x) (2*x^3)-2*x^3*D(x) (3*x^2-1))/(3*x^2-1)^2
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        ((3*x^2-1)*(6*x^2)-2*x^3*D(x) (3*x^2-1))/(3*x^2-1)^2
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        ((3*x^2-1)*(6*x^2)-12*x^4)/(3*x^2-1)^2
      </expr>
      <context>
        <item name="location" value="[0,1,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (18*x^4-6*x^2-12*x^4)/(3*x^2-1)^2
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (6*x^4-6*x^2)/(3*x^2-1)^2
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
  </list>
</reply>

