<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="calculus.differentiation.plus">
      <expr>
        D(x) ((2-x)/(x^2+1))+D(x) (2*x^3)
      </expr>
    </elem>
    <elem ruleid="calculus.differentiation.quotient">
      <expr>
        ((x^2+1)*D(x) (2-x)-(2-x)*D(x) (x^2+1))/(x^2+1)^2+D(x) (2*x^3)
      </expr>
      <context>
        <item name="location" value="[0]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (-x^2-1-(2-x)*D(x) (x^2+1))/(x^2+1)^2+D(x) (2*x^3)
      </expr>
      <context>
        <item name="location" value="[0,0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (-x^2-1-(2-x)*(2*x))/(x^2+1)^2+D(x) (2*x^3)
      </expr>
      <context>
        <item name="location" value="[0,0,1,1]"/>
      </context>
    </elem>
    <elem ruleid="calculus.differentiation.deriv-of-poly">
      <expr>
        (-x^2-1-(2-x)*(2*x))/(x^2+1)^2+6*x^2
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.distr-times">
      <expr>
        (-x^2-1-4*x+2*x^2)/(x^2+1)^2+6*x^2
      </expr>
      <context>
        <item name="location" value="[0,0,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.linear.merge">
      <expr>
        (x^2-1-4*x)/(x^2+1)^2+6*x^2
      </expr>
      <context>
        <item name="location" value="[0,0]"/>
      </context>
    </elem>
  </list>
</reply>

