<reply result="ok" version="1.0.3 (0)">
  <incorrect equivalent="false">
    <location>
      linearalgebra.gaussianelim.scale
    </location>
    <state>
      <prefix>
        [12,1,1,0]
      </prefix>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              2
            </OMI>
            <OMI>
              4
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
      <context>
        <item name="columnj" value="0"/>
      </context>
    </state>
    <argument description="row">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMI>
          0
        </OMI>
      </OMOBJ>
    </argument>
    <argument description="scalefactor">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="arith1" name="divide"/>
          <OMI>
            1
          </OMI>
          <OMI>
            6
          </OMI>
        </OMA>
      </OMOBJ>
    </argument>
  </incorrect>
</reply>

