<reply result="incorrect" version="0.6.3 (0)">
  <strategy>
    linearalgebra.gaussianelim
  </strategy>
  <location>
    [0,2,0]
  </location>
  <expected>
    <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
      <OMA>
        <OMS cd="linalg2" name="matrix"/>
        <OMA>
          <OMS cd="linalg2" name="matrixrow"/>
          <OMI>
            1
          </OMI>
          <OMA>
            <OMS cd="arith1" name="divide"/>
            <OMI>
              1
            </OMI>
            <OMI>
              2
            </OMI>
          </OMA>
        </OMA>
        <OMA>
          <OMS cd="linalg2" name="matrixrow"/>
          <OMI>
            2
          </OMI>
          <OMI>
            4
          </OMI>
        </OMA>
      </OMA>
    </OMOBJ>
  </expected>
  <steps>
    4
  </steps>
  <equivalent>
    False
  </equivalent>
  <arguments>
    <elem descr="row">
      0
    </elem>
    <elem descr="scale factor">
      1/6
    </elem>
  </arguments>
  <derivation>
    <elem ruleid="Scale">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              2
            </OMI>
            <OMI>
              4
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
  </derivation>
</reply>

