<reply result="ok" version="0.7.3 (0)">
  <list>
    <elem ruleid="linearalgebra.gaussianelim.scale">
      <argument description="row">
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMI>
            0
          </OMI>
        </OMOBJ>
      </argument>
      <argument description="scale factor">
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMA>
            <OMS cd="arith1" name="divide"/>
            <OMI>
              1
            </OMI>
            <OMI>
              6
            </OMI>
          </OMA>
        </OMOBJ>
      </argument>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              2
            </OMI>
            <OMI>
              4
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
      <context>
        <item name="columnJ" value="0"/>
      </context>
    </elem>
    <elem ruleid="linearalgebra.gaussianelim.add">
      <argument description="row 1">
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMI>
            1
          </OMI>
        </OMOBJ>
      </argument>
      <argument description="row2">
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMI>
            0
          </OMI>
        </OMOBJ>
      </argument>
      <argument description="scale factor">
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMA>
            <OMS cd="arith1" name="unary_minus"/>
            <OMI>
              2
            </OMI>
          </OMA>
        </OMOBJ>
      </argument>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              3
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
      <context>
        <item name="columnJ" value="0"/>
      </context>
    </elem>
    <elem ruleid="linearalgebra.gaussianelim.scale">
      <argument description="row">
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMI>
            1
          </OMI>
        </OMOBJ>
      </argument>
      <argument description="scale factor">
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMA>
            <OMS cd="arith1" name="divide"/>
            <OMI>
              1
            </OMI>
            <OMI>
              3
            </OMI>
          </OMA>
        </OMOBJ>
      </argument>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              1
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
      <context>
        <item name="columnJ" value="1"/>
        <item name="covered" value="1"/>
      </context>
    </elem>
    <elem ruleid="linearalgebra.gaussianelim.add">
      <argument description="row 1">
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMI>
            0
          </OMI>
        </OMOBJ>
      </argument>
      <argument description="row2">
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMI>
            1
          </OMI>
        </OMOBJ>
      </argument>
      <argument description="scale factor">
        <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
          <OMA>
            <OMS cd="arith1" name="unary_minus"/>
            <OMA>
              <OMS cd="arith1" name="divide"/>
              <OMI>
                1
              </OMI>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
        </OMOBJ>
      </argument>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMI>
              0
            </OMI>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              1
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
      <context>
        <item name="columnJ" value="1"/>
        <item name="covered" value="1"/>
      </context>
    </elem>
  </list>
</reply>

