<reply result="ok" version="0.6.5 (0)">
  <list>
    <elem ruleid="Scale">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMV name="a"/>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              2
            </OMI>
            <OMI>
              4
            </OMI>
            <OMI>
              2
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
      <context>
        <item name="columnJ" value="0"/>
      </context>
    </elem>
    <elem ruleid="Add">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMV name="a"/>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              2
            </OMI>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  2
                </OMI>
                <OMV name="a"/>
              </OMA>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
      <context>
        <item name="columnJ" value="0"/>
      </context>
    </elem>
    <elem ruleid="Scale">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMV name="a"/>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMI>
                1
              </OMI>
              <OMV name="a"/>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
      <context>
        <item name="columnJ" value="1"/>
        <item name="covered" value="1"/>
      </context>
    </elem>
    <elem ruleid="Add">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMI>
              0
            </OMI>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMA>
                <OMS cd="arith1" name="unary_minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    2
                  </OMI>
                  <OMV name="a"/>
                </OMA>
              </OMA>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMI>
                1
              </OMI>
              <OMV name="a"/>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
      <context>
        <item name="columnJ" value="1"/>
        <item name="covered" value="1"/>
      </context>
    </elem>
  </list>
</reply>

