<reply result="incorrect" version="0.2.10">
  <strategy>
    Gaussian elimination
  </strategy>
  <location>
    [0]
  </location>
  <expected>
    <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
      <OMA>
        <OMS cd="linalg2" name="matrix"/>
        <OMA>
          <OMS cd="linalg2" name="matrixrow"/>
          <OMI>
            1
          </OMI>
          <OMI>
            0
          </OMI>
        </OMA>
        <OMA>
          <OMS cd="linalg2" name="matrixrow"/>
          <OMI>
            0
          </OMI>
          <OMI>
            1
          </OMI>
        </OMA>
      </OMA>
    </OMOBJ>
  </expected>
  <steps>
    4
  </steps>
  <equivalent>
    False
  </equivalent>
</reply>

