<reply result="ok" version="0.6.5 (0)">
  <incorrect equivalent="False">
    <location>
      forwardpass
    </location>
    <state>
      <prefix>
        [54,1,1,0,1,0,1,1,0,0,0,1,1,0,1,0,0]
      </prefix>
      <context>
        <item name="columnJ" value="1"/>
        <item name="covered" value="0"/>
      </context>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMI>
              0
            </OMI>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMA>
                <OMS cd="arith1" name="unary_minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    2
                  </OMI>
                  <OMV name="a"/>
                </OMA>
              </OMA>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMI>
                1
              </OMI>
              <OMV name="a"/>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </state>
    <arguments>
      <elem descr="row">
        0
      </elem>
      <elem descr="scale factor">
        1/(-1)
      </elem>
    </arguments>
  </incorrect>
</reply>

