<reply result="ok" version="0.6.5 (0)">
  <incorrect>
    <location>
      Forward pass
    </location>
    <expected>
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMI>
              0
            </OMI>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMA>
                <OMS cd="arith1" name="unary_minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    2
                  </OMI>
                  <OMV name="a"/>
                </OMA>
              </OMA>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              0
            </OMI>
            <OMI>
              0
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </expected>
    <equivalent>
      False
    </equivalent>
    <arguments>
      <elem descr="row">
        0
      </elem>
      <elem descr="scale factor">
        1/2
      </elem>
    </arguments>
  </incorrect>
</reply>

