<reply result="incorrect" version="0.5.4">
  <strategy>
    linalg.gaussianelimination
  </strategy>
  <location>
    [0]
  </location>
  <expected>
    <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
      <OMA>
        <OMS cd="linalg2" name="matrix"/>
        <OMA>
          <OMS cd="linalg2" name="matrixrow"/>
          <OMI>
            1
          </OMI>
          <OMI>
            0
          </OMI>
          <OMA>
            <OMS cd="arith1" name="minus"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  2
                </OMI>
                <OMV name="a"/>
              </OMA>
            </OMA>
            <OMI>
              2
            </OMI>
          </OMA>
        </OMA>
        <OMA>
          <OMS cd="linalg2" name="matrixrow"/>
          <OMI>
            0
          </OMI>
          <OMI>
            1
          </OMI>
          <OMA>
            <OMS cd="arith1" name="unary_minus"/>
            <OMI>
              1
            </OMI>
          </OMA>
        </OMA>
        <OMA>
          <OMS cd="linalg2" name="matrixrow"/>
          <OMI>
            0
          </OMI>
          <OMI>
            0
          </OMI>
          <OMI>
            0
          </OMI>
        </OMA>
      </OMA>
    </OMOBJ>
  </expected>
  <steps>
    6
  </steps>
  <equivalent>
    False
  </equivalent>
  <arguments>
    <elem descr="row">
      0
    </elem>
    <elem descr="scale factor">
      1/2
    </elem>
  </arguments>
  <derivation>
    <elem ruleid="Scale">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                3
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="unary_minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    2
                  </OMI>
                  <OMV name="a"/>
                </OMA>
              </OMA>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                2
              </OMI>
            </OMA>
            <OMI>
              8
            </OMI>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMA>
                <OMS cd="arith1" name="times"/>
                <OMI>
                  4
                </OMI>
                <OMV name="a"/>
              </OMA>
              <OMI>
                4
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              4
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                10
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="unary_minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    8
                  </OMI>
                  <OMV name="a"/>
                </OMA>
              </OMA>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="Add">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                3
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="unary_minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    2
                  </OMI>
                  <OMV name="a"/>
                </OMA>
              </OMA>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              2
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              4
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                10
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="unary_minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    8
                  </OMI>
                  <OMV name="a"/>
                </OMA>
              </OMA>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="Add">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                3
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="unary_minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    2
                  </OMI>
                  <OMV name="a"/>
                </OMA>
              </OMA>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              2
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              2
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="Scale">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                3
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="unary_minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    2
                  </OMI>
                  <OMV name="a"/>
                </OMA>
              </OMA>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              2
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="Add">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                3
              </OMI>
            </OMA>
            <OMA>
              <OMS cd="arith1" name="plus"/>
              <OMA>
                <OMS cd="arith1" name="unary_minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    2
                  </OMI>
                  <OMV name="a"/>
                </OMA>
              </OMA>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              0
            </OMI>
            <OMI>
              0
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
    <elem ruleid="Add">
      <OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
        <OMA>
          <OMS cd="linalg2" name="matrix"/>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              1
            </OMI>
            <OMI>
              0
            </OMI>
            <OMA>
              <OMS cd="arith1" name="minus"/>
              <OMA>
                <OMS cd="arith1" name="unary_minus"/>
                <OMA>
                  <OMS cd="arith1" name="times"/>
                  <OMI>
                    2
                  </OMI>
                  <OMV name="a"/>
                </OMA>
              </OMA>
              <OMI>
                2
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              1
            </OMI>
            <OMA>
              <OMS cd="arith1" name="unary_minus"/>
              <OMI>
                1
              </OMI>
            </OMA>
          </OMA>
          <OMA>
            <OMS cd="linalg2" name="matrixrow"/>
            <OMI>
              0
            </OMI>
            <OMI>
              0
            </OMI>
            <OMI>
              0
            </OMI>
          </OMA>
        </OMA>
      </OMOBJ>
    </elem>
  </derivation>
</reply>

