<reply result="ok" version="0.6.6 (3597)">
  <list>
    <elem ruleid="algebra.manipulation.logarithmic.logarithm">
      <expr>
        x-3 == 4^(1+1/2)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.power-ratio">
      <expr>
        x-3 == (4^3)^(1/2)
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        x-3 == 64^(1/2)
      </expr>
      <context>
        <item name="location" value="[2,1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.root">
      <expr>
        x-3 == 8
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 11
      </expr>
    </elem>
  </list>
</reply>

