<reply result="ok" version="0.6.6 (3597)">
  <list>
    <elem ruleid="algebra.manipulation.logarithmic.logarithm">
      <expr>
        1-5*x == (1/3)^(-1)
      </expr>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        1-5*x == 1/(1/3)
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-right">
      <expr>
        5*x == -2
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.times">
      <expr>
        x == -2/5
      </expr>
    </elem>
  </list>
</reply>

