<reply result="ok" version="0.6.6 (3597)">
  <list>
    <elem ruleid="algebra.manipulation.logarithmic.logarithm">
      <expr>
        4 == x^(-1)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x^(-1) == 4
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.nth-root">
      <expr>
        x == 4^(-1)
      </expr>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        x == 1/4
      </expr>
      <context>
        <item name="location" value="[2]"/>
      </context>
    </elem>
  </list>
</reply>

