<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.manipulation.logarithmic.logarithm">
      <expr>
        x-2 == 3^2
      </expr>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        x-2 == 9
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 11
      </expr>
    </elem>
  </list>
</reply>

