<reply result="ok" version="0.6.7 (3710)">
  <list>
    <elem ruleid="algebra.manipulation.logarithmic.logarithm">
      <expr>
        4 == x^(-1)
      </expr>
    </elem>
    <elem ruleid="algebra.equations.linear.flip">
      <expr>
        x^(-1) == 4
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.equation.nth-root">
      <expr>
        x == 4^(-1)
      </expr>
    </elem>
  </list>
</reply>

