<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.manipulation.logarithmic.logarithm">
      <expr>
        x-3 == 4^(1+1/2)
      </expr>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.power-ratio">
      <expr>
        x-3 == (4^3)^(1/2)
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        x-3 == 64^(1/2)
      </expr>
      <context>
        <item name="location" value="[1,0]"/>
      </context>
    </elem>
    <elem ruleid="algebra.manipulation.exponents.root">
      <expr>
        x-3 == 8
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x == 11
      </expr>
    </elem>
  </list>
</reply>

