<reply result="ok" version="1.0.5 (0)">
  <list>
    <elem ruleid="algebra.manipulation.logarithmic.logarithm">
      <expr>
        x^2-1 == 2^3
      </expr>
    </elem>
    <elem ruleid="arithmetic.operation.rational.power">
      <expr>
        x^2-1 == 8
      </expr>
      <context>
        <item name="location" value="[1]"/>
      </context>
    </elem>
    <elem ruleid="algebra.equations.coverup.onevar.minus-left">
      <expr>
        x^2 == 9
      </expr>
    </elem>
    <elem ruleid="algebra.equations.coverup.power">
      <expr>
        x == 3 or x == -3
      </expr>
    </elem>
  </list>
</reply>

